### ISSUE TITLE
display settings not saved

### ISSUE THREAD

**Issue by MariaFeodora** [Dimillian/IceCubesApp#100]
Once you quick app via right click and quit, display setting is reseted

![Image](https://user-images.githubusercontent.com/65338652/213213712-7817f1fb-574c-4c41-9925-c08f783dc2cd.png)

![Image](https://user-images.githubusercontent.com/65338652/213213882-8ef5793b-d6e8-43fe-ac7e-e4613b537046.png)

**Comment by MariaFeodora** [comment]
Hey there! There two things I would like to say: [1] I've selected the "Nemesis-Dark" theme with a custom accent color (kind of dark yellow-ish). Everytime I update the app via Testflight that accentcolor is set todark (black?). So I have to click on the already selected Nemesis theme again to reset the accent color to its default. Then I must select my own accent color again. [2] The new font scale slider on macOS is awesome. However, what I would like to see is the resizing of the scrollview when I resize the window. Actually it sticks to somewhat iOS width. You can limit the window size on macOS, that would be okay. But I'd like to use it with wider window. (-:


![Image](https://user-images.githubusercontent.com/65338652/213217481-01c3279b-7b6b-40fb-8e2f-89750bdb20f0.png)

**Comment by sgclark** [comment]
Second this. Would be great for Display options to retain specific colors and settings user chooses.  I've repeatedly had to go into Display settings to reset colors because they did not save. 

Not sure if there will be an option to publish unique themes similar to what the app Drafts does but that would be an awesome option!!

**Comment by lswee** [comment]
Agreed. I can see #277 mentions it being a bug when Match System is enabled.

I've requested a feature (#314) to to set different colours for Light and Dark mode.

**Comment by Raphty** [comment]
Also an issue on the iOS version.

**Comment by henrik** [comment]
Seeing this as well on macOS. To make things worse, for some reason it resets to a black accent colour with my dark theme, making it unusable until I configure it again, or give up and switch to "Match System".

<img width="495" alt="Screenshot 2023-02-21 at 21 27 36" src="https://user-images.githubusercontent.com/216/220462339-43b4acca-33cd-4ec1-87e0-c0fe47472502.png">
