### ISSUE TITLE
cancel doesn’t work

### ISSUE THREAD

**Issue by MariaFeodora** [Dimillian/IceCubesApp#101]
Pressing reply and then cancel, doesn’t work 🤔

![Image](https://user-images.githubusercontent.com/65338652/213214585-76b6fa0a-d657-4087-ba13-548c6b43d869.png)

**Comment by jsynowiec** [comment]
Works for me on 1.0 (892) on iOS and macOS. It displays the delete/save draft prompt. Clicking either closes the reply post composer.

**Comment by rafaelcaricio** [comment]
It happened once, now I cannot reproduce. 🤔

**Comment by Dimillian** [comment]
Same I saw it a few times and I don't know how to reproduce as of yet.

**Comment by jimrhiz** [comment]
It also happened once for me, after I had added a quiz to the draft post. As I could not cancel, I had to kill the app. I could not reproduce the bug when I tried again.

I wonder if the visual "Cancel" label and the area you have to touch to activate it are not in the same place.
