### ISSUE TITLE
Double tap to "confirm" dialog when favoriting/boosting a post

### ISSUE THREAD

**Issue by MariaFeodora** [Dimillian/IceCubesApp#103]
Liking Icecube a lot so far after having tried several other Mastodon apps. My only feedback would be to ask for an optional "confirm" dialog when favoriting/boosting a post. Perhaps an option to require a double tap to favorite/boost so I don't hit it accidentally? Thank you for the work so far, can't wait for the public release!

**Comment by a-dows** [comment]
+1 for this enhancement. Preferably these would be separate toggles, as the "stakes" for accidentally boosting are much higher than for faving.
