### ISSUE TITLE
Bug: app crashes when visiting some users profile

### ISSUE THREAD

**Issue by mikkkee** [Dimillian/IceCubesApp#1035]
## Environment:

 - OS: 
iOS v16.1.1
 - IceCubesApp version: 
IceCubesApp v1.5.7

## Description

App crashes immediately when I visit some users profile, one example profile is this https://mas.to/@tezoatlipoca

## Related Issues

Didn't find any relates issues after searching for "crash" in open issues.

**Comment by sothawo** [comment]
Works for me on iOS 16.3.1
![Uploading C3313B29-2455-497D-8694-212CA4B08FCB.jpeg…]()

**Comment by sothawo** [comment]
![6A48F558-65DA-4243-B06D-6724B5A7B76A](https://user-images.githubusercontent.com/8456476/220953657-f7b60979-7a56-403c-ac0b-e3ef0c0dbbc6.jpeg)

**Comment by mikkkee** [comment]
Thanks is there a way for me to send crash logs?

**Comment by Dimillian** [comment]
Could you update to iOS 16.3? There is indeed a crash an earlier iOS version but it's not happening on the latest one. we have a few other issues closed about it.

**Comment by blueturtleai** [comment]
Just tried it with 16.2 and it didn’t crash either.

**Comment by mikkkee** [comment]
Thanks it doesn’t crash any more after updating to iOS 16.3.1

**Comment by mikkkee** [comment]
Works in iOS 16.3.1

**Comment by mikkkee** [comment]
Works in iOS 16.3.1

**Comment by tezoatlipoca** [comment]
Sorry my profile borked your app. :(
