### ISSUE TITLE
Menus opening up in the top left corner of the screen

### ISSUE THREAD

**Issue by MariaFeodora** [Dimillian/IceCubesApp#104]
![Image](https://user-images.githubusercontent.com/65338652/213218273-07891462-2c8a-4e98-8cf6-29adaf0d606d.png)

**Comment by jsynowiec** [comment]
Displays correctly for me on 1.0 (892) on macOS Ventura 13.1 on Apple Silicon.

<img width="395" alt="Screenshot 2023-01-18 at 16 48 03" src="https://user-images.githubusercontent.com/1029142/213219527-74215edd-6d52-4f0b-a7c0-4a98cd2f9a30.png">

The one difference I see from the screenshots is that you have a MacBook with a notch and the larger menu bar. Maybe there's something specific about it to handle.
