### ISSUE TITLE
Feature request: new icon for bot accounts 

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#1043]
Imo the new gear icon for bot accounts is not very intuitively understandable. I understand, that the used font doesn’t offer a robot icon. But would it be possible to use Unicode instead? Not sure, if this would work in all clients.
![A5C6CDEB-13DC-4F41-9245-9A10392A9D6B](https://user-images.githubusercontent.com/113246030/221138064-565d7813-d590-4f25-b067-4eb2723e4667.jpeg)

**Comment by Havhingstor** [comment]
This Unicode character is currently used for the setting to show the ChatGPT integration. If it is used for bot accounts, we should change the other icon, as both aspects aren't related.

**Comment by blueturtleai** [comment]
The bot account icon has been changed. Although I think the new icon is still not really intuitively understandable, it’s better than the gear before 😀.
