### ISSUE TITLE
Feature request: favoriting direct messages in dm tab

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#1044]
It should be possible to favorite a direct message directly in the direct message tab. Currently this can only be done in the notifications tab or the home timeline.

**Comment by paul4565** [comment]
You can do this if you long press on the message inside the conversation. I had requested this as well.

**Comment by blueturtleai** [comment]
Okay, thanks for the information! I‘d suggest, that favoriting is added to the … menu too.

**Comment by blueturtleai** [comment]
Fixed in #1053
