### ISSUE TITLE
Bug: No Photo Access

### ISSUE THREAD

**Issue by Mjocfl** [Dimillian/IceCubesApp#1046]
## Environment:

 - OS: iOS v16.4
 
 - IceCubesApp version: v1.5.8
 

## Description
Cannot add photo to post. App allows me to select photos from photo library, but does not add any photos to the post. iOS settings indicate app only has one-time photo selection permissions and cannot access photos. 

## Related Issues

 - [ X ] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
It's an iOS 16.4 beta issue, nothing I can do about it until Apple fix it.

**Comment by Mjocfl** [comment]
Thank you for the information!
