### ISSUE TITLE
Bug: No. of boosts on timeline posts not refreshed until a new one added.

### ISSUE THREAD

**Issue by paul4565** [Dimillian/IceCubesApp#1050]
## Environment:

iOS 16.3.1
IceCubesApp 1.5.8
## Description
Number of boosts shown on a post on the home feed is not refreshed until you add another. 
## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
I'm closing this one as it's a more general bugs that posts activities is not "live" or shared. I plan to work on that a bit later. And there is some more generic issue somewhere in the list.
