### ISSUE TITLE
Feature request: Add followed Hashtags to a List

### ISSUE THREAD

**Issue by loremipsum2022** [Dimillian/IceCubesApp#1055]
I'm not sure if it's technically possible, but it would be great if you could add a hashtag you follow to an existing list. Maybe you could then additionally hide the respective hashtag from the home timeline.

**Comment by sothawo** [comment]
Lists are managed on the mastodon instance. I had a look at the API, it does not seem possible to add a hashtag to a list, only ids of accounts one is following.

**Comment by Dimillian** [comment]
Sorry not really planed at this point as I want to stay close to the API.
