### ISSUE TITLE
Bug: iPad Slide over 2 columns

### ISSUE THREAD

**Issue by EvilOne** [Dimillian/IceCubesApp#1058]
## Environment:

 - OS: 
iPadOS 16,3,1
M1 iPad Pro
 - IceCubesApp version: 
1,5,9

## Description

2 column display is an available option when used in Slide Over view. Because it looks bad, it shouldn't be an option.

![IMG_0829](https://user-images.githubusercontent.com/169561/221360760-797bb181-cd00-40bd-b442-8e531bece12c.jpg)

## Related Issues

 - [X] Search that these bugs don't already exist before creating it.

**Comment by outadoc** [comment]
+1, I would even that the slide-over mode on iPad should use the same layout as on an iPhone; not only should the split-view be disabled, it would also be much better to have bottom navigation with this narrow window.

**Comment by Dimillian** [comment]
Slideover is now iPhone layout, in next version
