### ISSUE TITLE
Bug: iPad Stage Manager

### ISSUE THREAD

**Issue by EvilOne** [Dimillian/IceCubesApp#1060]
## Environment:

 - OS: 
iPadOS 16,3,1
M1 iPad Pro
 - IceCubesApp version: 
1,5,9

## Description
The app is slow to refresh when resized in Stage Manager. Please take a look at the attachment.

https://user-images.githubusercontent.com/169561/221361085-a7c20429-c8fa-4aae-8732-ecd3825cc2b4.MP4

## Related Issues

 - [X] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Fixed
