### ISSUE TITLE
Feature request: new icon-color for DMs in the activity tab

### ISSUE THREAD

**Issue by rstockm** [Dimillian/IceCubesApp#1064]
As we all know, DMs on Mastodon are just "special" mention postings. Nevertheless, IceCubes offers a dedicated DM-Tab, which is a good thing IMHO.
But: the activity - list renders DM just like normal mentions, which is confusing in terms of UX. Just these little pixels change:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/3195116/221367069-5db964b1-35c2-4bcf-8124-a39d40467b34.png">

Which is way to subtle.

## suggestions

a) make the circular indicator a new one, maybe orange, and use the DM icon:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/3195116/221367119-a5e0be75-a585-4015-a808-8e3c7bccddf0.png">
and/or
b) give DMs a different (configurable via settings) background color.

**Comment by Dimillian** [comment]
<img width="90" alt="image" src="https://user-images.githubusercontent.com/535509/221370324-f71fa378-2144-476c-ae20-5d0741be02c9.png">
All good now :) this was a great suggestion!

**Comment by rstockm** [comment]
Splendid 🙏
