### ISSUE TITLE
Bug: Emojis in username rendered too small

### ISSUE THREAD

**Issue by santisbon** [Dimillian/IceCubesApp#1066]
## Environment:

 - OS: 
iOS 16.3.1, iPadOS 16.3.1, macOS 13.2.1
 - IceCubesApp version: 
IceCubesApp 1.5.9

## Description

When a username contains custom emojis, they are rendered really small and slightly misaligned. The size makes it hard to tell what the emoji is. 

This image show the difference between IceCubesApp (left) and the Mastodon web UI (right). The image is magnified but in real life the emoji is so small you can't really tell what it is.

![Comparison](https://i.imgur.com/Iho2CSB.png)

**Comment by santisbon** [comment]
> IMHO using emojis in usernames is not a nice thing. It clutters the timelines and screenreaders have lots of problems with this... imagine you are blind and your computer has to read loud each imoji in each username...
> 
> Therefore i'd like to see an option to hide those emojis in usernames...

Yes, clients can hide username emojis or all emojis if desired (some like Mammoth already do). For those who want to see emojis, which is most users, it's best to display them properly.

**Comment by phpmacher** [comment]
> For those who want to see emojis, **which is most users**

Do you have a source for this?
From my experience, I would see it differently.

Apart from that, display inconsistencies are of course also important to be reported.

**Comment by Dimillian** [comment]
CC @divadretlaw, I saw that too. The size seems nice now but the offset is kinda off. I wonder if you can use firstBaseline alignment in your library? Or maybe something else is going on?
