### ISSUE TITLE
Bug: No Cancel button on Custom Emoji pop up

### ISSUE THREAD

**Issue by jmb** [Dimillian/IceCubesApp#1073]
## Environment:

 - OS: iOS 16.13.1
 - IceCubesApp version: v1.5.9

## Description

When opening the Custom Emojis dialogue in compose, there is no obvious way to dismiss the pop up. There probably should be a Cancel button.

**Comment by sothawo** [comment]
I just tap into the edit field again and then the custom emoji popup closes
