### ISSUE TITLE
problem with menu bar, its not hidden while scrowling

### ISSUE THREAD

**Issue by MariaFeodora** [Dimillian/IceCubesApp#108]
Something gone wrong with the menu bar.

![Image](https://user-images.githubusercontent.com/65338652/213221633-5bc00b0c-d93c-4b6c-9552-ebf52cd2621d.png)

**Comment by ScottChampagne** [comment]
Experienced this as well.

**Comment by kckd** [comment]
I’ve seen it on the top bar as well. Looks like it might be setting the background view to transparent or hidden but its child views are still visible.
