### ISSUE TITLE
Bug:Public post visibility diminished by a boost. 

### ISSUE THREAD

**Issue by paul4565** [Dimillian/IceCubesApp#1096]
## Environment:

 - OS: 16.3.1
 
 - IceCubesApp version: 1.5.10
 

## Description

Original public post boosted by my contact to followers only appears as followers only against the original, and prevents boosting. 
## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
What?

**Comment by paul4565** [comment]
Ok, so I see a post she has boosted in my home timeline. She always boosts to followers only. If I want to boost it I have to touch on the post so I'm seeing it from the original author and then boost it. If I touch on the boost icon in the timeline, it does nothing. This seems different to other apps. Sorry if I made no sense.

**Comment by paul4565** [comment]
Also, it seems like the author posted it to his followers only, but he didn't. See attached grabs:-
![image](https://user-images.githubusercontent.com/126080192/221667519-1c8d2cd3-0b0c-4c6e-a0eb-94e55c4cd89a.jpeg)

![image](https://user-images.githubusercontent.com/126080192/221667572-baa61522-4884-426b-956b-d396e3e23b04.jpeg)

**Comment by paul4565** [comment]
Also, it seems like the author posted it to his followers only, but he didn't. See attached grabs:-

![image](https://user-images.githubusercontent.com/126080192/221668803-127b6e7d-0400-4876-83a3-e1ac4a2bf21b.jpeg)

![image](https://user-images.githubusercontent.com/126080192/221668830-f7bd7ac1-5813-44fb-99f6-112cc1e48413.jpeg)
