### ISSUE TITLE
Feature request: ability to edit image description / alt text

### ISSUE THREAD

**Issue by LauraLangdon** [Dimillian/IceCubesApp#1110]
Currently it seems to be impossible to edit an image's description / alt text, and it would be great to be able to do this! It's possible in other clients, so doesn't seem to be an API restriction.

**Comment by Dimillian** [comment]
It's totally possible. if your instance is up to date (4.1), the app support it.

**Comment by LauraLangdon** [comment]
Yes, [my instance](https://github.com/hachyderm/hachyderm) is up to date, and I'm able to edit image descriptions using Ivory and Mona, but don't see an option for this on Ice Cubes. I can edit a post containing an image, but I can't edit the image description.

To be clear, I'm referring to editing an image's description after posting, not creating the image description before posting.
