### ISSUE TITLE
Local Timeline Jumps Randomly

### ISSUE THREAD

**Issue by pdxvr** [Dimillian/IceCubesApp#1122]
I don't understand how the local timeline loads, sometimes it loads and stays where I last was and gives me an unread count, other times it scrolls to the latest posts.  If there is some logic to how this works, I would like to know what it is so I can try to make it retain the last position where I left off.  If it's a bug or just not quite resolved, I'd like to see a setting to either stay at last place or scroll to newest.

**Comment by Dimillian** [comment]
It won't save like the home timeline. It only stays where you left off if you pull to refresh on it. For now is this excepted. If you swap between timeline if'll always be on the latest status.
