### ISSUE TITLE
Feature request: improve speed to start longer videos 

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#1136]
Currently it takes very long until a larger video in a post starts playing. For a 58s video it takes about 2 minutes until playback starts after tapping on the start button. I tried the same in the web frontend, where the video started immediately.

Until the video starts, I can use the app, but no other media (images/videos) is displayed. All are blurry and the wait cursor is shown.

**Comment by Dimillian** [comment]
Do you have a link to a post with this video?

**Comment by blueturtleai** [comment]
https://mastodon.social/@pallenberg/109952854905999271

**Comment by blueturtleai** [comment]
Were you able to reproduce the problem?

**Comment by flodavid** [comment]
I have the same problem, needing to wait for the full video to be downloaded  to play it. What is strange that the preview are playing instantly, only when clicking on it to have the sound does it redownload the whole thing

**Comment by blueturtleai** [comment]
Fixed by the new media viewer.
