### ISSUE TITLE
Bug: Some text and icons are unreadable with light tint colors

### ISSUE THREAD

**Issue by mcchots** [Dimillian/IceCubesApp#1140]
## Environment 

 - OS: iOS 16.3.1
 - IceCubesApp version: 1.5.12

## Description

Text and icons on polls and labels appear in the white default font when a light hue tint is used. This renders it difficult to see and sometimes impossible. 

See attached images for a better visual explanation. 
![image](https://user-images.githubusercontent.com/975793/222501532-4b870e89-5dea-40b7-a70b-9c1e0e1fe3f2.jpeg)

![image](https://user-images.githubusercontent.com/975793/222501733-ed297e71-4b2d-48c3-817a-37e027f655cc.jpeg)

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Closing this one. Choosing your own color, it's up to you to make a readable theme

**Comment by stepheneb** [comment]
In case someone gets here and wondered how to do this

Profile > Settings > Display Settings > Tint Color

Here's what the results of a poll look like now with a similar yellow with the opacity reduced to about 0.3

![image](https://github.com/Dimillian/IceCubesApp/assets/7188/033651a5-c776-467e-9a57-591f775ddef4)
