### ISSUE TITLE
Github issue cleanup

### ISSUE THREAD

**Issue by sothawo** [Dimillian/IceCubesApp#1142]
Currently Github shows 222 open issues, looking at the project I see 119 open bugs and feature requests.. Would be nice if issues moved to done could be closed so it's easier to see which bugs and features are really open.

![image](https://user-images.githubusercontent.com/8456476/222553970-9d1fa138-b7f4-4989-bf5d-9a1a7404de46.png)

**Comment by Dimillian** [comment]
It's more that they're not all in that project. I have to add them manually

**Comment by Dimillian** [comment]
I did quite a cleanup yesterday :)
