### ISSUE TITLE
Bug: filtered post show with a small empty space

### ISSUE THREAD

**Issue by sothawo** [Dimillian/IceCubesApp#1175]
## Environment:

 - OS: 
   iOS 16.3.1
 - IceCubesApp version: 
1.6.0

## Description

looks like filtered posts still show up

![IMG_7645](https://user-images.githubusercontent.com/8456476/222954565-c9707078-dbb7-4fa3-89a9-4713a1bd1d49.jpg)

**Comment by Dimillian** [comment]
Yes I had to make an adjustment for performances reason. Will see how to fix properly later.

**Comment by sothawo** [comment]
and I even can swipe on them and invoke context actions

**Comment by sothawo** [comment]
🎉
