### ISSUE TITLE
Bug: display setting "match system" does not switch from dark to light or back

### ISSUE THREAD

**Issue by sothawo** [Dimillian/IceCubesApp#1176]
## Environment:

 - OS: 
16.3.1
 - IceCubesApp version: 
1.6.0

I have set the design to match system, but when my phone switches to light during the day, IceCUbes stays on dark - and the same in the other direction.

**Comment by jemus42** [comment]
I have observed a similar behavior but in my case it only affects the top few posts in the notifications tab, not the home timeline.
I can reproduce it by switching from any light to any dark theme and switching between notification and home timeline tab.

**Comment by sothawo** [comment]
Hm, the switching worked yesterday evening and this morning with the latest version. I’m closing this now
