### ISSUE TITLE
Bug: Many aspects of Calckey are broken

### ISSUE THREAD

**Issue by ThatOneCalculator** [Dimillian/IceCubesApp#1181]
## Environment:

 - OS: 16.3.1 (iPhone 13 Pro Max)
 - IceCubesApp version: 1.6.2 (Latest App Store version as of this issue's creation)
- Instance: https://stop.voring.me (Calckey v13.2.0-dev14 (latest commit on dev branch))

## Description

As Calckey continues to add Mastodon API compatibility, we find that iOS clients tend to have more problems than Android ones. We just got auth working, but many things don't work:

- Loading posts
- Loading profiles
- Loading timelines
- Loading trending
- Loading notifications
- Searching
- File uploads 

The following works but still throws an error for some reason:

- Posting (no media)

The following works as expected:

- Auth/logging in
- Instance information
- Viewing your own name, profile picture, followers, follows, and post count

![IMG_3241.png](https://user-images.githubusercontent.com/44733677/223009995-d72332f0-9ce3-4062-bcdb-fc2966f411d9.png)

![IMG_3244.png](https://user-images.githubusercontent.com/44733677/223009997-c086d60f-c860-4e7e-84c1-7ea6e4f3066a.png)

![IMG_3242.png](https://user-images.githubusercontent.com/44733677/223009994-3d77302d-6018-4786-be31-bab970f89bab.png)

![IMG_3243.png](https://user-images.githubusercontent.com/44733677/223009996-8d5044b4-d9f3-4a58-8e52-071aedc69df3.png)

**Comment by juandesant** [comment]
No extra details to add to this ticket, other than the same behavior is experimented on version 1.6.15 and https://calckey.social/

**Comment by zotanmew** [comment]
All of these (except trending) should be working on latest calckey develop builds.

**Comment by ThatOneCalculator** [comment]
Yep, and thank you for your hard work on that! Closing in favor of #1485.
