### ISSUE TITLE
Scrolling janky on MacOS

### ISSUE THREAD

**Issue by selfagency** [Dimillian/IceCubesApp#119]
This may not be an issue restricted to your app but possibly with cross-platform Swift apps generally, but when I scroll with my mousewheel inside the app on desktop, half the time the scroll is entirely unresponsive.

**Comment by alakoring** [comment]
On iPad, sometimes when I scroll, the app then scrolls itself. So this may not be Mac-specific (even though the symptom is different).

**Comment by pedromorais-raidiam** [comment]
It's happening for me on iOS, scrolling is too jittery to be usable, the scroll bar (the one you press and hold) jumps like crazy when you're scrolling, even when there's no content loading.

**Comment by pedroCX486** [comment]
It's happening for me on iOS, scrolling is too jittery to be usable, the scroll bar (the one you press and hold) jumps like crazy when you're scrolling, even when there's no content loading.

**Comment by alakoring** [comment]
Confirm, 1.0.10 on iPad may jump a bit as you scroll with the scroll bar.

**Comment by pedroCX486** [comment]
I made a video showing my issues: https://youtube.com/shorts/bA2UbNRBsJQ?si=EnSIkaIECMiOmarE

Sorry for the shorts format, YouTube forced it due to the orientation.

**Comment by Dimillian** [comment]
This is not something I'll be able to solve with SwiftUI sorry.

**Comment by Dimillian** [comment]
I didn't even knew you could scroll with the scroll bar on iOS. Is it an accessibility thing? Because it's visually distracting I can disable it.

**Comment by alakoring** [comment]
It’s a good way to scroll large distances. IMO you should absolutely not disable basic scrolling functionality. Maybe need to report a bug to Apple if this is basic SwiftUI bugs.

**Comment by EmilJacobs** [comment]
Made a video about the scrolling behaviour in 1.4.5. This certainly is janky, heh.
https://youtu.be/j9Ncka1ZzWw

**Comment by Dimillian** [comment]
Yep. Scrolling up on macOS is not great :/ but it's hard to see what I can do unfortunately.

**Comment by Dimillian** [comment]
Duplicate

**Comment by pedroCX486** [comment]
> Duplicate

Shouldn’t the other one be a duplicate since this one is older and contains more context like videos?
