### ISSUE TITLE
Bug: Reply to a long post includes the "long post" warning from original?

### ISSUE THREAD

**Issue by LorenAmelang** [Dimillian/IceCubesApp#1196]
## Environment:

 - OS: 16.3.1
 
 - IceCubesApp version: 1.6.3
 

## Description

![Reply include long post warning](https://user-images.githubusercontent.com/1297090/223625032-e7d2f7f5-40b4-4525-b8e5-a8304b82387c.png)

That warning is exactly what topped the (very) long post I replied to. Seems wrong...  

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
This is just standard feature. When replying, it takes the content warning. You're free to change it or remove it.

**Comment by LorenAmelang** [comment]
Ah, I see now that if I tap the triangle icon that line disappears. But what I didn't get before is that it would be part of my post. In the composition window it is at the very top, not in the section where I type my reply. Could it appear after the named reply targets? Where I know I can delete people I don't want targeted? Much more intuitive...
