### ISSUE TITLE
Rendering of this post feels wrong

### ISSUE THREAD

**Issue by palaniraja** [Dimillian/IceCubesApp#12]
Please check the post - https://geeknews.chat/@arstechnica/109606762427600086

and it rendered the image and the card which has the image (attached)

I am not sure what is happening but it feels like duplicate rendering. if it is going to render a card then no need to show the asset/attachment?

https://geeknews.chat/@arstechnica/109606762427600086

![screenshot](https://user-images.githubusercontent.com/124864/210127587-ba24cb3b-9e87-429e-8085-2932a215bb38.png)

**Comment by Dimillian** [comment]
Yup, I saw that. I guess if there is an image then the card should not render? But what if the image is note related to the link?

**Comment by palaniraja** [comment]
Cool

I was thinking, if there is a card we can ignore any attachment? assuming leaving the implementation decision to the card?
