### ISSUE TITLE
Bug: Cannot add new words to filters

### ISSUE THREAD

**Issue by Maskross** [Dimillian/IceCubesApp#1206]
## Environment:

 - OS: iPadOS 16.3.1
 
 - IceCubesApp version: 1.6.4
 

## Description

When trying to create a new filter or update an existing one, new words aren’t added. Every other change, like changing the title or removing words is updated accordingly, but new words are not.
## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by sothawo** [comment]
the same issue as #1184?

**Comment by Maskross** [comment]
Yes, it seems to be the same. Didn't see that issue even tho I looked for them before making this one. My apologies.
