### ISSUE TITLE
[Bug] New posts indicator is not always tappable

### ISSUE THREAD

**Issue by jsynowiec** [Dimillian/IceCubesApp#121]
I noticed, that since one of the recent builds, the new posts indicator on timeline is not always tappable. Nothing happens when I tap on it. I'm not sure what are the conditions, as I wasn't able to reliably reproduce the issue.

![IMG_7137](https://user-images.githubusercontent.com/1029142/213478946-bb068e21-5381-485a-8d42-da2b762c925e.jpeg)

**Comment by jimrhiz** [comment]
Possibly similar to #101 where the Cancel button sometimes doesn't work when composing a new post? That one is not reproducible either.
