### ISSUE TITLE
Feature request: TootSDK for all major servers (Mastodon, Pleroma, PixelFed etc).

### ISSUE THREAD

**Issue by LorenAmelang** [Dimillian/IceCubesApp#1227]
No idea if this could fit with IceCubes, but I'd love to see other servers than just Mastodon!

https://github.com/TootSDK/TootSDK

When app developers build apps for Mastodon and the Fediverse, every developer ends up having to solved the same set of problems when it comes to the API and data model.

[Konstantin](https://m.iamkonstantin.eu/konstantin) and [Dave](https://social.davidgarywood.com/@davidgarywood) decided to share this effort. TootSDK is a shared Swift Package that any client app can be built on.

Key Principles ⚙️
Async/Await based. All asynchronous functions are defined as Async ones that you can use with Async/Await code
Internal consistency and standardization of model property names
Standardization across all supported Fediverse APIs
Platform agnostic (TootSDK shouldn't care if it's on iOS, macOS or Linux!)

Project Status 📈
Mastodon - Nearly there
Pleroma - Nearly there
Pixelfed - Nearly there
Friendica - Nearly there
Akkoma - Nearly there
Writefreely - To do

**Comment by Dimillian** [comment]
Closing this for now. I'm too far ahead in the app to switch a whole underlying aspect of it. But there are other issues open there about supporting other server than mastodon! You can search and contributes on them!
