### ISSUE TITLE
Feature request: Move icons down when labels off

### ISSUE THREAD

**Issue by brayozz** [Dimillian/IceCubesApp#1232]
Hi,

Just an idea for improving the UI. When labels are off, we have this huge empty area below them. It would look much better when the option labels = off to pull those icons down or make them a bit bigger.

![image](https://user-images.githubusercontent.com/25374150/224565782-fcba15f3-6c8f-4860-89d3-4375663a3954.jpeg)![image](https://user-images.githubusercontent.com/25374150/224565786-6c8532c7-4e71-4ecd-8a2f-fc50cb18ea6c.jpeg)

**Comment by Dimillian** [comment]
Duplicate and not possible currently with SwiftUI.
