### ISSUE TITLE
Bug: Automated adding of #Tags at the end in editing mode deletes text

### ISSUE THREAD

**Issue by haugjp** [Dimillian/IceCubesApp#1235]
## Environment:

 - OS: 
iOS 16.3.1
 - IceCubesApp version: 
 IceCubes 1.6.5

## Description

When adding Tags (#) via the new "Add #Tags after my text" option in editing mode (after publishing a post), the tags get added, but the original text is deleted. This does not happen, when choosing the option "Add #Tags in place". The text is still recoverable with the option "Restore previous text".
I could not reproduce this issue with every one of my posts, only with a longer one, which would exceed the allowed character count when the tags get added. 
This behaviour is not influenced by the use of (german) special characters like ä, ö, ü, although those characters where present in the post, this behaviour first occurred. 

![IceCubes_br1_01](https://user-images.githubusercontent.com/127724581/224641364-126fbfd8-c54f-4d63-8596-71e5e4dea69f.png)
![IceCubes_br1_02](https://user-images.githubusercontent.com/127724581/224641370-5b867f88-cf30-4555-9c05-97a840fa3496.png)

## Related Issues

I have not found any related bug reports.

**Comment by Dimillian** [comment]
Should be fixed in the next (upcoming) version.
