### ISSUE TITLE
Bug: accounts displayed multiple times

### ISSUE THREAD

**Issue by m4h4** [Dimillian/IceCubesApp#1269]
## Environment:

 - OS: 16.3.1
 
 - IceCubesApp version: 1.6.7
 

## Description
Accounts are displayed twice![image](https://user-images.githubusercontent.com/34862998/226100297-bd93ff97-ff76-44fe-b0b8-52758be30bcf.png)

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
You can delete one. You probably added it twice?
