### ISSUE TITLE
Feature request: make strings localisable

### ISSUE THREAD

**Issue by xabirequejo** [Dimillian/IceCubesApp#1287]
I've got two requests:

1) There are some strings that seem to be taken from system localisation (_Cancel_ and _Back_ are the ones I've seen, within the Explore, Profile and Settings screens). However, if iOS doesn't support the language (eg: Basque), the strings are shown in English (or fallback language). So my first request is to make said strings independent from the system. See attached pictures.

![IMG_3371](https://user-images.githubusercontent.com/888924/226490589-ef4933c6-22e9-4122-94cb-66595fc7c4d4.jpeg)

![IMG_3372](https://user-images.githubusercontent.com/888924/226490594-a2edda17-4863-4dbe-86c3-c2fef2452e7f.jpeg)

2) Within settings > display settings there is this _Theme_ area. My second request is to have one string for the Theme heading and another one for the Theme setting itself, so that the main one can be translated as Appearance and the latter as Theme.

![IMG_3370](https://user-images.githubusercontent.com/888924/226491209-63d7272d-cbfe-4ee9-8aac-ae03e249572a.jpeg)

**Comment by Jerry23011** [comment]
If anyone has time, maybe consider making `Edit History` localizable as well. Thanks in advance.
![1](https://user-images.githubusercontent.com/89069957/226560734-92b65b07-cddb-437f-a79f-71d09e39c8bc.jpeg)
