### ISSUE TITLE
Custom tint color didn't persist?

### ISSUE THREAD

**Issue by palaniraja** [Dimillian/IceCubesApp#13]
Changed the Tint color before updating the app. And updated the app from testflight. Now it defaults to previous default color not the one i selected

**Comment by Dimillian** [comment]
The format of Theme changed, for you'll have to setup your custom theme once more. Sorry for the inconvenience.

**Comment by jtraulle** [comment]
Hello @Dimillian,

Every time that the app has an update, I loose my custom tint color.
Last time with update 1.10.34 this morning.
