### ISSUE TITLE
Bug: Instant crash with new 1.6.9 version

### ISSUE THREAD

**Issue by LorenAmelang** [Dimillian/IceCubesApp#1308]
## Environment:

 - OS: iOS 16.3.1
 
 - IceCubesApp version: 1.6.9
 

## Description

Just updated to 1.6.9, via the Ice Refills shortcut. Open shows the default (empty posts) Home timeline screen for an instant, then crashes back to my iPhone home screen. Double click of the phone's home button shows the IceCubes header over a pure black window. Hard kill, try again, same crash. 

Surprised this isn't here already...  Maybe only happens on my tiny iPhone SE2020 "2ndGen"? In dark mode? With multiple instance timelines signed in, and several "peek at" "local timelines"? 

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Could you delete and reinstall the app and tell me?

**Comment by LorenAmelang** [comment]
That worked! Said it would delete all the app data, but it didn't, all my accounts and settings are still working. Is there a way to save/restore them in case...

**Comment by perry-mitchell** [comment]
Deleting and reinstalling also worked for me.

**Comment by LorenAmelang** [comment]
My iPad 12.9 5gen (with only my main instance) updated itself later that day, and crashed the same way when I first opened IceCubes. Delete and reinstall fixed it, too. Both devices moved on to 1.6.10 with no issues...

**Comment by SabineSW** [comment]
I am experiencing an immediate crash since this afternoon with 1.6.10 with my iphone (13&14 ios 16.3.1 & MacBook Air MacOS Ventura 13.2.1).
Here is an crash report from the MacBook:
[icecubes_crash_report.txt](https://github.com/Dimillian/IceCubesApp/files/11113093/icecubes_crash_report.txt)

**Comment by SabineSW** [comment]
Deleting and reinstalling icecubes did not help (neither on my iphone nor on my macbook!

**Comment by Dimillian** [comment]
Fixed now.
