### ISSUE TITLE
Unable to add account with a password manager filling form

### ISSUE THREAD

**Issue by krzysztofjeziorny** [Dimillian/IceCubesApp#131]
Trying to add an account on iPad mini w Bitwarden password manager: As soon as the prompt to unlock the manager (with touch button) to fill-up the login data appears, the login form page is gone.

iPadOS 16.2
AppStore version of the app (not TestFlight)

**Comment by Subsurface-divelog** [comment]
initially I had the same problem with 1Password on iPad, but after a few tries I was able to make it work - but at least five or six times it either jumped back to "add account" or tried to validate my login without offering me a chance to enter the 2FA code...

**Comment by dirkhh** [comment]
initially I had the same problem with 1Password on iPad, but after a few tries I was able to make it work - but at least five or six times it either jumped back to "add account" or tried to validate my login without offering me a chance to enter the 2FA code...

**Comment by atomicbird** [comment]
Same thing happened to me with autofill from 1Password and iCloud passwords. Copying and pasting worked. No error messages, but the add account UI would reappear repeatedly.

**Comment by Dimillian** [comment]
Weird, it's just a Safari View, I'll look.

**Comment by johncarney** [comment]
Can confirm that the password manager login flow on iPad is flaky. I was trying to log in using keychain on iPad and the login box kept crashing out. I eventually got connected. I did not have this problem on iPhone.
