### ISSUE TITLE
Bug: Changing app icon no longer works

### ISSUE THREAD

**Issue by alakoring** [Dimillian/IceCubesApp#1321]
## Environment:

 - OS: iPadOS 16.4 (20E246)
 
 - IceCubesApp version: 1.6.9
 

## Description

App did not display custom icon after update. Changing custom icon does not work.

## Related Issues

 - [ x ] Search that this bugs don't already exist before creating it.

**Comment by Havhingstor** [comment]
Did you test it on the iPhone too? If not, it's probably fixed with #1310 in version 1.6.10, which is already finalized.

**Comment by alakoring** [comment]
I did not test on iPhone. It is working in 1.6.10 (once that became available through App Review).
