### ISSUE TITLE
Unable to add hackyderm.io account

### ISSUE THREAD

**Issue by TheLocehiliosan** [Dimillian/IceCubesApp#133]
Under "Add account", I type "hackyderm.io", the instance info populates below, and I click "Sign in".

The sign in button text briefly changes to a spinner, and then goes back to "Sign in".

A login page is never presented.

**Comment by cro** [comment]
I see this behavior too with my self-hosted Pleroma instance.

**Comment by sts10** [comment]
FWIW, I just signed in successfully to my https://hachyderm.io account on my iPhone. Are you sure you used an 'h' rather than a 'k'?

**Comment by dirkhh** [comment]
It took me several tries - but I've been using the app with my hachyderm.io account for a few hours now. But there's definitely something odd going on with the sign-in experience (in my case it was a combination of the web browser window, the password manager (1Password) and the 2FA follow up question - and it took at least half a dozen tries before this all collaborated cleanly)

**Comment by TheLocehiliosan** [comment]
> FWIW, I just signed in successfully to my https://hachyderm.io account on my iPhone. Are you sure you used an 'h' rather than a 'k'?

I think this was probably my issue.

I looks like hacKyderm redirects to the actual site, so that's likely why the info loads.

**Comment by cro** [comment]
Reviewing the Pleroma logs it appears that Pleroma is returning a 400.  I might try to debug this over the weekend.

**Comment by Dimillian** [comment]
FYI we have #140 open for supporting Plemora, GTS and more. I would love for someone to look at it.
