### ISSUE TITLE
Bug: VoiceOver reads posts hidden by filter

### ISSUE THREAD

**Issue by pitermach** [Dimillian/IceCubesApp#1331]
## Environment:

 - OS: iOS 16.4
 
 - IceCubesApp version: 1.6.10
 

## Description

When you set a Mastodon filter up to hide posts, in the timeline icecubes then displays them as "filtered by $FilterName" with a Show anyway button to reveal it. However, if you read that post with VoiceOver, it just reads the post in full as if it wasn't filtered at all. Ideally, it should work like it does for posts behind a CW now, so VoiceOver would first just read the filter and require a double-tap to reveal the post.

Awesome work on the accessibility improvements, by the way. Other than this issue the app works really well and I love all the little sound effects throughout it!

**Comment by Dimillian** [comment]
CC @nesevis
