### ISSUE TITLE
App crashes if you tap a malformed Mastodon account link

### ISSUE THREAD

**Issue by jkachel** [Dimillian/IceCubesApp#134]
Typing in a malformed Mastodon account link (say, `@icecubesapp@mastodon.social` vs. `mastodon.cloud`), posting said toot, and then attempting to click the resulting link to view the account profile results in a crash. (In my case, the profile lookup that presents itself when you're typing in names didn't give me the result I was looking for, so I typed it in wrong and found the error.) 

**Steps to reproduce:**

1. Post a toot with a malformed at-account-at-instance account reference. 
2. View the resulting toot (either in the general timeline or by drilling down into the individual item). 
3. The account reference will appear as a link. Tap it to attempt to view. 

**Expected result:**

In this case, either the text should not be linked, or an error message modal should be displayed stating that the profile is not valid.

**Actual result:**

The app crashes and the user is dropped back at the springboard. 

**Other remarks:**

- This was mostly found due to the profile lookup acting oddly. That's a separate issue, but not sure where the issue is. (The regular Mastodon client also delivered bad results in my case.)
- In Expected Result, it should be noted that the first option is what the offical Mastodon client does. This is not an endorsement, simply pointing out prior art. 
- The original toot where this was noticed is here: https://kachel.social/@james/109718237011312791 though I've since edited it to fix the account - you should be able to see what the original problematic one was, though.

**Comment by kc9jud** [comment]
Related: #102

**Comment by henrik** [comment]
Another example: clicking the linked email/account in this toot crashes the app: https://social.lol/@jack/109725071270957316
