### ISSUE TITLE
Bug: Unable Yo Sign Out Of App Without Deleting Account

### ISSUE THREAD

**Issue by DBowman2001** [Dimillian/IceCubesApp#1340]
## Environment:

 - OS: iOS 16.4 iPhone 13 mini

 - IceCubesApp version: 1.6.12

## Description
I am unable to figure out how to log out of my account within the app without deleting my account from the app. That makes it necessary to go through the account authorization process every time I use the app. I don’t have time for typing in my instance name and authorizing access to my mastodon account every time I use the app. I donated to your efforts today, and it’s otherwise a great app, but I can’t use it, given the hassle with signing out and back in using the app.  If there’s a way to keep my account info in the app and still sign out of mastodon, I have not been able to find it. 

Also, on a less important issue… the app severely darkens my profile header photo on my iPhone 13 mini. Not a big deal, but it’s weird that it only happens with Ice Cubes. Using the web interface it looks normal.

**Comment by blueturtleai** [comment]
You can sign out in the settings dialog via “log out account” below the list of accounts.

**Comment by DBowman2001** [comment]
I did that - but that deleted my account from the app. I am asking if there is a way to sign out without deleting my account from the app. I should not have to go through the account authorization process every time I use the app. And I can’t stay signed in on the app all the time - that’s an account security risk. That’s why I enabled 2FA.

**Comment by Dimillian** [comment]
No you can't. That's now how Mastodon work. A new app is created on the Mastodon side everytime you login and that the only way to do it because of the decentralised aspect of it. So indeed, login out in Ice Cubes wipe out your token. And there is no way to retrieve it. If your token would stay alive, that would create a security risk actually.

**Comment by DBowman2001** [comment]
Dimillian: thank you for your response. It looks like I will need to stay with the web interface when logging in to mastodon by phone. No apps for me.
