### ISSUE TITLE
Bug: Refresh issue on jump to latest

### ISSUE THREAD

**Issue by RobATX** [Dimillian/IceCubesApp#1344]
## Environment:

 - OS: 16.4
 
 - IceCubesApp version: 
 

## Description

Refresh issue. Is there any way to fix this issue after Jump to Latest where there’s a delayed refresh of several posts after the jump? 

https://user-images.githubusercontent.com/31712535/229140104-015f7271-219d-4b87-afff-805906f5c119.MOV

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
It's not delayed, posts are streamed in live. That a core function of the app.

**Comment by RobATX** [comment]
The other apps I'm testing like Mona seem smoother because they wait until they've pulled from the stream to display. It's disconcerting when the stream moves from under you while you're reading.
