### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by SittenSpynne** [Dimillian/IceCubesApp#1359]
## Environment:

 - OS: 
iOS 16.1.2
 - IceCubesApp version: 
1.6.13

## Description

I consistently crash if I follow this process:

1. Open the app.
2. Tap the notifications tab.
3. Tap an account icon in the notifications.

The account page partially loads but always crashes. I have tried this with multiple accounts from multiple instances, so it does not seem like an instance-specific or account-specific bug.

## Related Issues

(I didn't see any but my search-fu is known to fail.)

**Comment by sothawo** [comment]
Works for me with Icecubes 1.6.13 on current iOS 16.4

**Comment by Jerry23011** [comment]
Works for me too.
@SittenSpynne What type of notification are you referring to for this issue?

**Comment by SittenSpynne** [comment]
It doesn't seem limited to specific types of notifications. On some of my accounts if I tap any profile from the Notifications tab the crash happens. On other accounts, it only happens maybe 1/8 times.

**Comment by oobleck** [comment]
I’m experiencing this going to any user profile page from anywhere in the app.

- iOS 16.1.1 (20B101)
- Ice Cubes 1.6.13

**Comment by Dimillian** [comment]
Please update your iOS version. This is a known issue with iOS 16.1
