### ISSUE TITLE
Problems with sensitive media

### ISSUE THREAD

**Issue by xurble** [Dimillian/IceCubesApp#136]
There are a couple of little problems with sensitive media.

1. Images that aren't sufficiently tall can truncate the text above them
2. Only images get the little eye button to re-hide media, videos do not.

**Comment by xurble** [comment]
For example.  [This toot](https://mastodon.social/@vruz/109715531661589600) is truncated.

![Simulator Screen Shot - iPhone 14 - 2023-01-19 at 19 04 36](https://user-images.githubusercontent.com/246116/213602598-f9b07887-7607-480f-84e0-73c6bcd8658d.png)

**Comment by Dimillian** [comment]
Thanks for solving it!
