### ISSUE TITLE
Bug: Timeline is stuck in a loop when top post is filtered as completely hidden. 

### ISSUE THREAD

**Issue by Truhe2342** [Dimillian/IceCubesApp#1376]
I think it started 4 weeks ago, when I began noticing, that the timeline is often stuck in a loop and I have to kill and restart IceCubes. When arriving at the top of the timeline, IceCubes shows a steadily increasing counter of new posts. When I slowly scroll up, it shows posts which already where at the top of the timeline (so they were added redundantly). When I stop scrolling the timeline snaps back to the first (older) appearance of these posts and the counter again starts increasing. It's stuck in that loop.

OS:
iOS 16.4.1

IceCubesApp version:
1.6.14

Instance: chaos.social running Mastodon v4.1.2

**Comment by sothawo** [comment]
seems to be the same behaviour as I described. I have the impression, that when IceCubes is reloading and then the timeline is scrolled up, an additional reloading is triggered. It is ossible to not touch it and wait until the counter settles and then scroll up to the top.

**Comment by Dimillian** [comment]
I believe I've fixed it on main. I'll ship it soon.

**Comment by sothawo** [comment]
I should go back to use the fresh built from main installation on my phone - getting lazy with that when not working on it

**Comment by ppuschmann** [comment]
I often only see the content of the latest reload of items are displayed four or five times in a row.

Example: Ice Cubes fetches new 20 posts.

this is displayed as:
- Post 1-20
- Post 1-20
- Post 1-20
- Post 1-20
- Post 1-20

Only the "newest" (most top) items reduce the correct "new post" count of 20.

I'm looking forward to the fix.

**Comment by EwanCroft** [comment]
I also have this.

**iOS 16.4.1 (a) on iPhone 8 Plus**
**Ice Cubes v. 1.6.15**

https://github.com/Dimillian/IceCubesApp/assets/121812160/29838958-414b-4ef6-9f4d-5e8577d50a2e

**Comment by Subnet-Masked** [comment]
I am seeing this as well, unable to scroll while the app is counting new posts.

I am on iOS 16.5.1 with IceCubes 1.6.16 on an iPhone 13 Pro.

Only solution I have found is to completely close the app and way about 15 minutes before trying again.

**Comment by beanymax** [comment]
> I believe I've fixed it on main. I'll ship it soon.
I believe this is still happening - 1.6.17

**Comment by rezhajulio** [comment]
It happened to me several times today.

IceCubes version 1.7.1.

**Comment by LucaJunge** [comment]
Yes, it still happens.

**Comment by LucaJunge** [comment]
I'm at the point now where this error is so annoying that it makes the app unusable for me currently. 

What mblase75 said is probably related to what happens with filters and counters

**Comment by jue89** [comment]
> This loop seems to happen whenever the latest toot in my timeline is being hidden because of a keyword filter. Once a new toot is available to display, the looping stops.
> 
> I confirmed this by posting a Wordle toot, which is a filtered keyword for me, and the loop was triggered. Then I posted a second toot without any filtered keywords, and the loop immediately stopped.
> 
> Perhaps it can’t display it, but then it checks and sees there is one more post, so it adds it to the counter, and then just keeps adding one every second. In this case, the fix might be to filter out hidden toots before incrementing the counter.

The loop still appears. And the looping toots aren't hidden by a filter, afaict.

**Comment by amelandri** [comment]
I have the same exact problem. iPhone 11, iOS 17.2.1, IceCube 1.10.5

**Comment by Dimillian** [comment]
Fixed on main update will be out soon.

**Comment by amelandri** [comment]
Sadly it’s happening again. Version 1.10.11

**Comment by Dimillian** [comment]
I'll try that again then
