### ISSUE TITLE
Bug: Allow moving the app to different directory

### ISSUE THREAD

**Issue by dwt** [Dimillian/IceCubesApp#1377]
## Environment:

 - OS: MacOs 13.3.1 (22E261)
 - IceCubesApp version: 1.6.14

## Description

When I move the application to a different directory (I like having my applications under ~/Applications/$Category/ to make it easier for me to find them again if I don't remember the name for some reason.

However, doing that makes the update (through the App Store) fail. Even though this has worked for me in the past for apps installed via the App Store.

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.
 
I couldn't find any…

**Comment by Dimillian** [comment]
Yeah I don't think I can fix that Apple bug.

**Comment by dwt** [comment]
Do you have any idea what causes this? Other Applications that I have moved around like this do not have any issues on update.

If I can provide any info on how this happens, I would love to do that.

**Comment by Dimillian** [comment]
I don't really. This is an iOS app on macOS, so maybe that the issue. But whatever it is, this is not something I can fix from the app.
