### ISSUE TITLE
How to connect using a custom HTTPS port?

### ISSUE THREAD

**Issue by xingyue52077** [Dimillian/IceCubesApp#1383]
If Mastodon is set up on a port other than 443 because that port is not available, can it still be accessed through our app?

**Comment by Shanesan** [comment]
Pretty sure this works correctly if your nginx instance is configured properly:

https://serverfault.com/questions/536576/nginx-how-do-i-forward-an-http-request-to-another-port

**Comment by xingyue52077** [comment]
For example, my address is domain: 8888, I enter domain: 8888 in the url, can not be used, such a problem can be fixed?

I tested the source code and it was automatically deleted after entering the url: 8888, but I couldn't find out how this was implemented. Can you tell me how to specify the source code location? Thank you very much.
