### ISSUE TITLE
Feature request: Smaller/Disabled Link previews

### ISSUE THREAD

**Issue by Murgeye** [Dimillian/IceCubesApp#1386]
Currently link previews take up a lot of space and can only be made somewhat more compact by making all media smaller. I would love to have an option to either disable them completely or make them a smaller--more icon-like--as in MetaText (see attached screenshot).

Thanks for making this app!

![image](https://user-images.githubusercontent.com/16648242/233294507-f1e0637b-28b9-4d99-9848-45806e7dfe7a.jpeg)

**Comment by Dimillian** [comment]
If you set the media preview as none / small it'll be removed / reduced in the display settings.

**Comment by Murgeye** [comment]
I assume you mean the 'Status Media Style' setting? Setting that to 'compact' indeed hides the link preview.

However, I would much rather have the option to configure both settings independently. I like large media previews (and compact and medium seem to crop images weirdly) but don't need the link preview images.

By the way, the example toot in the display settings would benefit from a media preview. Otherwise you have to leave the screen to see how the options work.
