### ISSUE TITLE
Bug: Views not loading, cannot reset app

### ISSUE THREAD

**Issue by abhibeckert** [Dimillian/IceCubesApp#1387]
## Environment:

 - OS: 16.3.1
 
 - IceCubesApp version: 1.6.15
 

## Description

I'm complete unable to use the app - all the views just show place holders.

![15D7956C-6153-495D-9D31-20B872CDC5F9](https://user-images.githubusercontent.com/266088/233488726-4c7fcaad-8fd9-48ce-bc15-cc90d17069b8.png)

I've tried deleting the app and re-installing but it's still in the same state.

**Comment by Dimillian** [comment]
Can you try to logout / login?

**Comment by abhibeckert** [comment]
@Dimillian I can't log out, there is no logout button!

Re-installing didn't log out either.

**Comment by Dimillian** [comment]
In the home screen, tap on the avatar button and then settings in the sheet. From there you can swipe to logout your account.

**Comment by abhibeckert** [comment]
![1C128A77-064E-4CB6-95B1-CED7B37E80F5](https://user-images.githubusercontent.com/266088/233927186-498c7467-cdb2-48a9-a495-20744040de2e.png)
what do I swipe on in that screenshot?

**Comment by Dimillian** [comment]
In the timeline tab sorry, you can try to tap the top left rounded button, and there you should have a setting button.
