### ISSUE TITLE
Bug: notifications count is double the actual number of notifications

### ISSUE THREAD

**Issue by greyghoster** [Dimillian/IceCubesApp#1389]
## Environment:

 - OS: iOS 16.4.1
 - IceCubesApp version: 1.6.14

## Description

The notifications count has double the count of entries listed. 

## Related Issues

**Comment by blueturtleai** [comment]
This is a known issue. To fix it, the „duplicate notifications fixer“ was introduced. You find it at the bottom of the notification settings screen.
