### ISSUE TITLE
Feature request: Timeline position sync across devices

### ISSUE THREAD

**Issue by haugjp** [Dimillian/IceCubesApp#1398]
it would be very nice to have a feature, which allows the sync of the current position in the timeline across the devices with IceCubes installed and the same Account logged in. Imho this would push the usability of the app when using multiple devices significantly.

**Comment by Dimillian** [comment]
Duplicate and planned at some point.

**Comment by TS6ix2GaH3q679h5** [comment]
Just curious if anyone else still has this issue? 

I see in the release notes that Ice Cubes supports the Mastodon Marker API but the timeline position doesn't sync for me between iOS and macOS versions. My instance is on Mastodon 4 and I believe this API was added in Mastodon 3 so I'm not sure what exactly the issue could be. Each time I open the app I'm at the same location I was when I stopped using the app *on that device*.
