### ISSUE TITLE
Feature request:

### ISSUE THREAD

**Issue by ArnonClark** [Dimillian/IceCubesApp#1404]
It would be useful to have a "Follow this hashtag" option when you long-press on a hashtag. Sorry if I missed it. 

Search that this request don't already exist before creating it.

**Comment by ArnonClark** [comment]
Optimally, at least in my scenario, a way to add federated, followed hashtags into my various feeds, treating them them as an account, essentially, that one can curate on a granular level. If that's already there, I'm sorry I missed it, and I can't imagine it would be easy, but it would be nice. :)

**Comment by henrik** [comment]
If you click a hashtag, you get to a screen with a "Follow" button at the top right.

You can't currently long-press a hashtag to follow it, but I agree that would be nice.

**Comment by Dimillian** [comment]
Won't be possible with current SwiftUI. Tapping on it to follow from the detail screen is the way for now.
