### ISSUE TITLE
Feature request: Ability to toggle scroll direction.

### ISSUE THREAD

**Issue by MontblancKupo** [Dimillian/IceCubesApp#1405]
Being able to have new content loading from the bottom rather than the top would be awesome since you read top to bottom already in a post. I would like to be able to just keep scrolling down rather than scroll up, then down, then jump up, then scroll down, etc. Having scrolling direction be a toggle in settings seems like it wouldn't be too hard to implement and would allow people to choose the style they prefer.

**Comment by Dimillian** [comment]
#WonDo sorry
