### ISSUE TITLE
Bug: Blank menu items in profile pages

### ISSUE THREAD

**Issue by digitalqualms** [Dimillian/IceCubesApp#1409]
## Environment:

 - OS: 
macOS 13.3.1 (a) (22E772610a)
 - IceCubesApp version: 
1.6.15 (1891)

## Description

Clicking the "..." button on a profile page shows blank menu items

Screenshot:
![IceCubes-menu-bug-20230508](https://user-images.githubusercontent.com/50979043/236858084-1136ba2b-5b47-44f3-bcb4-a6b5213efc03.jpg)

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by digitalqualms** [comment]
Possibly related, when I view my own profile:

![IceCubes-menu-bug-20230508-2](https://user-images.githubusercontent.com/50979043/236858785-7b00d183-8d53-44e7-9ef6-0ea66d282d4a.jpg)

This context menu item does nothing.

**Comment by Dimillian** [comment]
macOS issue unfortunately. Let's hope Sonoma fix it.
