### ISSUE TITLE
Attempting to close the “more actions” menu by clicking outside of it

### ISSUE THREAD

**Issue by rvschuilenburg** [Dimillian/IceCubesApp#141]
Not sure if I’m using the correct name for the menu. I mean the three little dots on the top right of a message. When you open it, you see “favorite, boost, bookmark, etc” in a drop-down menu. 

My expectation is to be able to close this menu by clicking / pressing outside of it. 

It does indeed close it, but it also processes that click as it would be without this menu open (so if you clicked on the message, it will go to the message detail screen). 

I would expect it to only close that menu, and not process anything else related to my click. 

This is on iOS btw.

**Comment by michaelx** [comment]
I'd expect this too. Basically the only way to dismiss it currently without causing another interaction is to scroll away.

**Comment by alexveeee** [comment]
Same with the timeline drop down menu. I frequently click outside this menu to close it and click into a toot detail when I would expect nothing else to happen except closing the menu.

**Comment by pjolt** [comment]
This is the same as #334
