### ISSUE TITLE
Bug: Can't add alt-text when adding a picture during edit

### ISSUE THREAD

**Issue by TScheffler** [Dimillian/IceCubesApp#1411]
## Environment:

 - OS: iOS 16.4.1
 - IceCubesApp version:  IceCubesApp 1.6.15

## Description

I forgot a picture in a post and added it later in an edit. I was not able to add a description (alt text) to the photo - the context menu didn't show this option.

**Comment by Dimillian** [comment]
It depends of your instance, for that to work your instance / server have to run one of the latest version of Mastodon. It was not possible until recently. It have to be above 4.1
