### ISSUE TITLE
Bug: alt text dialog erases to switching apps

### ISSUE THREAD

**Issue by jonathankoren** [Dimillian/IceCubesApp#1419]
## Environment:

 - OS: iOS 1.16.4.1
 - IceCubesApp version: 1.6.15

## Description

When composing alt text, the eatery erases if switch out of ice cube and switch back.

This may be related to a bug where if you’re composing a post, switch apps, and come back, the text box is erased, or partially erased, but then refills if you try to edit the text.

### Steps to reproduce:
1. Compose post with image
2. Add alt text to the image, but leave the dialog open.
3. Swap out of ice cubes. Going  to the Home Screen should be sufficient, but swapping to another app to be sure.
4. Swap back to ice cubes. Note that the alt text dialog is now empty

**Comment by Gadgetoid** [comment]
Same issue here. I’ll switch to look something up or reference a larger version of the image and *poof* Not only gone, but vanishes before my eyes to really drive home the frustration.

**Comment by jonathankoren** [comment]
Still happens 1.8.5 / 17.0.3

See also
https://github.com/Dimillian/IceCubesApp/issues/1576

**Comment by jonathankoren** [comment]
@Dimillian
