### ISSUE TITLE
Bug: Hashtag suggestions force lowercase

### ISSUE THREAD

**Issue by samuelbjohnson** [Dimillian/IceCubesApp#1424]
## Environment:

 - OS:  iOS v16.5
 - IceCubesApp version: 1.6.15

## Description

When I type the hash symbol to begin a hashtag, the list of suggested hashtags, presumably pulled from the server, is converted to all lowercase characters, rather than leaving the CamelCase intact, as is the convention on mastodon.

**Comment by Dimillian** [comment]
Can't reproduce. if I search I autocomplete to an hashtag with camelCase and tap on it, it's inserted with the proper casing.
