### ISSUE TITLE
Bug: Custom Emoji flashing in and out

### ISSUE THREAD

**Issue by paw** [Dimillian/IceCubesApp#1434]
## Environment:

 - **OS:**  iOS 16.5
 - **IceCubesApp version:** 1.6.15

## Description

Sometimes when loading custom emoji inside toots/names it will get stuck in a loop flashing between the blank placeholder square and the custom emoji. I've encountered this rarely elsewhere, but the most frequent place and easiest to reproduce is when viewing your own profile. Using custom emoji in your display name makes the bug very apparent and easy to reproduce. It seems to happen sometimes when loading more toots beyond the first few, but does not always occur.

When this happens the performance tanks, the content window flashes as well, and while you can still technically interact with toots the content flashing makes it difficult. Ways to make it stop that I've found include opening Control Center and starting a screen recording, or scrolling back up to the top of your profile (where the bug will not be occurring), clicking edit info to bring up that modal (no need to save), and then when you scroll back down it will have stopped.

## Videos

Bug occurs:

https://github.com/Dimillian/IceCubesApp/assets/51191974/ad77c3ac-68bc-40f9-99cd-6042f4e15cfc

Stopping bug by editing info:

https://github.com/Dimillian/IceCubesApp/assets/51191974/29be8ed5-983e-494d-aa5e-6b207614a07a

## Related Issues

 - N/A

**Comment by Smalls1652** [comment]
I started seeing the same thing on other users' profile, but only with users that have custom emojis in their display name. I can get it to occur consistently when I:

* Switch to the all posts and replies tab on a user's profile.
* Going back to all posts and replies on a user's profile from a post I opened in that tab.

https://github.com/Dimillian/IceCubesApp/assets/1042907/2f08c53b-275a-416d-a969-36a99a39b5c8
