### ISSUE TITLE
Bug: Letters-left countdown does not match length validation alert

### ISSUE THREAD

**Issue by henrik** [Dimillian/IceCubesApp#1439]
## Environment:

 - OS: 
Ventura 13.3.1 (22E261)
 - IceCubesApp version: 
Version 1.6.15 (1891)

## Description

The countdown showed a few characters remaining but also an alert about the message being too long:

<img width="438" alt="Screenshot 2023-06-23 at 11 31 53" src="https://github.com/Dimillian/IceCubesApp/assets/216/d0d83df5-abf1-4b7d-8b84-ed0c691ab4ed">

Note the "1" in the lower right, suggesting I'm 1 character under the limit.

At a guess, IceCubes calculates toot length slightly differently than Mastodon, and the alert is from the Mastodon server?

This was my toot – I can reproduce by attempting to post this text again (on ruby.social):

```
The #VisionPro made me want to play with #SwiftUI. I’ve done a little bit of iOS and Mac dev over the years but not much lately, and no SwiftUI.

I figured a good smallish project could be a Mac client showing our commit-by-commit code review tool side by side with GitHub in splits – we currently achieve that via https://fluidapp.com.

#ChatGPT has helped a lot – I’ve gotten further than expected in maybe 30 minutes of work. Now trying to tear myself away before the pub stops serving breakfast…
````

Perhaps related to the links, hashtags, the Unicode ellipsis at the end?

Removing the initial "The" let me post it.

Now off to breakfast! 😁 

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by nathanwale** [comment]
I think this has to do with the difference between how the Mastodon server and Swift are counting the length of Unicode strings.

The length validation code on the Mastodon server seems to be counting the grapheme clusters (from https://github.com/mastodon/mastodon/blob/a985d587e13494b78ef2879e4d97f78a2df693db/app/validators/note_length_validator.rb#L5):
```ruby
  def too_long?(value)
    countable_text(value).mb_chars.grapheme_length > options[:maximum]
  end
```

I don't know anything about Ruby, though.

Your post is 499 characters if we use `String.count` in Swift, but 509 characters if we use `String.utf8.count`. I think that is the cause. Not sure what should be done about it though. 
![Screenshot 2023-06-24 at 11 44 28 pm](https://github.com/Dimillian/IceCubesApp/assets/48480798/255da67d-13b8-4532-919e-30aa09b0a43c)

IceCubes seems to count utf16 characters at https://github.com/Dimillian/IceCubesApp/blob/a740fe8ca896e7cfcbbf3dbb14a82eb8f9db8835/Packages/Status/Sources/Status/Editor/StatusEditorViewModel.swift#L73

```swift
var statusTextCharacterLength: Int {
    urlLengthAdjustments - statusText.string.utf16.count - spoilerTextCount
}
```

So it seems that IceCubes counts characters as utf16, while Mastodon maybe counts as utf8?

I'm not sure. Does anyone know if there's an official way to count the length of posts?

**Comment by henrik** [comment]
Good sleuthing. Hm, that's odd. The length per that Ruby code is 499 which should match the IceCubes UI. FWIW Ruby strings default to UTF-8.

```
$ irb
"> toot = "…"
>> require "active_support/all"  # To get mb_chars
>> toot.mb_chars.grapheme_length
=> 499
>> toot.bytesize
=> 509
>> toot.encoding
=> #<Encoding:UTF-8>
```

**Comment by henrik** [comment]
I think it's about the URL handling.

"Via https://fluidapp.com." shows as 472 chars left in Ivory and the ruby.social Mastodon web UI, but 475 chars left in IceCubes. If I remove one char and break the link, making it "Via ttps://fluidapp.com." this shows as 476 chars left in all three. So making it a link takes up an extra 3 chars in the other two apps.

**Comment by henrik** [comment]
It wasn't an issue with this toot, but I'm noticing in passing that the length calculation for `@` mentions also seems off in IceCubes.

The toot `@IceCubesApp@mastodon.online!` leaves 487 chars in Ivory and the ruby.social Mastodon web UI (counting the length of the username as it will be displayed: `@IceCubesApp`) but 471 in IceCubes.

**Comment by henrik** [comment]
Looking at the Mastodon source code, URLs should be considered 23 characters long for purposes of length validations.

[This code](https://github.com/mastodon/mastodon/blob/55e7c08a83547424024bac311d5459cb82cf6dae/app/validators/note_length_validator.rb#L18) replaces things that look like URLs with [a 23 char length string](https://github.com/mastodon/mastodon/blob/55e7c08a83547424024bac311d5459cb82cf6dae/app/validators/status_length_validator.rb#L6) before validating length.

And for mentions, [this code](https://github.com/mastodon/mastodon/blob/55e7c08a83547424024bac311d5459cb82cf6dae/app/validators/note_length_validator.rb#L19) replaces [mentions](https://github.com/mastodon/mastodon/blob/55e7c08a83547424024bac311d5459cb82cf6dae/app/models/account.rb#L65C1-L66) with just the local part before validating length.

**Comment by nathanwale** [comment]
IceCubes only accounts for URL length if a URL is greater than 23 characters. So it wasn't replacing your URL. 
See: https://github.com/Dimillian/IceCubesApp/blob/a740fe8ca896e7cfcbbf3dbb14a82eb8f9db8835/Packages/Status/Sources/Status/Editor/StatusEditorViewModel.swift#L345

Removing the if block there gets the same count as Mastodon's online client:
![Screenshot 2023-06-25 at 2 43 45 pm](https://github.com/Dimillian/IceCubesApp/assets/48480798/5819ba46-8c72-4bbe-b261-70631bc184ab)

I've fixed it in my fork and am going to make a pull request.

(Also, counting post length is really complicated and maybe should be extracted from the UI)
