### ISSUE TITLE
Feature request: toggle to exclude boosts from timeline

### ISSUE THREAD

**Issue by pacorob** [Dimillian/IceCubesApp#145]
It would be great if there was an option above the time to exclude the boosts and replies on the timeline.

**Comment by a-dows** [comment]
These should be two separate things (toggling boosts and toggling replies).

**Comment by pacorob** [comment]
I'm wondering why this was set as Done since I'm not seeing the option in general to exclude boosts from timeline only possible per account (as in latest update). Also I guess I need to reopen a new ticket for a feature request to have button to toggle on/off to exclude replies on timeline?

**Comment by Dimillian** [comment]
Not planning to do a general exclude at the moment. It could create more headache than not. Preferred solution was to work with the API level feature, which is per users.

**Comment by Dimillian** [comment]
Will re open, re add when I'll consider the feature, but it might be much later down the line, maybe when I'll implement custom filters (not server side) in the app.
