### ISSUE TITLE
Feature request: synchronize timeline on different devices

### ISSUE THREAD

**Issue by MatthiasGor** [Dimillian/IceCubesApp#1450]
Storage on the timeline of the position and synchronization between different devices.

**Comment by jcheroske** [comment]
It would be nice for unread notifications to be synchronized as well.

**Comment by Dimillian** [comment]
Planned / hard to do / long term / duplicate

**Comment by Hipska** [comment]
> Planned / hard to do / long term / duplicate

What do you mean with that? Is there a duplicate FR for this? If so, where is it?
