### ISSUE TITLE
Bug: Better Custom Emoji display on iPad

### ISSUE THREAD

**Issue by imdatsolak** [Dimillian/IceCubesApp#1457]
## Environment:
 - OS: iPadOS - any
 - IceCubesApp version: 1.6.16

## Description
The custom emoji picker completely covers the post so that one can't see that an emoji was picked. (s. attachment)
![image](https://github.com/Dimillian/IceCubesApp/assets/10852644/0b519415-67f5-47fc-a707-45795112e9e3)

Please make the emoji picker smaller so that the user can see that an emoji was selected.
## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
<img width="1136" alt="image" src="https://github.com/Dimillian/IceCubesApp/assets/535509/d1a73edc-5ce1-412d-929b-6e4b3ac76583">
