### ISSUE TITLE
Feature request: Support for formatted post display

### ISSUE THREAD

**Issue by imdatceleste** [Dimillian/IceCubesApp#1459]
Mastodon stores the toots in HTML if there is any format information (e.g. markdown from the `glitch-soc` fork). 

Currently IceCubesApp only displays these toots in plain-text format, all formatting from the server are discarded.

It would be awesome, if it would display the posts formatted with HTML.

AFAIK, when posting a toot, it is sent in plaintext and depending on the server-configuration, the server then converts it to HTML if it detects any formatting (and the user has set it so on their server-profile in e.g. `glitch-soc`).

Thank you for your consideration.

**Comment by ShadSterling** [comment]
Apparently there is some support for formatting; I'm seeing crossed out text in a port that doesn't have any formatting - https://mastodon.social/@glyph/110724377873612649

**Comment by imdatsolak** [comment]
> Apparently there is some support for formatting; I'm seeing crossed out text in a port that doesn't have any formatting - https://mastodon.social/@glyph/110724377873612649

This is a bug, IceCubesApp should **not** interpret markdown by itself. 

If the user has set that they are posting Markdown or HTML (it is a setting in `glitch-soc` at the very least), Mastodon automatically parses the incoming plain-text as being in that format and converts it to HTML before storing it.

So, if IceCubesApp retrieves a toot-text from Mastodon-server, it should not do any additional parsing/interpreting. It should just support the display of HTML in the post-view.

**Comment by ShadSterling** [comment]
How can I distinguish whether the crossed-out text is something Ice Cubes added by interpreting the plain text or something Ice Cubes displayed from the HTML?

**Comment by imdatsolak** [comment]
> How can I distinguish whether the crossed-out text is something Ice Cubes added by interpreting the plain text or something Ice Cubes displayed from the HTML?

If you see it in IceCubesApp, then it means it is how it should be shown, no further interpretation.

Interpretation and conversion from Markdown to HTML is only done **on the server**. If the server returns a ˜text˜ then the tilde-symbols are to be shown and not interpreted in the client (note: I am using the "special" ˜ to avoid GitHub interpreting it).

So, rule:
1. User types text with markdown. Client sends it to the server as PLAIN-TEXT format. Client does **not** interpret anything, does **not** convert anything. It sends it "raw" to the server.
2. Server checks what settings the user has and depending on the settings, it either converts Markdown to HTML **or** leaves it as is.
3. Client retrieves the result back from the server and displays what it gets from the server. If it is plain text, then client displays plain text. If it is HTML, client **should display formatted text**, but IceCubesApp doesn't do that atm.

**Comment by Dimillian** [comment]
ATM Ice Cubes strip HTML. There is indeed a new set of allowed tag for bold etc... planning to support it once it's a bit more mainstream.

**Comment by ShadSterling** [comment]
So, if Ice Cubes retrieves the post and either displays plain text as-is or strips tags from HTML, how does crossed-out text ever appear?  In particular, how does that happen in https://mastodon.social/@glyph/110720782356844143 ?
That post appears to be plain text in my (laptop) browser, but has crossed out text in Ice Cubes

**Comment by Dimillian** [comment]
It's a bug in Ice Cubes. Because of the UI framework the app is using, SwiftUI, the easiest way to render HTML text is to use the native Markdown renderer. So HTML is stripped, then it's converted to Markdown for final display. Some characters combinaison are interpreted as Markdown unfortunately and rendered as such.

**Comment by Dimillian** [comment]
This one sound nice :)

**Comment by ShadSterling** [comment]
Seen again in https://mastodon.social/@taylorlorenz/110742042969323601
