### ISSUE TITLE
Bug: Language detection always detects wrong language

### ISSUE THREAD

**Issue by gunnhildsk** [Dimillian/IceCubesApp#1461]
## Environment:

 - OS: iOS 16.5.1
 
 - IceCubesApp version: IceCubesApp v1.6.16
 

## Description

Every time I post something, the language detector detects the wrong language and prompts me to either Post in Selected language or in Detected language. I write in norsk nynorsk, but the detector thinks it is norsk bokmål (a very similar language). It is frustrating to always have to confirm what language I write in. I am missing either a far better language detection feature, or the opportunity to turn this feature off, either entirely or for specific languages. 

## Related Issues

 - [ X] Search that this bugs don't already exist before creating it.

**Comment by Havhingstor** [comment]
We use Apple‘s language detection, so that is the origin of the error. The best option is probably to allow deactivating the language detection (maybe only for selected languages)

**Comment by gunnhildsk** [comment]
This would be a good option, I think! I imagine this issue will be prevalent with a lot of smaller languages not properly supported by Apple.

**Comment by Dimillian** [comment]
I'll add an option to disable it :)

**Comment by Dimillian** [comment]
<img width="357" alt="image" src="https://github.com/Dimillian/IceCubesApp/assets/535509/7ef338aa-d1be-4818-8929-bd561a319c31">
 :)
