### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by popey** [Dimillian/IceCubesApp#1462]
## Environment:

 - OS: 
iOS 16.5.1
 - IceCubesApp version: 

1.6.16

## Description

Cannot add second account on the same instance as an existing account.

I have a few accounts on the same instance. I can add the first, but when I try and add the second, it asks for the instance name, then shows my existing account with the usually [Authorize] / [Deny] buttons. 

How can I add another account to Ice Cubes, which is on the same instance as my main account?

## Related Issues

 - [X] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
You can logout on the web sheet I guess. It's a Mastodon WEBUI issue imo.
