### ISSUE TITLE
Feature request: Mute and Block someone directly from the timeline

### ISSUE THREAD

**Issue by roydbt** [Dimillian/IceCubesApp#1464]
Like in the official mastodon app, you should be able to mute someone without having to go to their profile. I know right now the ... menu is already too crowded so why not remove the Favorite, Boost, Bookmark, and Reply button from there as currently there are 3 ways to do these actions.

**Comment by alexito4** [comment]
This was implemented in https://github.com/Dimillian/IceCubesApp/releases/tag/1.6.17 👍🏻
