### ISSUE TITLE
Bug: When viewing a remote timeline, you can't see how many favourites/boosts/replies there are

### ISSUE THREAD

**Issue by roydbt** [Dimillian/IceCubesApp#1465]
## Environment:

 - OS: iOS 16.5.1
 - IceCubesApp version: 1.6.16

## Description

When viewing a remote timeline, in the feed view there seems to not be any favourites/boosts/replies but when I click on a post suddenly there are replies to that post.

## Related Issues

 - [X] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Not fixable with the way the Fediverse works ATM
