### ISSUE TITLE
Feature request: Display custom emoji on profile Sheet

### ISSUE THREAD

**Issue by pylapp** [Dimillian/IceCubesApp#1474]
The custom instance emojis seems to be unmanaged yet in the profile account, could be nice to implement it.

(And thank you and good luck for this SwiftUI implementation, you are a bit insane 😂❤️)

Current profile hyperlink: https://framapiaf.org/@pylapp

![image](https://github.com/Dimillian/IceCubesApp/assets/7559007/da56e29c-5336-4105-9d41-e1f5a13cd00e)

**Comment by Dimillian** [comment]
Challenge accepted lol

**Comment by Dimillian** [comment]
Done 
![image](https://github.com/Dimillian/IceCubesApp/assets/535509/9f12bb3d-904c-4f0f-a3a9-eccb473e8a85)
