### ISSUE TITLE
Bug:  Cannot type using Chinese input method on iPad

### ISSUE THREAD

**Issue by hdcola** [Dimillian/IceCubesApp#1476]
## Environment:

 - OS: 
iPadOS 16.5.1
 - IceCubesApp version: 
1.6.16
- Input
System Chinese PingYin or WuBi

## Description

I can't reproduce it 100%. However, when typing Post, I often have the problem of not being able to type the last word in a line. The problem is that I can see the selection in the input prompt, but I can't enter it into the input box. You can only press a space or enter a phrase to get out of this state.

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.
 No

**Comment by Jerry23011** [comment]
Hi @hdcola,

我目前还不能在我的 iPad 上复现，你用的是简体中文输入法吗？如果可以的话，能麻烦你上传一个屏幕录制吗

I can't reproduce it so far, are you using the Simplified Chinese input method? If it's possible, could you upload a screen recording when the issue occurs?

**Comment by hdcola** [comment]
> Hi @hdcola,
> 
> 
> 
> 我目前还不能在我的 iPad 上复现，你用的是简体中文输入法吗？如果可以的话，能麻烦你上传一个屏幕录制吗
> 
> 
> 
> I can't reproduce it so far, are you using the Simplified Chinese input method? If it's possible, could you upload a screen recording when the issue occurs?

我已经在我的iPad上复现了，软件版本是从app store最新的版本，输入法是五笔，使用的是键盘。屏幕录制完成，等我到电脑上再上转。

I have reproduced in my iPad. The version is new from app store. Input method is Wubi and I use smart keyboard. I recored the movie, but now I use iPad that can't upload. When I use my computer, I will upload.

Thank you reply my report. :)

**Comment by hdcola** [comment]
这段时间放假，而我一直只有iPad，所以一直没有上传视频。直到昨天，我终于仔细总结了这个bug的触发方法。当输入到一行的最后时，如果你使用五笔输入的是可以直接出字的内容时就会触发这个bug。你可以试试 q 也就是我，它就会出q而不会出 我 这个中文。但是如果输入的是一个会有多个候选的内容时，就可以出现提示。

这是当前的版本(1.7.4 iPad OS 16.6)的情况。



> Hi @hdcola,
> 
> 
> 
> 我目前还不能在我的 iPad 上复现，你用的是简体中文输入法吗？如果可以的话，能麻烦你上传一个屏幕录制吗
> 
> 
> 
> I can't reproduce it so far, are you using the Simplified Chinese input method? If it's possible, could you upload a screen recording when the issue occurs?
