### ISSUE TITLE
Bug: Bluesky bridge fails

### ISSUE THREAD

**Issue by GreenFootballs** [Dimillian/IceCubesApp#1479]
## Environment:

 - OS: 
iOS 16.5.1
 - IceCubesApp version: 
 1.6.17

## Description

Tried the new Bluesky feature. Successfully added my account to `skybridge.fly.dev`, but nothing else works; I just get "An error occurred while loading posts, please try again."

I set my Bluesky handle to a custom domain - could that be a problem?

**Comment by Dimillian** [comment]
I'll close anything BlueSky related for now as this is highly experimental and dependant of the API. I didn't started to look into it appart from unblocking the auth.

**Comment by epetousis** [comment]
It appears that the showstopping bug (blocking both sign in and feed retrieval) was the lack of header URL being returned from the SkyBridge server for BlueSky accounts without banners, as Ice Cubes requires every account to have a valid non-null URL returned in the `header` field for the type decoding to succeed. I've submitted a pull request at videah/SkyBridge#43.
