### ISSUE TITLE
Feature request: Content filter

### ISSUE THREAD

**Issue by pacorob** [Dimillian/IceCubesApp#148]
It would be great if a content filter would become available.

**Comment by Dimillian** [comment]
duplicate of this #25

**Comment by pacorob** [comment]
> duplicate of this #25

I'm wondering when looking at the other feature request #25 if this has actually been added to the app since I can't find such option nor was it listed in a recent app update. I'm talking about an actual custom content filter as is available in e.g. competitor apps like Mercury and Tusker as is also shown here: https://www.hardreset.info/devices/apps/apps-mastodon/add-new-filter/  
I therefore think this should be reopened.

**Comment by Dimillian** [comment]
Right, it's indeed planned. I plan to rework the settings screen to have server side filter editable there per account.

**Comment by Dimillian** [comment]
But it'll still duplicate of #115
