### ISSUE TITLE
Feature request: Swiping motion required for refreshing could be smaller.

### ISSUE THREAD

**Issue by DarrenTitor** [Dimillian/IceCubesApp#1480]
When swiping down to refresh the page, the swiping distance of the finger required is almost 2x / 2.5x as large as other popular apps. 
Maybe it's a tiny problem. But I think this tiny inconsistency of interaction really stands out.

**Comment by Dimillian** [comment]
Closing. This is a default iOS control I have no control over. Probably a SwiftUI issue.
