### ISSUE TITLE
Feature request: Calckey API support

### ISSUE THREAD

**Issue by ThatOneCalculator** [Dimillian/IceCubesApp#1485]
Given #1181 is resolved, it's great that Calckey can mostly be used for basic compatibility now, but it would be great to see native support for the Calckey API, enabling features such as more timelines, reactions, proper quotes, antennas, channels, etc.

**Comment by Dimillian** [comment]
Duplicate for now.

**Comment by ThatOneCalculator** [comment]
> There will only be one master issue to support Calckey

Shouldn't that be *this* issue? An issue outlining eventual support for the Calckey API?
