### ISSUE TITLE
Feature request: Release a Linux Debian .AppImage / tar.gz / .deb package

### ISSUE THREAD

**Issue by expertmanofficial** [Dimillian/IceCubesApp#1486]
I'm on Linux Mint 20.3, Cinnamon and I would LOVE to try IceCubesApp.

The problem is, I have an Android and a Linux Mint OS set. Not macOS or iPhone.

So, yeah, the title says it all. Would appreciate Appimage / tar.gz build.

**Comment by Dimillian** [comment]
^ 
Yep, it won't happen unless someone want to write a native Linux version of this app, that would definitely be awesome.
