### ISSUE TITLE
Bug: Unable to post a video

### ISSUE THREAD

**Issue by Giucy2575** [Dimillian/IceCubesApp#1488]
## Environment:

 - OS: 16.5.1
 
 - IceCubesApp version: 1.6.17
 

## Description

When I want to post a video, I have the error message "You can't send an unprocessed media". The video doesn't process at all when I use a VPN (I need one at all times for safety reasons)

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by henrik** [comment]
What video format? Are you able to attach an example video here that you can't upload?

What instance? (In case it's instance specific, though the error message doesn't sound like it.)

**Comment by Dimillian** [comment]
VPN issue. Need more precise info on video format.
