### ISSUE TITLE
[calckey] Polls aren't being fetched correctly

### ISSUE THREAD

**Issue by zotanmew** [Dimillian/IceCubesApp#1489]
Polls that have been voted in are glitchy because of an interaction between ice cubes and calckey:
- Ice Cubes requests `/api/v1/polls/:id/` (with trailing slash)
- Calckey responds 301 `/api/v1/polls/:id` (without trailing slash) due to koa-no-trailing-slash
- Ice Cubes doesn't send the Bearer token to the new URL after the redirect

The mastodon client API docs (https://docs.joinmastodon.org/methods/polls/) also don't show a trailing slash, so I think this shouldn't break anything.

I believe that this can be fixed by removing the trailing slash here:
https://github.com/Dimillian/IceCubesApp/blob/10caea9d1a9d42a30ace91e86826bcf7f60c7d11/Packages/Network/Sources/Network/Endpoint/Polls.swift#L10

**Comment by zotanmew** [comment]
I just tested this and the one character change does indeed fix the issue. Should I create a PR?

**Comment by Dimillian** [comment]
Good catch fixed!
