### ISSUE TITLE
Feature request: Comprise a List made of Hashtags. 

### ISSUE THREAD

**Issue by oxjox** [Dimillian/IceCubesApp#1493]
It would be beneficial, in my opinion, to bundle a number of hashtags into a list. Sort of like a playlist made of different artists or music genres. Example... 
List: Photography
Hashtags: #blackandwhite #filmphotography #leica #ilfordhp5 #mediumformat #35mm

What I'm not sure about is if it's up to the user or the developers to determine what's allowed in the list. 
 - Should a List include accounts as well as hashtags? 
 - Is a List only users? 
 - Is another name needed ( in the UI) for a group of hashtags? Hashlist? Smart List? Group? 

I'd lean towards the former (if possible) allowing the user to make a list of either hashtags or accounts or both. Let the user make a list called 'Photo Hashtags' and 'Photo Accounts' or just 'Photography' if it's both (for example).

**Comment by Dimillian** [comment]
Probably won't be able to to dit with current API.
