### ISSUE TITLE
Bug: No Custom Emoji Popup

### ISSUE THREAD

**Issue by eth0net** [Dimillian/IceCubesApp#1497]
## Environment:

 - OS: iOS 17.0 (21A5277h)
 
 - IceCubesApp version: 1.6.17
 

## Description

There is no custom emoji popup that I can find when using the app on my phone to compose. No button for it or popup when typing after `:` in the composer.

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.
 

No links I’m aware of.

**Comment by Dimillian** [comment]
The accessory view is missing in iOS 17 beta 3 #1, update to iOS 17 beta 3 #2.
