### ISSUE TITLE
Bug: Special Emoji Crashes App 

### ISSUE THREAD

**Issue by Shanesan** [Dimillian/IceCubesApp#1498]
## Environment:

 - OS: 
 iOS DEV BETA
 - IceCubesApp version: 
 1.6.17

## Description

https://misskey.io/notes/9gvcmq4jns

Searching for or viewing this toot in any way crashes the app.

**Comment by Shanesan** [comment]
Awesome!! Will wait for the update and test live when it comes to the App Store.

**Comment by henrik** [comment]
It’s in the App Store now 🚀 Works fine for me in the prod app on my real phone.

**Comment by Shanesan** [comment]
Interestingly this still crashes so it must be an iOS 17 bug. I'll close this for now and report in when we get an actual non-dev release.
