### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by BenChase** [Dimillian/IceCubesApp#1499]
## Environment:

 - OS: iOS 16.1.1
 
 - IceCubesApp version: 1.6.17
 

## Description
Open opening certain user profiles the app instantly crashes.
Example(s):
@flexghost@mastodon.social
@Are0h@ubiqueros.com
@rmi@cloudisland.nz

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by Havhingstor** [comment]
I can't reproduce it in iOS 17.0 or 16.4, I'm redownloading the 16.1 Simulator to try it there.

**Comment by Havhingstor** [comment]
I was able to reproduce it in 16.1, I'll look into it

**Comment by Havhingstor** [comment]
The problem is that the bug doesn't always occur if I open one of the profiles.
The fact that it only happens on 16.1 and the stacktrace suggests it's a SwiftUI bug. I'm trying to find our code that triggers the faulty SwiftUI nonetheless.

**Comment by Dimillian** [comment]
Don't spend time on this. It's a bug in iOS 16.1 SwiftUI that have been reported multiple times. Nothing to do about it but to tell the user to update their iOS version.

**Comment by BenChase** [comment]
Happy with the outcome.  Will upgrade iOS.
