### ISSUE TITLE
Scrolling up sometimes gets stuck

### ISSUE THREAD

**Issue by EvilOne** [Dimillian/IceCubesApp#15]
App Version 0.7.711
iOS 16.2
iPhone 14 pro Max

With the latest app I could not scroll up for some reason. I was able to get around it when I tapped or double tapped the timeline icon. 

https://user-images.githubusercontent.com/169561/210136714-326d95d9-fe64-40a4-bede-f6ddbb09526a.mp4

**Comment by Dimillian** [comment]
Should be fixed in latest version. If you can confirm.

**Comment by seanlifetime** [comment]
Confirmed, I cannot recreate this. Thanks for the quick turn around!

**Comment by EvilOne** [comment]
Confirmed, I can no longer recreate this. Thanks for the quick turn around.
