### ISSUE TITLE
Feature request: Have way to cancel dot menu on post

### ISSUE THREAD

**Issue by ryanmichaelsmith** [Dimillian/IceCubesApp#1500]
When scrolling through feed, I often accidentally press the dot menu on a post. There's no way to cancel out of that menu without tapping on a post and browsing to that post.

Suggestion: either disable browsing to another post when tapping while context menu is visible.

It's a minor annoyance but happens pretty often for me.

**Comment by mrkwnzl** [comment]
You can tap & hold for a second somewhere outside the menu and it will be closed on release. Not sure if that is an explicit feature or accidentally possible, but that’s how I do it.

**Comment by Dimillian** [comment]
Won't be able to properly fix that thanks to SwiftUI unfortunately :/
