### ISSUE TITLE
Feature request: Jump to Latest for Local and Federated Timelines

### ISSUE THREAD

**Issue by ProjectAzar** [Dimillian/IceCubesApp#1503]
Not a huge priority issue, but it would be helpful to have the “Jump to Latest” feature available on the Home timeline in the drop down menu on the timeline pane available in the Federated and Local timelines. 

At present, it appears the only methods for jumping to the top of the Local and Federated timelines is to either manually scroll or to click the notification in the upper right corner numerous times to climb the list.

If this feature is already implemented or already rejected, I’ll gladly close this report. 

Thanks!

**Comment by Dimillian** [comment]
<img width="330" alt="image" src="https://github.com/Dimillian/IceCubesApp/assets/535509/bb3f0237-af99-4372-931a-f3b0ba9be338">

it's already there, you can select the top menu and jump to latest from any timeline.

**Comment by ProjectAzar** [comment]
Maybe this is a bug then. I only see the Jump to Latest option on the Home
timeline, though I may be using the wrong word. On an iPad, it is the
square timeline on the top of the list on the left. The drop down menu
where I can select another timeline appears there. Every other timeline
does not have the dropdown menu to select Jump to Latest.

Please see attached screenshot.


Selecting the Local timeline on the left panel opens the Local timeline in
the center panel, but I do not have the option to “Jump to Latest” as the
drop down menu is not available.

This may simply be a bug with iPad compatibility or I could be doing
something wrong, so if I’m just missing it, feel free to close and ignore.

Thanks.

The alternative is to set the home timeline to another timeline and
