### ISSUE TITLE
Feature request: Translate a post on timeline

### ISSUE THREAD

**Issue by pacorob** [Dimillian/IceCubesApp#153]
Have the option to translate a post on your timeline.

**Comment by pacorob** [comment]
I've noticed it doesn't always show the 'translate' text below the post and button at ...
An example: 

![c528c8d9c0f231e6](https://user-images.githubusercontent.com/122526166/214245113-b1389daf-9527-4efc-bfd9-c233e89ba1cc.jpeg)

Not sure if this has to do with a wrong language setting of the users app/mastodon client?

**Comment by Dimillian** [comment]
It should be 100% like the web. If the web don't show the translate, the app should not and vice-versa. 
Basically sometimes the status have the wrong language set or no language at all, in this case I can't do anything more magic that I'm doing. 

But you can use the ... Translate which will be there more often than not.
