### ISSUE TITLE
Bug: no information about new notifications

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#1531]
## Environment:
 - OS: iOS 16.5
 - IceCubesApp version: 1.7.1

## Description
I added a new account to icecubes. I’m not notified about new notifications for this account. Neither by the red bubble in the accounts menu, nor by the red notification counter when I switch to the new account. When I open the notification tab, I can see the new notifications.

All notifications are enabled in the settings. Switching notifications off/on, restarting the app and deleting/re-adding the account didn’t help.

For my other three accounts notifications work without problems. It seems to be a specific problem of this new account.

**Comment by Dimillian** [comment]
Could be a server side problem. Some instance don't support the push proxy.

**Comment by blueturtleai** [comment]
Seems to work now as expected. No idea, what changed. Perhaps another restart of the app did it 😀.
