### ISSUE TITLE
Bug: inconsistency when tapping icons

### ISSUE THREAD

**Issue by umrath** [Dimillian/IceCubesApp#1540]
(This effect is present in all versions of IceCubes since the beginning.)

When tapping the Timeline-icon in the bottom-left corner, the display scrolls to the top of the posts that have been loaded.
When in the Notifications-view a tap on the notifications-button does not scroll up to the top.
The same is true for the messages-section.

The expected behaviour would be a consistency between all views.

**Comment by Dimillian** [comment]
Fixed
