### ISSUE TITLE
Bug: Umlaut in URL not recognized as valid link

### ISSUE THREAD

**Issue by AliveDevil** [Dimillian/IceCubesApp#1546]
## Environment:

 - OS: iOS 16.6
 - IceCubesApp version: 1.7.3

## Description

Receive a post containing an umlaut in its path, this URL won’t be recognized as a link.

```
https://en.wikipedia.org/wiki/Elbbrücken_station
```

With URL encoded characters the URL works:
![image](https://github.com/Dimillian/IceCubesApp/assets/734738/b7da4329-d346-4479-bc5e-5733789a0f31)

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by grant-mcs** [comment]
This should now be fixed in the main branch.
