### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by TahomaSoft** [Dimillian/IceCubesApp#1555]
hi;

how can I delete a mastodon server from my account list if that server no longer exists? I can’t delete it or log out from inside the app.

thanks!

## Environment:

 - OS: 
 
 - IceCubesApp version: 
 

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
In settings yo can swipe to delete the account.
