### ISSUE TITLE
Feature request: thread posts

### ISSUE THREAD

**Issue by pacorob** [Dimillian/IceCubesApp#156]
Have the option to make a thread post so in other words create multiple posts in one go.

**Comment by diasthiago** [comment]
Please do this! 🙏🙏🙏

**Comment by slugmuffin** [comment]
Maybe related, maybe should be split out: have a way to collapse thread posts in Home view. 

Example long thread:

![image](https://user-images.githubusercontent.com/26312415/221006693-acf8b640-988b-43ad-b255-38afb4178101.jpeg)

**Comment by echidistanti** [comment]
I am writing to request a feature that would automatically split long posts into threads, making it easier for users to read and engage with the content. Specifically, I would like to suggest that the app automatically split any post over a certain length into multiple threads, with each thread numbered or marked with an emoji such as 🧵 to indicate that it is part of a larger conversation.

I believe that this feature would be particularly useful for users who frequently write long-form content, such as bloggers, journalists, or thought leaders, as it would help them to break their ideas down into more manageable chunks and make their posts more engaging and accessible to readers. Additionally, the ability to unlist subsequent threads would allow users to maintain the integrity of their original post while still providing readers with a more digestible format.

I hope that you will consider implementing this feature in a future update of the app.
