### ISSUE TITLE
Feature request: Block user confirmation dialog

### ISSUE THREAD

**Issue by mdesmedt** [Dimillian/IceCubesApp#1568]
I just accidentally blocked a user after mis-touching "Block" instead of "Message".

Please add a "Are you sure you want to block [user]?" confirmation before blocking a user account.

**Comment by eric-Is-Me** [comment]
I tried my hand at implementing this confirmation dialog locally and it seems to work for the happy path use case. I'd like to open up a PR for this but I don't believe I have permission to create branches on this repository yet. (first time open source contributor here)
@Dimillian is there a process for me to get contributor access so I can push up a branch?

**Comment by eric-Is-Me** [comment]
Created PR: https://github.com/Dimillian/IceCubesApp/pull/1597

**Comment by eric-Is-Me** [comment]
PR that implements this feature request has been merged to mainline.
https://github.com/Dimillian/IceCubesApp/commit/4bbfdcd256ca4271b7dd5a53bf0b582e8131b017

@mdesmedt lets close this issue out?

**Comment by mdesmedt** [comment]
Cool. Thanks!
