### ISSUE TITLE
Bug: iOS 17 only?

### ISSUE THREAD

**Issue by AxelTerizaki** [Dimillian/IceCubesApp#1575]
## Environment:

 - OS: iOS 16
 
 - IceCubesApp version: 
 

## Description

I'm a little surprised to read that Ice Cubes dropped support for iOS 16 and lower *one day* after the release of iOS 17 where most people haven't upgraded yet from 16 and some just won't right now or can't because their devices are a little too old for iOS 17 (like my current iPad and iPhone, which are locked to iOS 16)

Was there really a need to make it compatible only with iOS 17 ?

**Comment by Dean151** [comment]
Thanks to this framework (iOS 17+ only), IceCubes is faster than ever.
https://developer.apple.com/documentation/observation

I thinks it's why @Dimillian made this turn. And also because he's in charge 😛

**Comment by Dimillian** [comment]
Indeed. And on top of that you can keep using it on iOS 16, the latest available update is fine and won't break anytime soon.
