### ISSUE TITLE
Bug: ALT-text loss

### ISSUE THREAD

**Issue by libelle** [Dimillian/IceCubesApp#1576]
## Environment:

 - OS: 
iOS 17.0
 - IceCubesApp version: 
1.7.8

## Description

While adding ALT text for images, the screen resets and ALT text is lost. 

It's not consistent. I've tried counting the number of characters entered, or timing how long I'm in the text area, but neither seem to be (directly) related.

There was previously a bug where if you switched away from the the ALT text input (say, switched to another app, then back) the text would be lost.
## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by predecker** [comment]
I had that effect only when trying to use the "share" dialog in the Foto-App. Klicked the foto, choose Icecubes, typed the toot, typed the Alt-text and suddenly I was back in the Foto-App and all texts were gone. Same result when I typed the Alt-text first, the reset always happened while typing the Alt-text.

Starting the toot in Icecubes worked normally. Typed the toot text, inserted the picture, typed the Alt-text.
