### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by markrprior** [Dimillian/IceCubesApp#1581]
## Environment:

 - OS: 
 16.6.1
 - IceCubesApp version: 
 1.7.6

## Description

Probably not your problem but rather Apple's but in case there is some overlap I thought I would report it anyway. 

I have app update on manual and noted that Ice Cubes was now at 1.7.8 (increase in 2 point releases) so I went to update it and got this popup that iOS 17.0 was required but I could download an older version of the app. OK probably 1.7.7, but that does not work as when you tap on download you just get the popup again (and again, ...). Maybe there is no 1.7.7 and that is causing the problem or maybe it is something else. It's annoying but only mildly. Also I guess that will be the end of app updates for me until I'm comfortable updating iOS (and leaping at the latest .0 release isn't it).

![IMG_4675](https://github.com/Dimillian/IceCubesApp/assets/6236685/7fe37fb8-4ad9-41bf-9c32-51690caee2a1)

## Related Issues

 - [ x] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Yeah I guess this is up to Apple.
