### ISSUE TITLE
Bug: Avatar position setting not remembered when closing app

### ISSUE THREAD

**Issue by davevs** [Dimillian/IceCubesApp#1582]
## Environment:

 - OS: 
 iOS 17.0
 - IceCubesApp version: 
 1.8.1

## Description

Avatar position setting not remembered when closing app

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.
 
## test report (translated from NL language, so exact wordings might be off)
- open app
- go to settings
- go to display settings
- go to avatar position
- choose 'leading' 
-> avatar is now shown left of messages
- close and restart app
-> avatar is now on top of message again

**Comment by Dimillian** [comment]
Fixed in latest version.

**Comment by davevs** [comment]
Fix confirmed in 1.8.3
