### ISSUE TITLE
Bug: @count_posts@ is displayed under polls 

### ISSUE THREAD

**Issue by dertuxmalwieder** [Dimillian/IceCubesApp#1584]
## Environment:

 - OS: iOS 17
 - IceCubesApp version: 1.8.2
 
## Description

It seems that the poll participants counter uses the wrong variables.

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

[Post:](https://norden.social/@Herr_Tuslowsky/111108161585329993)

![IMG_6248](https://github.com/Dimillian/IceCubesApp/assets/125629/61c31aae-2a73-4a57-9676-7b076c93961a)

**Comment by sh95014** [comment]
@dertuxmalwieder This appears to be from "design.tag.n-posts-from-n-participants %lld %lld" in the German localization.
