### ISSUE TITLE
Bug: Login with two factor app (in this case Authy) is nearly impossible.

### ISSUE THREAD

**Issue by jklippel** [Dimillian/IceCubesApp#1587]
## Environment:

 - OS: 
iOS 17.0.1

 - IceCubesApp version: 
 1.8.3

## Description

Login with two factor app (in this case Authy) is nearly impossible.

When adding a new account the login information (username and password) can be entered and then
the field for the 2nd factor code appears. After switching to the Authy app the IceCube app switches back to the "Add account dialog" and I have to start the login process to the instance again: entering my instance, username and password to ge to the 2nd factor dialog. 
As the 2nd factor code is only valid for 30 seconds, entering all credentials again in time is a little bit of a challenge.

### Expected behaviour:

The app is still at the same dialog in the browser mode (asking for the 2nd factor code) after switching to another app.

## Related Issues

 - [X] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Could you record a video of the bug? I can reproduce it. When I switch apps, Ice Cubes stays on the webview for me.

**Comment by jklippel** [comment]
No, you are right! I cannot reproduce it either. Must have been a glitch on that day. I could now logoff and logon repeatedly without error.

Sorry for the fuss and thanks for your feedback and for developing a great mastodon app!
