### ISSUE TITLE
Bug: Toggling the sidebar on iPad stucks in homepage view

### ISSUE THREAD

**Issue by Jerry23011** [Dimillian/IceCubesApp#1590]
## Environment:

 - OS: iPadOS 17.0.1
 
 - IceCubesApp version: v1.8.3
 

## Description

Toggling different button on the navigation bar on the left of the iPad doesn't switch to the right content. Tapping on homepage, trending, and local doesn't change the content. It stays within the homepage.

https://github.com/Dimillian/IceCubesApp/assets/89069957/e10cccb3-15e6-4316-8f20-ab518eb87a80

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Interesting. Is it directly after the launch? What timeline are you stuck on?

**Comment by Jerry23011** [comment]
> Fixed in upcoming version.

Thanks!
