### ISSUE TITLE
Question: Translation service

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#1591]
In the configuration I have selected, that not only DeepL is used for translation, as I don’t have an API key. Lately often LibreTranslate is used for translation. Imo the quality of the translation is inferior to DeepL.

Does icecubes use the DeepL/LibreTranslate API directly or is the Mastodon translation feature (probably via API) used?

**Comment by Dimillian** [comment]
The app only uses DeepL if you provide your own API key. If not, it falls back to the server implementation, which can be anything.

**Comment by blueturtleai** [comment]
Okay, thanks!
