### ISSUE TITLE
New posts indicator does not appear to be dismissable

### ISSUE THREAD

**Issue by unikitty37** [Dimillian/IceCubesApp#161]
When I am catching up on a timeline, and new posts come in, a New Posts indicator appears at the top.

![425ED312-81FA-4DDA-81CE-850417E66234](https://user-images.githubusercontent.com/139183/213668644-ac3910e7-fa42-407a-93a9-7d082bc3cdbb.jpeg)

There doesn't seem to be a way to get rid of this without tapping on it, which takes me to the new posts and loses my place. If I continue to scroll through the timeline it stays on screen, right in the line of vision as I scan the posts; it makes the harder to read.

Would it be possible to have a way of dismissing it? (TBH, I'd be happy to just be able to turn it off completely; I'll see the the new posts when I get to the top.)

**Comment by unikitty37** [comment]
Also, a minor nit: when there is only 1 new post, it still says "posts":

![BA8F024E-80EA-4029-BBE6-65892E282489](https://user-images.githubusercontent.com/139183/213670037-1f7e234f-cb42-4287-9226-6fa23343a51f.jpeg)

**Comment by sothawo** [comment]
not related exactly to this issue, but what's the difference between this kind of button with the number in it and the one with the list icon? Do they do something different?

**Comment by unikitty37** [comment]
The "new posts" button loads all the new posts at once, and the list icon loads them one at the time. Unfortunately, both of them scroll the timeline to the top rather than leaving it where it is, so you have to tap the list icon, read one post, then tap it again — or load them all at once and try and find where you were!

It would be much better if the new posts loaded automatically at the top, there was no notification, and the scroll position stayed where it was. Metatext definitely had the right idea here…

**Comment by sothawo** [comment]
thanks for the clarification. Yes, metatext had a great solution. Another thing about scrolling which tweetbot had, was that double tapping on the top of the screen briught you to the top of the list, immediately double tapping again to you back where you were. That's great when you erroneously tapped twice.

**Comment by Dimillian** [comment]
Thanks for holding in there, I plan to work on a solution soon

**Comment by sothawo** [comment]
no hurry, you're pushing out updates faster than I am checking the app store anyway
