### ISSUE TITLE
Bug: Layout is strange when the window size is small on iPad

### ISSUE THREAD

**Issue by Kyle-Ye** [Dimillian/IceCubesApp#1622]
## Environment:

iPadOS 17.0.3 + App version 1.8.5

## Description

When resizing the window to a compact view, the layout is still 3-column making it hard to use.

Instead we may consider using the tabBarView in this case.

### Actual behavior

![before](https://github.com/Dimillian/IceCubesApp/assets/43724855/9605c213-c20a-4f91-978a-53691633c69c)

### Expected behavior

![after](https://github.com/Dimillian/IceCubesApp/assets/43724855/58035b30-69c7-430c-958d-9302ddd7eaad)

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by Kyle-Ye** [comment]
A simple fix IMO is: 
```diff
+ @Environment(\.horizontalSizeClass) private var horizontalSizeClass

- if UIDevice.current.userInterfaceIdiom == .pad || UIDevice.current.userInterfaceIdiom == .mac {
+ if let horizontalSizeClass, horizontalSizeClass == .regular {
```

If you don't want `regular + iPhone` to `sidebarView`, we can also update the condition.

However this will not work. And we'll get nil for horizontalSizeClass.

The bug involves some implementation detail of SwiftUI's App and Scene.

> https://twitter.com/kyleswifter/status/1701999425923817702

To workaround, we need to get the horizontalSizeClass value within a `View` instance not an `App` instance.
(Refactoring appView getter into a struct conforming to `View` protocol)

**Comment by Dimillian** [comment]
Fixed on main soon to be released
