### ISSUE TITLE
Bug: Videos/GIFs does not play

### ISSUE THREAD

**Issue by vggonz** [Dimillian/IceCubesApp#1628]
## Environment:

 - OS: iOS v17.0.3
 
 - IceCubesApp version: v1.9.1
 

## Description

Neither GIFs or videos play anymore with the new media player. They appear by default in the timeline with a black preview and a crossed play symbol. Clicking on them opens the media player modal but the video/GIF does not play.

Photos are working just fine and everything works on the web version (photos, videos and GIFs)

![image](https://github.com/Dimillian/IceCubesApp/assets/4114693/17e9589c-fa5c-4a1d-8a3e-3f7758478d37)
![image](https://github.com/Dimillian/IceCubesApp/assets/4114693/a8a39de0-6d8b-4a57-b80a-906f1c32a7a8)

## Related Issues

 - [X] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
The new media player didn't change anything to the timeline video, so the video is faulty or never played before. I'll look into it.

**Comment by vggonz** [comment]
Well, after some tests and investigation, I've found it was a wrong configuration of the mastodon instance. It was serving static files through the app instead of the nginx and not aplying some headers correctly.

I still don't know how images were been served without issue and this only arised with gifs and videos. Anyway, the issue is not with the app and can be closed. Sorry for any inconvenience.
