### ISSUE TITLE
Bug: "show anyway" Button/Filter doesn't work

### ISSUE THREAD

**Issue by drohmd** [Dimillian/IceCubesApp#1639]
## Environment:
 - OS: 
 17.0.3
 - IceCubesApp version: 
 1.9.2

## Description

I set various filter for some reasons. If I try to read the toots anyway and press the appearing "show anyway" button it only opens the toot before or after the filtered toot. See also the attached video. 

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.
https://github.com/Dimillian/IceCubesApp/assets/120812779/b3e74bd9-be25-49fe-9dab-5e90d2888486

**Comment by DerOhm** [comment]
I noticed that the bug I described in my first post only appears in thread views. Single Toots in my timeline are not affected.

**Comment by drohmd** [comment]
Still a thing in 1.10.6

**Comment by Dimillian** [comment]
I'll look it soon
