### ISSUE TITLE
Bug: Missing translation for menu.new-window

### ISSUE THREAD

**Issue by DerMolly** [Dimillian/IceCubesApp#1642]
## Environment:

 - OS: macOS 14.0 (23A344)
 
 - IceCubesApp version: Version 1.9.3 (2076) (mac version)
 

## Description

The translation for the key menu.new-window seems to be missing (on the German translation at least).

![grafik](https://github.com/Dimillian/IceCubesApp/assets/3978662/0447c564-a3bc-4405-a151-39750202c120)

**Comment by Dimillian** [comment]
Fixed in main
