### ISSUE TITLE
Bug: Recent iOS builds break iOS’s AI-driven photo subject selection

### ISSUE THREAD

**Issue by jack4git** [Dimillian/IceCubesApp#1649]
## Environment:

 - OS: iPadOS 17.1 / iOS 17.1
 
 - IceCubesApp version: Latest 30 Oct
 

## Description

You made some kind of image handling change in the past month or so that broke iOS / iPad OS subject selection, where you open an image in preview mode and tap on the subject to select and have the ability to copy.

Used to work, stopped working in the past month. Just checked today’s update, still broken.

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by jack4git** [comment]
Update: I realized that if you open an image, then hit it “i” icon, it opens yet another image window. In the second window, the subject selection works.

But … not a great experience, not sure if intentional / why it works this way.

**Comment by Dimillian** [comment]
It is... everyone requested a faster image viewer, so I made my own. The subject selections, etc... are only a feature available with the system QuickLook, whish is slow to open for networked images, sadly. So, indeed, you can access it with the "i" button.

**Comment by jack4git** [comment]
Got it. I’ve never perceived normal image opens as slow … feels like sub-100ms here, using official mastodon client to open an image such as on this post https://mastodon.social/@TriflingTree/111325339018841027
