### ISSUE TITLE
Bug: Respect privacy settings: Show app posted from

### ISSUE THREAD

**Issue by idnovic** [Dimillian/IceCubesApp#1670]
## Environment:

 - OS: 
 iOS 17.1.1
 - IceCubesApp version: 
 IceCubesApp v1.9.6

## Description

A post I made had „posted from IcesCubesApp“ added to it. 
But in my mastodon instance I specifically deactivated this behavior under the privacy settings for my account.

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
I don't think there is anything I can do about this. Most probably it shows for your post when you look from your account.
