### ISSUE TITLE
Bug: Settings Menu on macOS not closable

### ISSUE THREAD

**Issue by thorstenstark** [Dimillian/IceCubesApp#1676]
## Environment:

 - OS: 
 macOS 14.1 
 - IceCubesApp version: 
Version 1.9.7 (2103) (Mac AppStore)

## Description

The Settings menu on macOS can't be closed anymore. There is no close button nor does clicking outside the Settings View/Window closes it.

<img width="603" alt="image" src="https://github.com/Dimillian/IceCubesApp/assets/7874611/311870dc-d2d6-4f09-9bee-77fd634f6e35">

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.
 
Couldn't find any other issue mentioning this bug.

**Comment by Jerry23011** [comment]
Try esc?

**Comment by Dimillian** [comment]
Fixed on main for next release.
