### ISSUE TITLE
Bug: Account default post visibility not applied

### ISSUE THREAD

**Issue by F11fth** [Dimillian/IceCubesApp#1677]
## Environment:

 - OS: iOS 17.1.1
 - IceCubesApp version: 1.9.7

## Description

On the specified version, when setting a default post visibility other than "Public" for an account, this is not reflected when creating a new post. 

Setting in the app (was seperately confirmed to be correct in the WebUI):
![IMG1](https://github.com/Dimillian/IceCubesApp/assets/26634127/90044f52-0e15-4d1a-be8b-aba27187e8a2)

Setting when creating a new post from the default timeline tab:
![IMG2](https://github.com/Dimillian/IceCubesApp/assets/26634127/a3a74708-2a3c-4c0f-8567-4b693e8384b8)

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.
 --> I was unable to find one

**Comment by Havhingstor** [comment]
You might have overwritten this setting for all accounts in the general settings->content settings->use server settings. If that is not activated, your standard post visibility is set here.
![image](https://github.com/Dimillian/IceCubesApp/assets/59767224/64624c3b-64af-434e-80c1-d25604bf984c)

**Comment by F11fth** [comment]
@Havhingstor Thanks, you were absolutely correct. I can't tell however if I changed something or if it's off by default. My suggestion, if it isn't, would be to have it on by default to avoid confusion. 
Thanks for the quick help though!

**Comment by Havhingstor** [comment]
I think it's on by default. I'll look into it, might also be possible to show a warning in the instance settings.
