### ISSUE TITLE
Bug: On macOS the menu items are not all displayed for a profile

### ISSUE THREAD

**Issue by pylapp** [Dimillian/IceCubesApp#1685]
## Environment:

 - OS: 
macOS Sonoma 14.1.1
 - IceCubesApp version: 
Version 1.9.9 (2118)

## Description

On macOS, in dark mode, I select some acount to get its profile.
I tap then on the three dots circled menu, to get more available actions.
There are several entries, some entries have a text inside, and others no, even if there are submenus inside.
FMPOV some texts are missing in the menu (see screenshot bellow).

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.
 
<img width="1406" alt="screenshot" src="https://github.com/Dimillian/IceCubesApp/assets/7559007/c48a0180-4e76-45e5-8461-c3c3458dfb32">

**Comment by jmb** [comment]
Just had this same issue - switching to light mode makes no difference and the bug is still there.

**Comment by proxfly** [comment]
Duplicated #1885

@Dimillian @pylapp This issue has been fixed by #1906, you may want to close this.
