### ISSUE TITLE
Feature request: add image caption in edit post

### ISSUE THREAD

**Issue by pacorob** [Dimillian/IceCubesApp#169]
I'm not sure if this is possible to support but it would be great if you forgot to add a caption to an image for the visual impaired / in general to add in the edit mode as well if you forgot to include it in the original post.

**Comment by Dimillian** [comment]
Closing this one as Mastodon actually doens't support it. Once a post is published you can media info anymore unfortunately.

**Comment by pacorob** [comment]
> Closing this one as Mastodon actually doens't support it. Once a post is published you can media info anymore unfortunately.

It might be soon supported looking at recent development here: https://github.com/mastodon/mastodon/pull/20878#event-8257028876
