### ISSUE TITLE
Slideover on iPad should be iPhone layout

### ISSUE THREAD

**Issue by Stooovie** [Dimillian/IceCubesApp#1698]
On iPad in Slideeover mode, the navbar is vertical and takes too much space. 

Solution: The app should adapt the iPhone layout (navbar on bottom) while in this mode. When sidebar is enabled, the layout breaks completely. 

![IMG_0678](https://github.com/Dimillian/IceCubesApp/assets/10572373/aa027ce6-5253-4f88-aa0f-ea392e8ce685)
![IMG_0679](https://github.com/Dimillian/IceCubesApp/assets/10572373/08bc4a3b-7d06-44a0-9c34-371f030812cf)

**Comment by Dimillian** [comment]
The plan is to have the app in tabbar mode when slideover. It'll be coming soon :)

**Comment by Dimillian** [comment]
Fixed on main
