### ISSUE TITLE
Bug: Using Observable MACRO leaks memory

### ISSUE THREAD

**Issue by Themakew** [Dimillian/IceCubesApp#1700]
## Environment:

 - OS: 
Lastest
 - IceCubesApp version: 
Lastest

## Description

I saw a thread in the Apple Forum regarding the MACRO Observable leaking memory until the latest Xcode 15.0.1: [LINK](https://developer.apple.com/forums/thread/736110?login=true&page=1#769898022) 

Testing here locally in fact it is happening yet, if you change to @StateObject+ObservableObject, the deinit is called.

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Ok but I'm not going back, so will just wait for an SDK update and recompile the app.

**Comment by MadeByShedrack** [comment]
Interesting. I hope this issue get fixed.

**Comment by Dimillian** [comment]
The only place where it could be problematic is the StatusRowViewModel. I'll if this one leak as there can be thousands of them. Other places we're talking about full screen tabs etc... not really a problem if it leaks.
