### ISSUE TITLE
Bug: Tapping the "add image" button while using a pixelfed account freezes IceCubes

### ISSUE THREAD

**Issue by Truhe2342** [Dimillian/IceCubesApp#1712]
## Environment:

 - OS: 17.1.2
 - IceCubesApp version: 1.9.12

## Description

After switching to a pixelfed account, when tapping the "add image" button in a new post, IceCubes freezes and has to be killed and restarted. I can reproduce this on iOS 17.1.2 and macOS 14.0.

**Comment by Dimillian** [comment]
Pixelfed seems to stray from Mastodon, and they now have their clients. I'm not sure that Ice Cubes should even be considered for use on Pixelfed.
