### ISSUE TITLE
Feature request: show number of replies a post has in the timeline

### ISSUE THREAD

**Issue by Apex-DE** [Dimillian/IceCubesApp#1713]
show the number of replies a post has in the timeline. Opening a post shows the thread, but it would be nice to see if a post has replies in the timeline directly.

**Comment by Dimillian** [comment]
<img width="87" alt="image" src="https://github.com/Dimillian/IceCubesApp/assets/535509/f2803fa4-b106-47b2-8ecd-3cf706883e82">

But it's already doing that, not for remote timeline tho, as it's not possible in this context unfortunately.
