### ISSUE TITLE
Bug:can’t copy substrings from toots

### ISSUE THREAD

**Issue by jonathankoren** [Dimillian/IceCubesApp#1716]
## Environment:
iOS 17
Ice cubes 1.9.11

## Description
It is impossible to select text from a toot, particularly after tapping to the single toot screen.  Tap and drag does nothing. Eventually it will trigger a long press, which brings up a menu of options, none of which are appropriate. The closest is “copy text”, but that copies the entire text, which can be over 1000 characters, when all you want to to do is select a single word for copying or lookup.

Pressing on the text should bring up the text select tool. Everything in the long press menu already has affordances through the onscreen icons.

**Comment by Dimillian** [comment]
Unfortunately, due to how SwiftUI Text works, this is not possible for now. I blame Apple for this one because there is no solution at the moment.
