### ISSUE TITLE
Alternate image text translation

### ISSUE THREAD

**Issue by franck-paul** [Dimillian/IceCubesApp#1718]
Is it possible to have the generated alternate text translated in my current language (set in French on my instance and on my device)?

I tried several images and the generated text is always in English; or may be should I activate the DeepL translation?

**Comment by Dimillian** [comment]
So I think that what I'll do is chain both services. Text generation will be in English with then an option to DeepL translate it to anything.

**Comment by franck-paul** [comment]
It will be nice!

**Comment by Dimillian** [comment]
It's done on main, will go in the next version

**Comment by franck-paul** [comment]
The workflow has been changed recently for alternate text translation as several translation services may be choosen (a good thing), but it is less choose'n'click than before. It is possible to provide an option, in the translation popup, to copy'n'paste the translation in place of the English description of the image?
