### ISSUE TITLE
Feature request: adjust font size in app (iOS Settings already possible)

### ISSUE THREAD

**Issue by pacorob** [Dimillian/IceCubesApp#172]
I think I've seen this mentioned on Mastodon by Thomas even with screenshot but couldn't find it listed here. 
It would be great to adjust the font size (and maybe even type) within the display settings of the app as well.

I'm aware it does already work via the system and Ice Cubes perfectly adjusts it. 
iOS Settings > Display & Brightness > Text Size
iOS Settings > Accessibility > Display and text size
iOS Settings > Accessibility > Per-App Settings, add Ice Cubes

**Comment by Dimillian** [comment]
I'm not planning to have that option on iOs as the app fully support dynamic type. But on macOS we have the slider in app.
