### ISSUE TITLE
Creating a List on IceCubes

### ISSUE THREAD

**Issue by Sanctum1969** [Dimillian/IceCubesApp#1720]
I'm looking for instructions on how to setup "Lists" on Mastodon for the IceCubes App. I recently saw this link on Mastodon:
https://fedi.tips/how-to-use-the-lists-feature-on-mastodon/

However, these instructions don't seem to work on the IceCubes App to set up a link as described. When I select the ... area on IceCubes (iOS) I see a "List" section, but I Can't seem to create a list. Could you please post instructions on how this works for IceCubes? Thanks!

**Comment by Dimillian** [comment]
If you don't have any list, open your profile tab and switch the lists section 

![image](https://github.com/Dimillian/IceCubesApp/assets/535509/61d3e616-ec95-4018-b8ba-2f13c2cc3193)

From there you can create a new list. 

Once done, you can access them from the timeline filter. 

![image](https://github.com/Dimillian/IceCubesApp/assets/535509/bb9440dc-4dc1-4860-99f2-0c60b2e34477)
