### ISSUE TITLE
Feature request: Better support for the Threadiverse (Lemmy/Kbin)

### ISSUE THREAD

**Issue by roydbt** [Dimillian/IceCubesApp#1726]
Threadiverse posts show a short summary and a link to the thread. The problem is that IceCubes thinks that the links are quote posts, and when pressing them I get sent back to the same short description and a link.
I am proposing that when there is a link to a post in that same post, IceCubes will let me open the link without treating it as an actual post.

**Comment by Dimillian** [comment]
Would be great but if it's a Mastodon app first. I can't support the thousands of forks out there.
