### ISSUE TITLE
Bug - Image not displaying in timeline, but does in post view.

### ISSUE THREAD

**Issue by ScottChampagne** [Dimillian/IceCubesApp#173]
This post references an image.  
![image](https://user-images.githubusercontent.com/13421207/213692014-b5bd65f5-08d7-4e49-ac73-a8b2e66aeb87.jpeg)
Nothing is displayed in timeline view.  

However, after clicking on the post, it displays in post view.  ![image](https://user-images.githubusercontent.com/13421207/213692189-5c52a384-11ae-455d-bbbd-2a9b7ec49973.png)

**Comment by Dimillian** [comment]
Probably just an edit.
