### ISSUE TITLE
Bug: edited posts not shown correctly in App

### ISSUE THREAD

**Issue by Apex-DE** [Dimillian/IceCubesApp#1734]
- OS: 
 iOS 17.1
 - IceCubesApp version: 
 IceCubesApp v1.9.14

## Description

after editing a post: it seems to be correctly saved on the server but the old unedited version is shown in the app which is confusing and not intended i believe?

**Comment by Apex-DE** [comment]
more info: edited post must contain smilies / content with smilies edited for the bug to show up

**Comment by Apex-DE** [comment]
example: i wanted to remove a smilie but it stayed within the post in the app but was correctly edited serverside

**Comment by bradheintz** [comment]
I don't need to have smilies/emoji in the post for the edited version to fail to show up in the iOS client. I've only observed the issue in replies, but have not tried it with a regular post.

**Comment by Apex-DE** [comment]
the bug seems to happen when you make a change within the post text. If you append text to the post, then the edited part is shown, but not the changes made within the post. Weird.

**Comment by Dimillian** [comment]
Editing a post relies on the server to send the corresponding stream event. But even there, I have some edge cases depending on the view you're in. I'll take a tour of the app and make sure the post is updated everywhere.

**Comment by Dimillian** [comment]
The app now send the event locally. Will be fixed in next version.
