### ISSUE TITLE
Feature request: Multi Toots (Posts)

### ISSUE THREAD

**Issue by detrophy** [Dimillian/IceCubesApp#1735]
Please add the possibility to post multiple posts directly as a thread to allow for users on standard character count instances to easily create threads. 

Maybe don't ask the user to create toots by, but create additional ones as needed.

Add either 🧵 or N/N as thread indicator at the end of each post.

![image](https://github.com/Dimillian/IceCubesApp/assets/23260830/44804f74-e220-4199-a9f3-c5e54114358e)

**Comment by Dimillian** [comment]
This is planned :)
