### ISSUE TITLE
Feature request: Improve rendering of App Store links

### ISSUE THREAD

**Issue by sh95014** [Dimillian/IceCubesApp#1746]
Example https://mstdn.social/@shaundon/111569283248192215 currently renders like a website preview, always slicing off parts of the app icon and using far more vertical space than necessary:

![IMG_0531](https://github.com/Dimillian/IceCubesApp/assets/95387068/0e8fb32b-23ef-4abb-8017-65d1ee7c2bdb)

Suggest specializing it to something like:

![IMG_0533](https://github.com/Dimillian/IceCubesApp/assets/95387068/3bae1e72-79c2-49eb-b129-1e80bfed5300)

Let me know if you're interested and I can look into a fix.

**Comment by Dimillian** [comment]
I don't know. I think I like all links card to be displayed the same way but I'm open to enhancements.
