### ISSUE TITLE
Feature request: Option to disable account popovers

### ISSUE THREAD

**Issue by sh95014** [Dimillian/IceCubesApp#1747]
https://github.com/Dimillian/IceCubesApp/pull/1687 is nice, but on a device with a pointing device (e.g., iPad with Magic Keyboard) it's easy for the pointer to hover over a name and trigger the popover while I've stopped scrolling to read something. The popover then blocks what I'm trying to read.

Suggest a user option to turn off the popovers.

Let me know if you're amenable and I can look into a fix.

**Comment by Dimillian** [comment]
Sure :)

**Comment by shuang886** [comment]
@Dimillian I see you enclosed the setting in a `#if targetEnvironment(macCatalyst)` check. This issue also (primarily, in my personal case) affects iPads with Magic Keyboards. Can we broaden that check to include iPads?

**Comment by sh95014** [comment]
@Dimillian I see you enclosed the setting in a #if targetEnvironment(macCatalyst) check. This issue also (primarily, in my personal case) affects iPads with Magic Keyboards. Can we broaden that check to include iPads?

**Comment by Dimillian** [comment]
Ah I didn't even knew that, yes I'll fix
