### ISSUE TITLE
BUG: visiting deleted user account crashes the app

### ISSUE THREAD

**Issue by dotemacs** [Dimillian/IceCubesApp#176]
Hello,

Thanks for IceCubes app 😄 

Bug report: I have a direct message from a user, that is a few months old. This user has since deleted his account on that instance.
But I only found this out by visiting his profile on the given instance in my browser. Because every time I tried to click on this user's username, IceCubes would just crash.

I'm not in a rush to have this fixed, but figured you should know about it.

Thank you

**Comment by kc9jud** [comment]
Related: #102 #134
