### ISSUE TITLE
Bug: Cannot upload attachment on MacOS

### ISSUE THREAD

**Issue by modean987** [Dimillian/IceCubesApp#1768]
## Environment:

 - OS: MacOS Sonoma 14.2.1
 
 - IceCubesApp version: 1.9.18
 

## Description

I can not upload images to Mastodon on an M1 MacBook Pro. I can select the the attachment icon, browse for the image on my Mac, select it, and click the open button, but nothing happens after that -- no communication takes place with the mastodon instance.

The MacBook is using the latest Mac OS, Sonoma 14.2.1. I do not have this problem on my iPad Pro.
## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Interesting. In the meantime you can copy paste directly in the composer.

**Comment by modean987** [comment]
I had no idea that was even possible! I will do that until the reason for the issue is discovered. I thought it might be a permissions issue, but the app seems to use the same permissions as my browsers, and they don't have the problem.

Thanks!

**Comment by Dimillian** [comment]
It was a permission issue. Next build will have it fixed
