### ISSUE TITLE
Feature Request: Ability to dismiss image with swipe

### ISSUE THREAD

**Issue by ender3** [Dimillian/IceCubesApp#177]
When looking at the detail view of an image, video or animation, the only way out of that screen is the cancel link in the upper right, which is quite a stretch for one-handed operation. The ability to dismiss this view with a swipe (either left to right, or [I admit it, this is Tweetbot muscle memory] down) would be fantastic.

**Comment by pacorob** [comment]
> When looking at the detail view of an image, video or animation, the only way out of that screen is the cancel link in the upper right, which is quite a stretch for one-handed operation. The ability to dismiss this view with a swipe (either left to right, or [I admit it, this is Tweetbot muscle memory] down) would be fantastic.

There is [already](https://github.com/Dimillian/IceCubesApp/issues/106) a feature request open from a couple of days ago.

**Comment by MariaFeodora** [comment]
When swiping away a video that is playing, the video does not get stopped, so you can still hear the audio. Also would love to be able to swipe media away from anywhere in the screen.
