### ISSUE TITLE
Bug: Icons too small in phone display / don't scale

### ISSUE THREAD

**Issue by umrath** [Dimillian/IceCubesApp#1789]
## Environment:

device: iPhone 12 (probably equally relevant to all similar devices)
os: any

## Description

When trying to "like" or "repost" anything, I have a chance of about ~30% to miss the button and do whatever happens when I hit the area next to the icon (usually opening the toot details or the like).
The hitbox/the icons are just too small to reliably hit them.

Also: They do not scale with the text.
My eye sight is getting worse and it's difficult to decypher the icons. I can scale up the text but not the icons. So, I need to memorize which icon is which.

## Related Issues

None found.

**Comment by Dimillian** [comment]
Good catch! I'll make the actions button scale!
