### ISSUE TITLE
Bug: `<unknown>` application passwords in Keychain Access

### ISSUE THREAD

**Issue by piercefaulkner** [Dimillian/IceCubesApp#1792]
## Environment:

 - OS: macOS Sonoma
 - IceCubesApp version: 1.10.1

## Description

The `notifications_private_key`, `notifications_auth_key`, and account ID application passwords have `<unknown>` as Name in the Keychain Access app.

<img width="539" alt="app" src="https://github.com/Dimillian/IceCubesApp/assets/86799892/25404c23-191f-4d79-83f8-af7a739ceb08">

**Comment by Dimillian** [comment]
🤷🏻

**Comment by piercefaulkner** [comment]
Can the keychain item names be updated? The `<unknown>` entries make reviewing your keychain take longer

**Comment by Dimillian** [comment]
Yes, but what about existing accounts? Do they need to be migrated?

**Comment by piercefaulkner** [comment]
I can try to build the app locally to test

**Comment by piercefaulkner** [comment]
I'm not using Ice Cubes anymore. If the developer compromises privacy they'll compromise security.

**Comment by Dimillian** [comment]
What I did? Where did I compromise privacy?
