### ISSUE TITLE
[iPhone] Feature request: Move "New Post" button to the bottom of the screen

### ISSUE THREAD

**Issue by bersfo** [Dimillian/IceCubesApp#1794]
On an iPhone it is really hard to reach the "new Post" button - It is at the very top of the screen. It would be much better to have it within reach of the thumb.

Two options:
#1 Integrate into taskbar (Mastodon or Mona style)
#2 Have it floating in the bottom right corner (Ivory style)

Even the official Mastodon app made this move more than a year ago.

**Comment by Dimillian** [comment]
Done on main. You'll be able to set it with tabbar customizations.
