### ISSUE TITLE
Bug: Trending Tab is now displaying Federated instead. 

### ISSUE THREAD

**Issue by zerodrek** [Dimillian/IceCubesApp#1796]
## Environment:

 - OS: 
 iOS 17.2.1
 - IceCubesApp version: 
 1.10.4

## Description

When navigating to the Trending tab it displays the Federated timeline instead. It was working fine this morning after I first updated to 1.10.4. When I opened the app a few minutes ago it suddenly started exhibiting this behavior. I have tried closing and restarting the app and clearing cache within the app and the issue still happens. 

![IMG_5796](https://github.com/Dimillian/IceCubesApp/assets/2582474/ab6fafcc-2da0-42fe-8ad5-15c43e4a3285)

## Related Issues

The same issue is occurring when using the Local tab. 

 
![IMG_5797](https://github.com/Dimillian/IceCubesApp/assets/2582474/93720827-a533-4ef1-9653-934921e55fc5)

**Comment by Dimillian** [comment]
Fixed on main will soon be released
