### ISSUE TITLE
Bug: MIssing Bookmark Button on Statuses

### ISSUE THREAD

**Issue by ifacodes** [Dimillian/IceCubesApp#1797]
## Environment:

 - OS: 
iOS 17.2.1
 - IceCubesApp version: 
Appstore 1.10.15

## Description

As of the latest App Store release the bookmark button is missing from posts.

![E26CAB3C-7F56-41FA-BDBE-06BC4395A954](https://github.com/Dimillian/IceCubesApp/assets/6687517/906c0de3-9b52-4353-808c-83eda68a9e58)

## Related Issues

None.

**Comment by qauff** [comment]
The option to swap the share action with the bookmark can be found in settings now.

https://mastodon.online/@IceCubesApp/111657732508281784
