### ISSUE TITLE
Have an empty account under the accounts section Mac OS can't remove it. Clicking the chevron does nothing

### ISSUE THREAD

**Issue by MariaFeodora** [Dimillian/IceCubesApp#180]
Have an empty account under the accounts section Mac OS can't remove it. Clicking the chevron does nothing

![Image](https://user-images.githubusercontent.com/65338652/213741834-cae53d22-2099-4f92-a421-1bd71467eea4.png)

**Comment by selfagency** [comment]
Same issue on iOS for me

![ef2d72f80fbe0734](https://user-images.githubusercontent.com/2541728/215300032-8d01473c-8b26-4c72-a961-47ae1c99b892.jpeg)

**Comment by mijndert** [comment]
Same here. I accidentally removed app access for Ice Cubes on my Mastodon profile and now I have an infinite loop and an account I can't remove anymore. 

![image](https://user-images.githubusercontent.com/626972/215403020-39a29350-0e5d-4629-864b-8c21af4006d0.jpeg)

**Comment by Dimillian** [comment]
Swipe to delete. I'll add a context menu soon.

**Comment by mijndert** [comment]
@Dimillian thanks! Due to the chevron, this is not super discoverable. But it could also be me not being super familiar with UI conventions in iOS.
