### ISSUE TITLE
Bug: Boost and Favorite buttons don’t work

### ISSUE THREAD

**Issue by SiffBA** [Dimillian/IceCubesApp#1800]
## Environment:

 - OS: 
 iOS 17.2.1, iPadOS 17.2
 - IceCubesApp version: 
 1.10.5 (and previous 2-3 versions)

## Description
The “Boost” and “Favorite” buttons under a post are very hard to touch - it looks like the touch targets are smaller and down and to the right from the icons. The other buttons under a post have the same issues, but to a lesser extent.

## Related Issues
None found

**Comment by Dimillian** [comment]
Fixed on main will be released soon
