### ISSUE TITLE
Feature request: followed hashtags in Compose window

### ISSUE THREAD

**Issue by aquariusdev** [Dimillian/IceCubesApp#1802]
A button in the bottom of the Compose window could open a sliding menu of followed hashtag pills to multi-select and add to the post. This would make it easier to post with preferred hashtags and not have to type them out, and by extension make posts easier to find via search. This would be easier than just autocomplete with popular hashtags. 

Optionally, whole followed tag groups could appear as pills to select at once from the menu by widening the menu and having tag groups appear in their own sliding rows, and selecting a tag group would automatically populate the end of the content in the compose window (instance character limits permitting). 

Tumblr's mobile app has a good example of this in action.
![image](https://github.com/Dimillian/IceCubesApp/assets/28520002/1fcbaef6-be00-4790-810e-410fa29726f3)

**Comment by aquariusdev** [comment]
My first rough mockup: ![add tags mockup](https://github.com/Dimillian/IceCubesApp/assets/28520002/938a66d8-a600-4084-b791-3d3c1f417b34)

**Comment by Dimillian** [comment]
I like it!

**Comment by Dimillian** [comment]
Done
