### ISSUE TITLE
Bug: tag group icon selection moves focus 

### ISSUE THREAD

**Issue by FiniteLooper** [Dimillian/IceCubesApp#1808]
## Environment:

 - OS: iOS 17.2.1
 
 - IceCubesApp version: 1.10.6
 

## Description

When creating a tag group it wants an "SF Symbol name" which is absolutely not clear what this means. I assumed I could skip this so I want and added my tags below. 

After doing so I realized I was unable to save, which means the tag group icon was required I guess. When I tried to add it my focus was constantly moved to add a new tag. 

Basically: if no icon is selected, once tags are added it's impossible to go back and add an icon without first deleting all the tags.

Also once a tag group is created there appears to be no way to edit it? I have to delete it and then recreate it from scratch. This is too much of a hassle so I'm just skipping using this feature all together. 

Here is a screen recording of the tag group editor moving my focus.

https://github.com/Dimillian/IceCubesApp/assets/463685/a98d628e-b518-43ca-8ed8-35ed21e181f4

## Related Issues

 - [X] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
If you select the tag group in the timeline you'll see an edit button.

**Comment by FiniteLooper** [comment]
Ah, so there is. And I can edit them from the settings after tapping on it, sorry not sure what I was doing before.

However, the tag group icon selection does feel very broken. In addition to what I wrote above I just noticed that when typing out an icon name, and then attempting to scroll horizontally to select one, that causes the list of icons to disappear and I have to start over again! Looks like when you search for an icon you have to choose one already visible, anything offscreen is not possible to scroll to.
