### ISSUE TITLE
Bug: Web Preview missing on posts with tags

### ISSUE THREAD

**Issue by S3basuchian** [Dimillian/IceCubesApp#1812]
## Environment:

 - OS: 
 iOS 17.2.1
 - IceCubesApp version: 
1.10.8

## Description

I noticed that posts containing tags do not show a web preview. The official client shows web previews in this case and I think this should be the intended behaviour (see attached images for comparison)
![IMG_9BF023BA7B69-1](https://github.com/Dimillian/IceCubesApp/assets/16594310/e6fa0e30-2593-4793-b7f2-3c675bac8fdb)
![IMG_9BF023BA7B69-2](https://github.com/Dimillian/IceCubesApp/assets/16594310/c5522f0f-076e-45ef-b1c8-e887cafdf814)

**Comment by Dimillian** [comment]
Hmmm that is weird. Are you logged on the same account on both apps? We don't do anything with web preview. We just display them if the post contains one. But it needs to be sent by the instance.

**Comment by S3basuchian** [comment]
Yes it is the same account. And I have noticed that the web previews are specifically missing on accounts that post tags after the link. For example this one: @ORF_News@orfodon.org

**Comment by Dimillian** [comment]
![image](https://github.com/Dimillian/IceCubesApp/assets/535509/ca0a6145-b439-4dbd-bc62-f7107cf869c6)

This was an old rule, this is getting fixed, thanks for the report!
