### ISSUE TITLE
Bug: Notification text disappear

### ISSUE THREAD

**Issue by lumaa-dev** [Dimillian/IceCubesApp#1815]
## Environment:

 - OS: iOS 17.2.1
 - IceCubesApp version: 1.10.10

## Description

Notifications often loose their content and images, simply replaced by "A new notification has been received". This issue has [already been addressed on Mastodon](https://techhub.social/@lumaa/111672316714986448), even after restarting the device the notifications were fixed for a small amount of time.\
It doesn't seem to happen on macOS tho.

Edit: It seems that updating the app fixed it? I don't know if it's temporary so I'll keep this issue opened for a little until I can evaluate if the bug is fixed or not

![Bugged notification](https://github.com/Dimillian/IceCubesApp/assets/93350976/68b12371-06b6-4103-b363-6534980693ab)

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
It's an iOS issue, unfortunately. Sometimes the notification extensions is killed and the only fix is a reboot.

**Comment by lumaa-dev** [comment]
There was an update at some point which fixed this issue without a reboot, I don't know if it's gonna kill again the notification extension so that's why I kept this issue opened temporarily.

**Comment by Stooovie** [comment]
Keeps happening on iOS 26.2 RC and IC 2.0.9, and it's the only app that's having that issue. Reboot doesn't fix it. Notification previews are set to Always.
