### ISSUE TITLE
How did you add local packages?

### ISSUE THREAD

**Issue by Gargo** [Dimillian/IceCubesApp#1825]
How do you add packages to "sources" section?
<img width="257" alt="Снимок экрана 2024-01-05 в 18 13 10" src="https://github.com/Dimillian/IceCubesApp/assets/853345/b3e7f02d-855a-45ef-a699-6d91d6e92a4d">

Tried steps from this tutorial but they appear in "package dependencies" section:
https://www.delasign.com/blog/xcode-swift-package-manager-local/

**Comment by Gargo** [comment]
@Dimillian why did you close it?

**Comment by pshadov** [comment]
@Gargo https://forums.swift.org/t/how-to-add-local-swift-package-as-dependency/26457/4
tldr; just drug&drop them from Finder.
