### ISSUE TITLE
Bug: Missing sound in videos

### ISSUE THREAD

**Issue by alexh-swdev** [Dimillian/IceCubesApp#1832]
## Environment:

 - OS: 
 iOS 17.2.1 
 - IceCubesApp version: 
 IceCubesApp v1.10.14

## Description

Videos in Toots don’t play their sound. (Yes, they are not muted and have a sound in the Mastodon web app ;) )

## Related Issues

 - [x ] Search that this bugs don't already exist before creating it.

**Comment by blueturtleai** [comment]
„Not muted“ means, sound is enabled via the video viewer sound control at the top right?

**Comment by alexh-swdev** [comment]
Yes, in the video itself (top right corner) as well as on the iPhone (13)

e.g. https://zdf.social/@ZDF/111606943355189262
(But it affects any embedded video I tried to watch in the last couple of weeks. It works in the (official) web frontend, but not in icecubes (unfortunately))

**Comment by blueturtleai** [comment]
I also couldn’t hear the sound. In many other cases it worked for me.

**Comment by alexh-swdev** [comment]
If i tap on the "i", then the video reloads in another over popup and I can here the sound.

**Comment by blueturtleai** [comment]
I hope, that @Dimillian finds a way to fix it 😎.

**Comment by blueturtleai** [comment]
Answer from @Dimillian on mastodon: „Yup but it's not new, normal view default to muted. I've fixed a bug tho, now you tap on the video and it'll play non muted (even if your phone is muted) in the big view. I plan to fix it eventually tho.“

So, your phone was muted, right? In my case that was the reason. If I unmute, I can hear the sound.

**Comment by blueturtleai** [comment]
Fixed for me in 1.10.17.

**Comment by alexh-swdev** [comment]
For me, too. I'll close it ,then.

Thanks @blueturtleai @Dimillian
