### ISSUE TITLE
Feature request: Show poll results without voting

### ISSUE THREAD

**Issue by Syphdias** [Dimillian/IceCubesApp#1835]
Sometimes I want to see the results of a poll without voting. There are various reasons for that:
- I don't want to answer the poll.
- I don't know the answer.
- The Question asked at a specific group or author asks to not vote in certain cases.

It would be great if one would long press one of the answers and select "Show results" or a similar mechanism.

**Comment by eric-Is-Me** [comment]
I tried out just making a button to toggle showing/hiding the results in this pr
https://github.com/Dimillian/IceCubesApp/pull/1877

**Comment by Dimillian** [comment]
Fixed for next release ^
