### ISSUE TITLE
Feature request: Hide/Filter answers/boosts on profile tab

### ISSUE THREAD

**Issue by drohmd** [Dimillian/IceCubesApp#1836]
I would like to have a feature to hide answers and/or boosts in the profile tab. Alternatively could it be implemented to filter for toots/answers/boosts and everyone can choose what he or she wants to see on the profile page. 
At the moment you see all toots, answers to toots and boosts at once on the profile page. I usually want to see only the toots of a person (or me).

**Comment by Dimillian** [comment]
New profile will do exactly that.
