### ISSUE TITLE
Bug: when composing from the share sheet tapping a tag closes the compose window (maybe a crash?)

### ISSUE THREAD

**Issue by FiniteLooper** [Dimillian/IceCubesApp#1838]
## Environment:

 - OS: iOS 17.2.1
 
 - IceCubesApp version: 10.10.15
 

## Description

From the photos app I share a photo and select IceCubes. When I partially type out a hashtag to use and tap one of the autocomplete suggestions it closes the compose window and I have to start over again. 

Here is a screen recording of this happening (also look at this obnoxious car I saw!)

https://github.com/Dimillian/IceCubesApp/assets/463685/4e0cba29-b78b-4b96-9da6-ded5f370540e

## Related Issues

 - [X] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Fixed in the latest version
