### ISSUE TITLE
Bug: Trending tab only loads 16 posts

### ISSUE THREAD

**Issue by BoxOfSnoo** [Dimillian/IceCubesApp#1840]
## Environment:

 - OS: iOS 17.2
 - IceCubesApp version: 1.10.16

## Description

In the last few releases (since the trending tab could be placed on the toolbar), there are only ever 16 trending posts in the list.  You cannot scroll for more below that.  Refresh only brings in 16 posts.  

I am using mastodon.online, but posts are from federated servers, so there should be more. If I go to the web client of mastodon.online I see many more posts in the "explore" timeline, and can continue scrolling far beyond 16 posts.

## Related Issues

 - [X] Search that this bugs don't already exist before creating it.

**Comment by BoxOfSnoo** [comment]
This didn't seem to solve the issue. I can see 17 now, but not sure if it is because one of the posts has been boosted or not.

**Comment by Dimillian** [comment]
I tend to close issues as soon as it's merged on main. The update is out only since a few hours. Can you try again?
