### ISSUE TITLE
Bug: 4 digit boosts wrap the numbers to another line

### ISSUE THREAD

**Issue by FiniteLooper** [Dimillian/IceCubesApp#1842]
## Environment:

 - OS: 17.2.1
 - IceCubesApp version: 1.10.15

## Description
When there are a number of boosts with 4 (or more probably) digits, the number display on the boost button wraps to the next line and looks broken. 

![image](https://github.com/Dimillian/IceCubesApp/assets/463685/107d7778-109d-4408-8c79-07b42fd16b6b)

## Related Issues

 - [X] Search that this bugs don't already exist before creating it.

**Comment by pshadov** [comment]
What about shortening and flooring the labels for big numbers?
Examples:
1,567 -> 1.5k
27,444 -> 27.4k
1,999 -> 1.9k

**Comment by FiniteLooper** [comment]
I just wanna say I think it's awesome to notice an issue in an app I love and use daily, and it's literally fixed within 24 hours of my reporting it. Great job @Dimillian!

FYI, after submitting this I was thinking that it might be that this is a combination of BOTH the boot and star count being 4+ digits at the same time. I'm not familiar with Swift or the code in this app, so I'm not sure if your fix took care of both counts or not.

**Comment by Dimillian** [comment]
Yes all counts down there will be rounded when over 1000

**Comment by pshadov** [comment]
and they will be rounded to the ceiling, not the floor, as I wrote in the comment above (i.e., 1551 -> 1.6k)

**Comment by Dimillian** [comment]
@pshadov I let Swift decide of that, but this is how Apple implemented it.

**Comment by pshadov** [comment]
totally makes sense, I should have checked `IntegerFormatStyle` API before writing my comment :D
