### ISSUE TITLE
Bug: ui on iphone mini barly usable

### ISSUE THREAD

**Issue by Nachtpfoetchen** [Dimillian/IceCubesApp#1849]
## Environment:

 - OS: 
 IOS: 17.2.1
Iphone 12 mini
 - IceCubesApp version: 1.10.17

## Description

Ui is cut off, sometimes bumbers in TL on top of each other
![IMG_8245](https://github.com/Dimillian/IceCubesApp/assets/47748053/4176b3a8-4e66-47c5-a407-bd69cbe4687d)
![IMG_8246](https://github.com/Dimillian/IceCubesApp/assets/47748053/0282d395-7daa-40cd-9d94-b1414b145046)
![IMG_8247](https://github.com/Dimillian/IceCubesApp/assets/47748053/1cb16e30-e763-4188-8eeb-4439d6078484)
![IMG_8248](https://github.com/Dimillian/IceCubesApp/assets/47748053/13ff068a-ddf6-4059-9083-203a2a73870a)

**Comment by Dimillian** [comment]
I fixed the accessory view bar in the editor. For the actions button on the status, I'll see what I can do, but probably hiding the count in the display settings would help in your case.

**Comment by Nachtpfoetchen** [comment]
Thank you
