### ISSUE TITLE
Option to always expand posts with content warnings

### ISSUE THREAD

**Issue by johncarney** [Dimillian/IceCubesApp#185]
Some mastodon clients have the option to automatically expand posts that have content warnings. It'd be great if Ice Cubes had this option. In this mode, some have a banner on top of the post that indicates that the post is flagged with a content warning.

**Comment by phpmacher** [comment]
When adding "add/edit filters", a possibility to not only hide/delete the matching posts, but to generate a CW, if the filter matches. That would be a great feature.

**Comment by eddieroger** [comment]
I would love the (originally proposed) feature as well, an am going to take a crack at it as time allows as a PR. I hope that doesn't stop other, more competent Swifters from doing it if they come across this.
