### ISSUE TITLE
Feature request: Media window enhancements on macOS

### ISSUE THREAD

**Issue by huxi** [Dimillian/IceCubesApp#1851]
- the media window (the one popping up if you click on an image or video) should support closing via Esc key.
- currently, this media window quickly opens and closes in case of a webpage (vs. image/video). It would be nice if this wouldn't happen and the webpage would open in the browser without quickly flashing the window. This isn't a huge problem, though.

I'd also like to use this ticket to thank you for all of your work on IceCubes. ❤️ I just sent you a donation.

The lack of Esc key support is my only remaining complaint about the app. That's a pretty huge compliment. 😄

**Comment by Dimillian** [comment]
It's been bothering me too. I'll add it soon. 
Also, have you been using the arrow key to navigate between medias?
