### ISSUE TITLE
Bug: Feed items clickable through title menu on macOS

### ISSUE THREAD

**Issue by jiannazzone** [Dimillian/IceCubesApp#1852]
## Environment:

 - OS: 
macOS 14.2.1
 - IceCubesApp version: 
1.10.17 (2363)

## Description

When you have scrolled down in the feed, embeds/links are clickable through the title bar (above the home/trending/etc dropdown). In the screenshot below, clicking in the red area opens the image viewer (the image has been partially scrolled up).

![ice-cubes-screenshot](https://github.com/Dimillian/IceCubesApp/assets/46025473/cf04dd47-359c-4e7b-871a-8929ae03c17f)

**Comment by Dimillian** [comment]
I have no idea what I could do about this. This is entirely down to SwiftUI / macOS Catalyst.
