### ISSUE TITLE
Bug: New post does not appear at top of timeline (unless I pull-to-refresh)

### ISSUE THREAD

**Issue by henrik** [Dimillian/IceCubesApp#1855]
## Environment:

 - OS: iOS 17.2.1
 - IceCubesApp version: 1.10.19

## Description

When writing a new post (tried both "private" and "unlisted") while on the timeline, I would expect the post to automatically show up at the top of the timeline.

But it does not (most of the time), and I need to pull-to-refresh.

Video:

https://github.com/Dimillian/IceCubesApp/assets/216/1f77805b-6162-4e04-bd0c-eb7837a81247

I've tried it something like 5 times, and 1 out of those times I believe it did appear as expected.

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
So the app is entirely reliant on your instance stream events. Sometimes the instance stream is off which will make the post a no-show until you refresh or manually fetch new post.
I'll emit the event locally like for edit.

**Comment by henrik** [comment]
Thank you! ❤️
