### ISSUE TITLE
Bug: unread counter gets cleared when just switching account and switch back

### ISSUE THREAD

**Issue by ikzelf** [Dimillian/IceCubesApp#1869]
## Environment:

 - OS: 
iOS v17.2.1
 - IceCubesApp version: 
v1.10.20
v1.10.21

iceCubesApp shows the correct number of unread items when started.
Change to a different account without reading any message and switch back to the original account
After returning to the original account with a certain number of unread messages, the number is cleared.

expectation: after switch back the unread messages count remains as it was, until the messages are actually read.

**Comment by Dimillian** [comment]
This is a normal behaviour for now and I'm looking for a way to make it better.
