### ISSUE TITLE
Account dropped for no apparent reason

### ISSUE THREAD

**Issue by johncarney** [Dimillian/IceCubesApp#187]
Yesterday I installed Ice Cubes on my iPhone and added my mastodon account. Everything looked good. Then this morning when I fired up Ice Cubes, it prompted me to add an account again. Unfortunately I can't give any steps to reproduce.

See my comment below for more details.

**Comment by amdavidson** [comment]
I don’t see how to +1 this on mobile but the same happened to me this morning.

**Comment by brantfaircloth** [comment]
I also see the same. Occurs seemingly intermittently and have not been able to reliably reproduce.

**Comment by johncarney** [comment]
It happened to me again yesterday, but this time instead of adding an account I force-quitted the app and re-opened and it was fine. I think it might not be a case so much of dropping accounts as inappropriately presenting the "add account" dialog on app launch.

**Comment by johncarney** [comment]
LOL. I just checked the app settings. Looks like it's not dropping accounts—just presenting the add account dialog inappropriately. As I said, this happens at app launch.

![image](https://user-images.githubusercontent.com/322950/213945057-06e377a9-6dc1-469f-9925-020c71515bd1.jpeg)

**Comment by samscam** [comment]
Just had the AppStore build lose my accounts here. Appears to have fully reset.
