### ISSUE TITLE
Bug: click on the Navigation Title bar is passed through to element behind it

### ISSUE THREAD

**Issue by maxbobse** [Dimillian/IceCubesApp#1871]
## Environment:

 - OS: 
macOS 14.1
 - IceCubesApp version: 
Version 1.10.18 (2384)

## Description

When clicking on the navigation title bar it is sending the click event to the item behind it and for example opens the post. 
<img width="467" alt="Screenshot 2024-01-12 at 11 08 26" src="https://github.com/Dimillian/IceCubesApp/assets/65524742/0595047d-d2ff-4748-ae94-fb3e3b0e757b">

**Comment by Dimillian** [comment]
Nothing I can do about it, I hope Apple will fix it.
