### ISSUE TITLE
Feature request: Auto detect source language for translations

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#1891]
If the translation service of an instance is used, it seems that the source language isn’t autodetected. Instead the configured language of the post is used. As the post language is often configured wrong, translation often fails.

I would suggest to always use autodection for that reason. Not sure, if this can be influenced by icecubes or has to be configured on the server side.

Example: post is written in Turkish, but German is configured. This results in this translation. The target language was English, but it’s obviously still Turkish.

![IMG_4952](https://github.com/Dimillian/IceCubesApp/assets/113246030/5d55a652-3550-47be-badc-280d5ef74166)

https://correctiv.social/@correctiv_org/111756443956478200

That happens on hachyderm.io, which has configured LibreTranslate as their translation service. I tried it manually on https://libretranslate.com/ where Turkish was autodetected correctly and the translation worked without problems.

**Comment by Havhingstor** [comment]
The mastodon api doesn't actually allow us to specify the source language, so if we use the built in translation service, we won't be able to give the source language. Our use of the DeepL service uses their autodetect method, so we don't need to specify it here either.

**Comment by blueturtleai** [comment]
What exactly is passed to the built in translation service? The text which should be translated or the URL to the post?

**Comment by blueturtleai** [comment]
Okay, thanks. Obviously the server doesn’t use auto detection, but uses the configured language of the post. I close this issue, as this only could be changed on the server side.
