### ISSUE TITLE
Bug: Tapping top of the Screen doesn't jump to latest post

### ISSUE THREAD

**Issue by Apex-DE** [Dimillian/IceCubesApp#1905]
## Environment:

 - OS: 
 17.2.1
 - IceCubesApp version: 
 1.10.23

## Description

Tapping top space on the screen (near dynamic island) in a pinned timeline of another instance doesn't jump to the latest post on the instance but only loads 100 new posts. This can take ages to get to latest post if you only peek in that instance once-in-a-while.

**Comment by Dimillian** [comment]
And jump to latest is not working to load the new posts directly?

**Comment by Apex-DE** [comment]
no, it only loads a 100 new posts, not the latest one.

**Comment by Dimillian** [comment]
I see the issue, will get fixed in the next release
