### ISSUE TITLE
Issues need tags

### ISSUE THREAD

**Issue by lolbat** [Dimillian/IceCubesApp#191]
Hi

I think that the issues section here needs some tags or labels to help people better represent their posts/comments.

Also maybe a Discussions section for feature requests etc?

**Comment by johncarney** [comment]
There are already labels, but apparently there are restrictions on who can add them. I'd love to be able to flag any issue I create as an "enhancement" or a "bug".

**Comment by johncarney** [comment]
PS. I'm not sure what kind of granularity GitHub has on label permissions, so it may not be possible.

**Comment by Dimillian** [comment]
So you can't add labels? I thought anyone could. For the project it's  definitely only admin, and it's basically me managing my own roadmap.

**Comment by johncarney** [comment]
We can't. I just thought we could save you a little legwork by self-categorizing issues we create. I understand that ultimately you need to triage each issue yourself, but self-categorization might help you prioritize your efforts.

**Comment by Dimillian** [comment]
My wife is actually on it too! But yes I saw... only users who have write access to the repository can do that and let's say it's a bit too dangerous. Also we had conversations, but I think issues + project is just fine. 

@johncarney Thanks a lot for the sponsor!

**Comment by lolbat** [comment]
> only users who have write access to the repository can do that and let's say it's a bit too dangerous. 

It is but are you sure that is the only way to do it? I have seen other repositories that have labels available on their issue posts.

**Comment by johncarney** [comment]
Actually, I was just looking at GitHub's project settings and there are issue templates with standard templates for bug reports and feature requests (thought I think the defaults are overkill). When anyone create a new issue, they can pick whichever template they need (or no template).

**Comment by johncarney** [comment]
@Dimillian You're welcome re sponsorship :)

**Comment by Dimillian** [comment]
All good thanks! Created very basic template that will help put labels on issues!

**Comment by johncarney** [comment]
> > only users who have write access to the repository can do that and let's say it's a bit too dangerous.
> 
> It is but are you sure that is the only way to do it? I have seen other repositories that have labels available on their issue posts.

Only people with write access to a repository can _create_ labels. Anyone with _triage_ access can _apply_ them. You probably don't want to grant triage access to just everybody.

https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels

**Comment by lolbat** [comment]
Thanks
