### ISSUE TITLE
Bug: Immediate crash on iphone / Startet auf iphone nicht mehr 

### ISSUE THREAD

**Issue by Growianer** [Dimillian/IceCubesApp#1913]
## Environment:
 - OS: 
  iOS 17.2.1
 - IceCubesApp version: 
 IceCubesApp v1.10.24

## Description

Lässt sich nicht öffnen, stürzt sofort ab.

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by ppuschmann** [comment]
@Growianer please use english... 😀

@Dimillian same issue here 

While browsing the standard home list the app crashed and doesn't want to start again. 

The app is already completely stopped

iOS and Ice Cubes version as above

**Comment by Dimillian** [comment]
Hmmm I guess it's some specific post triggering that. Now I have to find which one.

**Comment by Dimillian** [comment]
If this is in the cache your best bet is to reinstall it unfortunately

**Comment by tron2342** [comment]
Same issue here - reinstall has no effect.

**Comment by Growianer** [comment]
> If this is in the cache your best bet is to reinstall it unfortunately

Reinstall doesn't help...

**Comment by Murgeye** [comment]
Reinstall worked for me. New version was working fine yesterday and this morning until the timeline refreshed - after that no dice.

**Comment by Dimillian** [comment]
I need to find the post that is problematic 😬

**Comment by Murgeye** [comment]
I think for me it's this one: https://mastodon.social/@mkreutzfeldt/111795583554357452

If I scroll past this one, the app crashes.

**Comment by ppuschmann** [comment]
Would a log from the iPhone (taken on macOS) help you?
How could I share this log securely with you?

**Comment by ppuschmann** [comment]
@Murgeye this could be a hint. 
I can't find a similar post on my timeline on my mastodon-instance (web interface). 

Maybe this is related?

**Comment by Murgeye** [comment]
> @Murgeye this could be a hint. 
> I can't find a similar post (of mkreutzfeld) on my timeline on my mastodon-instance (web interface), although I also follow this account.

For me opening his profile (via search) also crashes the app. The post was about 12 hours ago and is a reply to his own post, so it might be buried in your timeline?

**Comment by Dimillian** [comment]
That's a great find! If I can reproduce it it'll get fixed right away!

**Comment by Dimillian** [comment]
Hmm I can browse his profile and don't get any crash.

**Comment by Murgeye** [comment]
That's weird, it is reproducible for me (see screencast below). Can I do anything to help debug this?

https://github.com/Dimillian/IceCubesApp/assets/16648242/4dee1f49-4437-47aa-94f4-9e3f2cbad887

**Comment by Dimillian** [comment]
Can you reboot your phone and tell me if this is still happening?

**Comment by ppuschmann** [comment]
App still crashes upon startup. 
-> turn iPhone off, then on again
-> App still crashes upon startup

**Comment by Dimillian** [comment]
> That's weird, it is reproducible for me (see screencast below). Can I do anything to help debug this?
> 
>  trim.AFA002CF-2645-4B1C-9DD2-4C5EE5EF1269.MOV

It was more for this behaviour

**Comment by Flachlandcoder** [comment]
Same problem here. I don't know if it is helpful, but the last thing I noticed before the app started crashing, was that only a part of the images appended to the toots were loaded. The older images were no longer visible, only the images of the most recent toots.

**Comment by Murgeye** [comment]
> > That's weird, it is reproducible for me (see screencast below). Can I do anything to help debug this?
> 
> > 
> 
> >  trim.AFA002CF-2645-4B1C-9DD2-4C5EE5EF1269.MOV
> 
> 
> 
> It was more for this behaviour 

The crash on visiting the profile remains on reboot. I have no insights on the internals of mastodon, but if this only happens for me, this might be an issue caused by federation with my instance (infosec.exchange)?

**Comment by blueturtleai** [comment]
I entered the mentioned url https://mastodon.social/@mkreutzfeldt/111795583554357452 in the search field on the explore tab and the app crashes immediately before even showing the post.
iOS 17.2 icecubes 1.10.24

**Comment by appinator** [comment]
1.10.26 fixed it for me.

**Comment by blueturtleai** [comment]
1.10.26 fixed it for me too.

**Comment by Dimillian** [comment]
Oh yeah okay this is it! https://github.com/Dimillian/IceCubesApp/commit/92662665b9d8238d88d0914db1c727edba8f7fcc

So it was already solved, that's why I could not reproduce it on my version.

**Comment by Dimillian** [comment]
Thanks all!
