### ISSUE TITLE
Feature request: Optimization for macos

### ISSUE THREAD

**Issue by mofneko** [Dimillian/IceCubesApp#1922]
The current version runs on catalyst and is dependent on the iOS version, even though it runs on macOS.

Also, there are many apps that don't work with macOS Sonoma at this stage, so I don't think it's a good idea to have a configuration that requires the latest version of macOS.

**Comment by Dimillian** [comment]
Well it runs on SwiftUI with the latest API, and this is not something I'll change anytime soon. Maybe one day I'll do a truly native macOS client but this will be a different app then.
