### ISSUE TITLE
Bug: sharing Videos from the Photos App not working

### ISSUE THREAD

**Issue by Apex-DE** [Dimillian/IceCubesApp#1923]
## Environment:
 - OS: iOS 17.3
 - IceCubesApp version: 1.10.27

## Description

when selecting a video recorded with the iPhone and i try to share via the photos app and i select IceCubes as target, the IceCubes Post Composer opens and closes/crahses after about 2 seconds. Posting the video from within the App with the media selector works fine.
I can send a screen-video of the bug via mail for showing the bug in action.

**Comment by Dimillian** [comment]
Yes because I cannot reproduce. How long is the video?

**Comment by Apex-DE** [comment]
Hi,

it’s a short Video shot on iPhone14pro. Whats your Mail address?

Greetings

**Comment by Dimillian** [comment]
hello@dimillian.app

**Comment by Dimillian** [comment]
Fixed in next version, shipping soon

**Comment by Apex-DE** [comment]
the issue got better with the fix, but it isn't gone. I have a 14mb sample for you to test, which still triggers the bug.
