### ISSUE TITLE
Bug: Probable memory leak with animations

### ISSUE THREAD

**Issue by bradheintz** [Dimillian/IceCubesApp#1925]
## Environment:

 - OS: iOS 17.2.1 on iPhone Xs Max
 - IceCubesApp version: 1.10.27

## Description

Repro:
- Open the app and browse the profile of @cmzw@mastodon.social
- Note: @cmzw@mastodon.social's posts consist mostly of animated content
- Scroll down, giving animations a chance to load
- Observe that at some point, IceCubesApp crashes
- After the crash, attempt to use another app (e.g. Facebook Messenger)
- Observe performance issues in the other app (e.g. long time on launch screen, profile pics no loading, etc.)

Other apps, including a re-launched IceCubesApp, will be similarly affected. Power-cycling the phone is necessary to restore normal functionality.

I haven't gone at it with debugging tools, but this has all the hallmarks of a major memory issue.

## Related Issues

 - [√] Search that this bugs doesn't already exist before creating it.

**Comment by bradheintz** [comment]
The issue appears to repro on IceCubesApp 1.10.26 running on macOS Sonoma 14.1.1 on a 2019 MacBook Air with 16GB RAM and no other apps running. Activity monitor shows Memory and Real Memory usage increasing monotonically, with scrolling becoming unusably jerky and new animations unusably slow to load before either of those reaches 1GB.

I haven't gone as far as inducing a crash on macOS.

I also checked the official Mastodon iOS client (same iPhone mentioned in the initial issue report) and Mastodon on the web (Firefox 121.0.1, same MacBook Air as above), and experienced no problems scrolling and no skyrocketing memory usage.

**Comment by Dimillian** [comment]
Amazing! Just found a huge leak!
