### ISSUE TITLE
Bug: Notification with large image not completely visible 

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#1926]
## Environment:
iOS 17.2, icecubes 1.10.27

## Description
If a notification with a mention includes a large image, the avatar of the poster isn’t completely visible.

![IMG_4990](https://github.com/Dimillian/IceCubesApp/assets/113246030/d3b5c7a1-1b31-43a4-93c9-180f57119da7)

In general I wonder, why images are displayed now full-size in notifications at all. If I remember correctly, you wrote recently, that notifications have a compact style. For larger view, just tap on the notification 😀.

**Comment by Dimillian** [comment]
This should be fixed in latest release
