### ISSUE TITLE
Bug: number of replies and boosts doesn’t display correctly on iOS

### ISSUE THREAD

**Issue by jimgar** [Dimillian/IceCubesApp#1927]
## Environment 

 - OS: iOS 17.3
 - IceCubesApp version: 1.10.27

## Description

Number of replies and boosts is being cut off when my iPhone is in portrait orientation. Tilting to landscape shows the counts. 

I have an iPhone 12 Mini so I expect this change has gone unnoticed given that not a lot of people use ‘smaller’ phones these days.

![IMG_0087](https://github.com/Dimillian/IceCubesApp/assets/90831652/f6587223-f36f-4e4f-b0a9-df31b7c21a37)

![IMG_0086](https://github.com/Dimillian/IceCubesApp/assets/90831652/84ed7fc0-dab3-4280-8dee-cb63930935f3)

![IMG_0085](https://github.com/Dimillian/IceCubesApp/assets/90831652/7535473f-ec42-4688-ae45-8ffa868d7908)

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
I'm wondering what would be the best solution. To scale the text down? Or to turn it off altogether?

**Comment by jimgar** [comment]
Not sure. It looks like whitespace, possibly from the icons, is covering up the text? If that's the case would scaling the text down even help? Turning the text off doesn't feel right because you lose the sense of what's popular at the moment or how much it is doing the rounds.

It didn't used to be this way, I only noticed it in the past several weeks and have only just got around to opening this issue (sorry - I realise that makes it harder to diagnose). Before, the whole number would display just fine.

**Comment by jimgar** [comment]
Hi

Thanks for working on this.

Just to let you know that the PR hasn’t resolved this issue for me, as number of boosts are still hidden by the star’s white space. 

Maybe I need to wait for an update to hit the app store?
