### ISSUE TITLE
Bug: Poll options very large

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#1931]
## Environment:
iOS 17.2, icecubes 1.10.28

## Description
In some cases the poll options are very large. It doesn’t seem to depend on the number of available options, as some polls are formatted correctly.

https://toot.wales/@HannahHowe/111840026639146183
![IMG_5012](https://github.com/Dimillian/IceCubesApp/assets/113246030/f48c6dc6-fcb8-4855-a010-f5afd678c831)

https://alt.lawndale.space/@bugbear/111839942889649277
![IMG_5013](https://github.com/Dimillian/IceCubesApp/assets/113246030/2c8ac51d-f87b-4274-ac6e-12ca4740ea60)

**Comment by thai-d-v** [comment]
Fixed by #1929
