### ISSUE TITLE
Feature request: Option to automatically expand and reveal sensitive media posts by a specific user

### ISSUE THREAD

**Issue by sh95014** [Dimillian/IceCubesApp#1933]
https://mastodon.xyz/@xkcd is a bot that posts once every few days and always sets a spoiler warning and marks the comic strip as sensitive. Would be good to have an "allow list" option to override those for a specific (trusted) user.

Basically, "Always show media" and "Always expand posts marked with content warnings", but only for a list of users.

**Comment by Dimillian** [comment]
I'm closing this as I don't do a specific client-side feature like this.
