### ISSUE TITLE
Bug: Respect the allowed number of attachment in the instances api response

### ISSUE THREAD

**Issue by ileodo** [Dimillian/IceCubesApp#1943]
## Environment:

 - OS: 
MacOS 14.2.1 (23C71)
 - IceCubesApp version: 
Version 1.10.29 (2490)

## Description

I understand by default, mastodon only allow 4 media attachments. however some instances might have vary setup. I believe that's why the instance endpoint has a field (`max_media_attachments`)[https://github.com/mastodon/mastodon/blob/1666b1955992e16f4605b414c6563ca25b3a3f18/app/serializers/rest/v1/instance_serializer.rb#L67]  indicating the max number of media attachment supported by that instance.

So, shall we remove the hard coded 4 from this wonderful client, and just respect the number returned in the instance api request?

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Good idea and done for next release!

**Comment by ileodo** [comment]
@Dimillian thanks for the rapid response on this!
I think in the timeline view, each status will only show 4 attachment, would it possible to remove that restriction and leave it to the server to control it?

happy to create a separate issue to track it.

**Comment by Dimillian** [comment]
I'll fix it too

**Comment by ileodo** [comment]
awesome.. I'll definitely be a sponsor for this!!
