### ISSUE TITLE
Feature request: Hide answers to blocked toots

### ISSUE THREAD

**Issue by drohmd** [Dimillian/IceCubesApp#1951]
If I block hashtags/words using filters I can't see the filtered toot itself, but If someone I follow answers to the toot I see the answer in my timeline. 
Since I don't have the filters without reason I don't want to see anything of the filtered stuff. 

Is it possible to implement a feature to hide the answers in addition?

**Comment by Dimillian** [comment]
The filter are the server side one. It's working exactly how it works on Mastodon at the API level. I don't plan to do client side filters so unless Mastodon make it work the way you want it won't change.
