### ISSUE TITLE
Bug: Pinned List Refresh Get Only First 100 Items

### ISSUE THREAD

**Issue by 702573N** [Dimillian/IceCubesApp#1960]
## Environment:

 - OS: iOS 17.3.1 / macOS 14.3.1
 - IceCubesApp version: 1.10.31

## Description

Since the last two updates some (not all) pinned lists refresh automatically on startup but only the first 100 new items. After refreshing manually by pulling down the list, the next 100 items appear. The only way to get all items is by clicking on "Jump To Newest"

## Related Issues

 - [X] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
But this is the expected behavior when saving your position. Only the home timeline will load all the pages. Will look into if I can bring that to all other timeline but I am not sure.

**Comment by Dimillian** [comment]
Actually it was a simple fix!
