### ISSUE TITLE
Bug: 1.10.31 Can’t find settings to configure Share button behavior

### ISSUE THREAD

**Issue by jjarava** [Dimillian/IceCubesApp#1961]
- OS:  iOS 17.2.1
 - IceCubesApp version: 1.10.31

## Description

Version 1.10.31 changed share button to share only links. Version description mentions that behavior can be configured in settings, but I can’t find the place. 

 - [x] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
it's in content settings.

**Comment by jjarava** [comment]
Thanks!! 🙏
