### ISSUE TITLE
Bug: Bar at top of some profiles 

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#1973]
## Environment:
iOS 17.2 icecubes 1.10.31

## Description
In some profiles a bar in background color is shown at top. At first I thought it’s a problem of the profile header image, but this seems not to be the case. The problem also occurs without an profile header image. For the profile of @Dimillian the problem occurs for example too.

![IMG_5073](https://github.com/Dimillian/IceCubesApp/assets/113246030/45b776fc-a7d1-4f24-9b0d-07b44e7a6b8c)

![IMG_5077](https://github.com/Dimillian/IceCubesApp/assets/113246030/07d9c10b-2b9a-401a-9fca-544fe89bfac3)

![IMG_5079](https://github.com/Dimillian/IceCubesApp/assets/113246030/89febf89-71c7-4e41-b96e-e200c00626f7)

**Comment by Dimillian** [comment]
Oh yeah it's bugging me, I'll look into it, at least before #1389

**Comment by blueturtleai** [comment]
Fixed in 1.10.44. Thanks @cschindler !
