### ISSUE TITLE
Bug: Crash after cancelling post creation

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#1992]
## Environment:
iOS 17.2 icecubes 1.10.32

## Description
When cancelling creation of a new post, icecubes crashes. It doesn’t always happen, it seems, some specific conditions have to be met. For the case I have recorded in the video, it happens most of the time: https://www.threads.net/@mosseri/post/C34VTugu42j

The crash happens at the end of the video after deleting the draft. It also happens when saving the draft.

https://github.com/Dimillian/IceCubesApp/assets/113246030/972cc211-8fc8-4c09-94b1-0989341b2192

**Comment by nullishamy** [comment]
Also crashes when deleting drafts of replies (if that is a different component).

**Comment by technocidal** [comment]
Happens to me as well. I'll have a look this evening to try to figure out what's happening.

**Comment by blueturtleai** [comment]
Didn’t happen to me for a long time, for that reason I close this issue.

**Comment by technocidal** [comment]
Same here. Everything is stable at the moment.
