### ISSUE TITLE
Bug: Option "Hide these posts from Home" does not save

### ISSUE THREAD

**Issue by adzsx** [Dimillian/IceCubesApp#2012]
## Environment:

 - OS: 
iOS v17.4
 - IceCubesApp version: 
IceCubesApp v1.10.32

## Description

List option "Hide these posts from Home" does not self inself after hitting Done resulting in all posts be shown in the home tab. If a list was set to Hide posts before a certain time, the options stays set, but trying to enable it now results in this bug.

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by BenMelchior** [comment]
Same for me with:

OS: 17.2.1
IceCubesApp version: 1.10.30

Opened already #1946.

**Comment by adzsx** [comment]
Opened already https://github.com/Dimillian/IceCubesApp/issues/1946. 
Sorry and Thanks @BenMelchior
