### ISSUE TITLE
Bug: No way to exit list creation dialog in macOS

### ISSUE THREAD

**Issue by sh95014** [Dimillian/IceCubesApp#2014]
## Environment:

 - OS: 
 macOS Sonoma 14.4
 - IceCubesApp version: 
 1.10.33 (self-built)

## Description

On macOS, there's no way to exit the list creation dialog. Clicking outside the dialog does not dismiss it, unlike on iPad.

<img width="616" alt="截圖 2024-03-23 上午11 51 24" src="https://github.com/Dimillian/IceCubesApp/assets/95387068/f6b2af62-b831-4182-b0ec-a24808fe5f6c">

## Related Issues

 - [X] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Fixed
