### ISSUE TITLE
Bug: read vs unread position within notifications not kept 

### ISSUE THREAD

**Issue by genebean** [Dimillian/IceCubesApp#2015]
## Environment:

 - OS:  iOS 17.4.1 (21E236)
 
 - IceCubesApp version: 1.10.32
 

## Description

Unlike the timelines within the app, the list of notifications doesn’t visually track what I have and haven’t read. This makes it really hard to know if I’ve actually reviewed all my notifications. 

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
It's not a bug, it's just a feature that is not implemented nor that I plan to implement. Notifications are notifications, a list of the latest stuff that happened on your account with the most recent on top.

**Comment by genebean** [comment]
Wow... not the reaction I expected. Making notifications harder to process is far from a feature.
