### ISSUE TITLE
Bug: Searching followed users doesn’t work 

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#2027]
## Environment:
iOS 17.2, icecubes 1.10.33

## Description
Searching in followed users doesn’t show a result. Only a preview is shown.

![IMG_5277](https://github.com/Dimillian/IceCubesApp/assets/113246030/7ad35957-87a9-4f2e-a3e9-d54e2ec38af5)

**Comment by nileshteji** [comment]
The search here works fine for me , can you try to reproduce and attach some video for it ?

**Comment by blueturtleai** [comment]
Just tried it again and couldn’t reproduce. Seems it was only a temporary problem.
