### ISSUE TITLE
Feature request: Add a 'mutuals' timeline

### ISSUE THREAD

**Issue by Lr-K** [Dimillian/IceCubesApp#2059]
In addition to 'Home', 'Local', 'Federated' and any custom timelines, there should be a 'Mutuals' timeline that only shows posts from people you follow that also follow you back.

This would provide an easier method to catch up on posts made by friends without managing a list manually.

**Comment by prsmr** [comment]
That would be awesome, but wouldn't the feature request be better suited for the Mastodon repository? It's probably easiest to implement through the API.

**Comment by Dimillian** [comment]
Not possible at the API level, indeed not possible in the client.
