### ISSUE TITLE
Feature request: Follower count widget

### ISSUE THREAD

**Issue by mamarguerat** [Dimillian/IceCubesApp#2078]
As you are in adding widgets to IceCubes, it would be great to have a widget with a follower count. And it would be event greater if we can add multiple accounts in a single widget to get an overview of the followers count of different accounts.

Thanks for the development of this app.

**Comment by Dimillian** [comment]
it is planned :)

**Comment by Mac3n** [comment]
Hi @Dimillian,
I checked the project and am interested in contributing to it. If there is a specific plane or design that you could share, I am happy to start with this feature :)
