### ISSUE TITLE
Bug: List view suddenly errors on load

### ISSUE THREAD

**Issue by alper** [Dimillian/IceCubesApp#209]
It was working fine and then all of a sudden. 

![image](https://user-images.githubusercontent.com/72429/213848739-01d58d88-2b3c-4962-b935-839bec6101b5.png)

**Comment by codepope** [comment]
I've had a prod and my current working theory is that it is this post

https://botsin.space/@newsyc250/109725835177289332

Or similar which includes a URL with an emoji blowing up the decoding.

**Comment by alper** [comment]
Mine is back now and it didn't seem to be server error.

Next time I'll see if I can pull logs.

**Comment by codepope** [comment]
Scroll down your timeline and you should hit the dodgy toot... or look at https://botsin.space/@newsyc250 and that will (at least for now) show the same issue.

**Comment by Dimillian** [comment]
So in the latest version I changed a bit how the timeline is loaded to smoother but than if there is an error loading one status it could throw this error. 
I've made it safer for the next update and I'll look at the user linked to try to understand why it's happening, thanks!
