### ISSUE TITLE
Bug: iOS 18 timeline position

### ISSUE THREAD

**Issue by mamarguerat** [Dimillian/IceCubesApp#2099]
## Environment:

 - OS: iOS v18.0 Developer Beta
 - IceCubesApp version: v1.10.41

## Description

With iOS 18 the timeline position is no longer saved and the "new posts count" in the top right of the screen no longer scrolls the timeline to the first unread post when clicking (the click of the button does nothing).
The "Fast Refresh" setting is disabled.

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
This is beta 1, so will probably wait on Apple a bit for this

**Comment by ChrisRudall** [comment]
I also see this behaviour on iOS 17.5.1

**Comment by djh1997** [comment]
Also seeing 

will keep an eye on it over next few betas if you need app logs let me know

**Comment by WaterSword** [comment]
Can confirm I am experiencing the same thing. ios 18 dev beta

**Comment by mamarguerat** [comment]
Fixed in v1.10.42
That was fast, thanks !
