### ISSUE TITLE
Bug: immensely laggy on iOS 18

### ISSUE THREAD

**Issue by boehs** [Dimillian/IceCubesApp#2101]
## Environment:

 - OS: 
  v18.0b1
 - IceCubesApp version: 
  1.10.42

## Description

The app is incredibly laggy. I suspect there was a change in implementation on apples end that is causing an edge case and a loop of some sorts. I haven’t experienced this bug in any other app. In the video, each action is being performed almost immediately after the previous one completes

https://github.com/Dimillian/IceCubesApp/assets/51836263/33b5b2dd-e200-4a02-a4d1-3cd82faa59e6

After things “settle”, scrolling performs fine, navigation is still slow.
## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
That's beta 1 for you. For now, nothing I can do further. Apple needs to fix LIst.

**Comment by Dimillian** [comment]
<img width="377" alt="image" src="https://github.com/Dimillian/IceCubesApp/assets/535509/ad70a8be-89d9-4752-ab37-0d9ecc65995e">

**Comment by mbirth** [comment]
Still a thing in Beta 3 btw.

**Comment by Dimillian** [comment]
It is, but still nothing I can do about it :/

**Comment by mbirth** [comment]
I know. 😕

**Comment by Jeehut** [comment]
Same thing here in Beta 3. It's really annoying. Also the loading behavior I don't like. I have to wait, and click it multiple times to get to the latest news. Wish I could see them without delay and scroll down from there.

**Comment by sirtux** [comment]
I see this behaviour as well in the latest iOS 18 Public Beta (22A5316k), and the IceCubes App is the only app so far I have this issue with. I'm happy to report this to Apple, but what exactly should I tell them? 

Thanks!

**Comment by Dimillian** [comment]
The issue is with SwiftUI List. To mitigate it you can hit the top menu button and select "refresh" to flush the timeline and only load the most recent posts. It get slower the more items there is in the List. 
Apple is supposedly working on a fix.

**Comment by sirtux** [comment]
I can confirm with iOS 18 Public Beta 3 the issue is solved.

**Comment by Apex-DE** [comment]
someone else can confirm it is fixed by now?

**Comment by mvoelkl** [comment]
> someone else can confirm it is fixed by now?

Feels way snappier on iOS 18 DB5 😉

**Comment by Apex-DE** [comment]
thanks. Beta train incoming ;)

**Comment by itgrrl** [comment]
I’m seeing this on iOS 18.5. Refreshing the timeline "fixed". Possible regression?

**Comment by michael-baumann** [comment]
Having the same on 18.5 with an iPhone 13 Mini. Scrolling became very slow and hangs for seconds. From the description and discussion here it seems this is back.
