### ISSUE TITLE
Bug: Display polls result to author without voting

### ISSUE THREAD

**Issue by DaveLeonard** [Dimillian/IceCubesApp#211]
Here is a poll with only 1 vote but displaying 3 bars as if it was 3 answers.

![IMG_1133](https://user-images.githubusercontent.com/6861484/213858646-4521cd16-5e48-42ee-84b4-f529b66b188f.jpg)

**Comment by Dimillian** [comment]
It's because for now you have to vote on your own poll in der to see the result. I'll get that fixes.
