### ISSUE TITLE
Bug: Upload errors hidden

### ISSUE THREAD

**Issue by richlv** [Dimillian/IceCubesApp#2116]
## Environment:

 - OS: iOS 17.5.1
 - IceCubesApp version: 1.10.43

## Description

When an image upload fails, the actual error message is not shown, and does not seem to be available in any way. "View error" does nothing.
This might cause an issue, where a user could hammer the server by repeatedly attempting an image upload, even if it is rejected on the server side.

For example, I had an image upload fail, and have retried it dozens of times, as I've seen transient errors before.
As they all have failed, I suspect it could be a permanent failure (image size?) - but meanwhile, I have uploaded this image to the server way too many times.

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.
 
#350 - uploads failing somewhat frequently

**Comment by richlv** [comment]
Looks like in this particular case I got error 500 persistently. Would be great if "View error" would show that :)

**Comment by Dimillian** [comment]
![image](https://github.com/Dimillian/IceCubesApp/assets/535509/a70bc0cb-2c5c-447a-92df-3ce634299750)

This is fixed!

**Comment by richlv** [comment]
Yay, thank you so much :)
