### ISSUE TITLE
Bug: My Inbox is Gone 😱

### ISSUE THREAD

**Issue by Jeehut** [Dimillian/IceCubesApp#2132]
I don't know if it has anything to do with the iOS 18 beta 3 I'm on, but I can no longer find the Inbox tab or feature anywhere. I was using Ice Cubes app only because of that feature, but now there's a "Trending Links" tab in its place which I don't need.

Is this an oversight or a design choice? If it's the latter, I'd probably go back to the official app. At least that one isn't laggy and takes forever to get to the latest posts.

**Comment by Dimillian** [comment]
From the settings you can customize your tabs and from there you can set back the messages to any of the tabs.
