### ISSUE TITLE
Feature request: hide replies and reblogs

### ISSUE THREAD

**Issue by we7ee** [Dimillian/IceCubesApp#215]
It would be nice to be able to hide replies and reblogs in the timeline.

(Like on the Mastodon website)

**Comment by phpmacher** [comment]
A wonderful premium feature would be, if there would be a setting to hide posts in the timeline, with which a user already interacted, that means post he/she has liked or boosted.

Boosted or answered posts with likes from me bring no new information for me.

**Comment by felipebaez** [comment]
Hide reblogs and hide replies is a feature on the web version of Mastodon. Would be great to bring it to the app. This way the user can decide if they see the content from only the people they follow or if they want to see what the people they follow think they should be seeing.

**Comment by we7ee** [comment]
@Dimillian may I ask why you've closed this issue? It's still not possible to hide replies and reblogs in the timeline. I'm not talking about hiding replies/reblogs for a specific account but in general.
Like on the mastodon website:
![image](https://user-images.githubusercontent.com/8250493/224141788-dd2f54a2-92bd-4f10-9d38-56cfb6cac0aa.jpeg)
