### ISSUE TITLE
Bug: Changing theme doesn't refresh the timeline selector on MAC.

### ISSUE THREAD

**Issue by JackL6** [Dimillian/IceCubesApp#217]
If you change theme (say light to dark) then the strip with the drop down timeline selector (Home, Local, Federated, ...) doesn't update and keeps the old colour.

Steps to reproduce: On a MAC, change the theme from dark to light (or light to dark).

This reproduces on Mac.
It doesn't reproduce for me on iOS.

Quitting and restarting the app fixes it, so not too serious.

Attached is a screenshot showing the issue.
Note how hard it is to read the word "Trending".

<img width="862" alt="IceCubesThemeChange" src="https://user-images.githubusercontent.com/96572801/213862801-ebc8840e-7455-4572-99fe-221720259352.png">

**Comment by Dimillian** [comment]
Will be fixed in upcoming version.
