### ISSUE TITLE
Bug: Timeline button no longer works in macOS

### ISSUE THREAD

**Issue by clanger9** [Dimillian/IceCubesApp#2185]
## Environment:

 - OS: 
macOS Sonoma 14.6.1
 - IceCubesApp version: 
1.10.51 (2829)

## Description

Clicking on the Timeline button no longer has any effect.
Previously, it would cause the timeline to scroll to the most recent post.

**Comment by Lobidu** [comment]
This Bug also exists in iOS

**Comment by Dimillian** [comment]
It's already fixed on main
