### ISSUE TITLE
Bug: Version 1.10.52 crasches

### ISSUE THREAD

**Issue by mkonia** [Dimillian/IceCubesApp#2186]
## Environment:

 - OS: 
14.6.1, Silicon Mac
 - IceCubesApp version: 
1.10.52

## Description

Version 1.10.52 crashes immediately on startup. Uninstalling and reinstalling does not solve the problem.

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by dne** [comment]
I have this issue too, since IceCubesApp got updated to 1.10.52.

Also running macOS 14.6.1 on Apple Silicon.

**Comment by seraphyn** [comment]
Sign this
At first I thought it was because of the WM Amethyst.
but even without it the app crashed

**Comment by Dimillian** [comment]
Fix is coming in the next version. Waiting for Review at Apple

**Comment by Dimillian** [comment]
The fix is out!
