### ISSUE TITLE
Option to hide raw web links in posts

### ISSUE THREAD

**Issue by vanitalo** [Dimillian/IceCubesApp#219]
Can you please add an option in settings to allow hiding of the http/s web links in posts when there is a preview rendered in the post. This would make each post in the timeline look cleaner. 
![F5F1FA5E-F261-4721-AD70-9909ACB90635](https://user-images.githubusercontent.com/9300807/213863245-f5f42223-b091-4bb9-8729-5f20b5e53e02.jpeg)

**Comment by henrik** [comment]
I believe Twitter specifically hides the raw link if it’s the last thing in a tweet and not otherwise. Worth keeping in mind. Removing an inline link if the preview is still at the end could get weird :)

**Comment by antijingoist** [comment]
The HTML returned in the post should contain span.invisible at certain points of the URL, so you could search for it that way. Or, depending on how you render it in-app, you can just set the invisible class to not display.
