### ISSUE TITLE
Bug: Filters not applied to other Local Timelines

### ISSUE THREAD

**Issue by TS6ix2GaH3q679h5** [Dimillian/IceCubesApp#2198]
## Environment:

 - OS: iOS 17.7
 
 - IceCubesApp version: 1.10.59
 

## Description

Filters don’t seem to apply to Local Timelines from *other instances* that I’ve added in tabs. They do seem to apply to my own home timeline and my own instance local timeline. 

The filters are set to enabled on “Public Timelines” so it sounds like they ought to be applied to *all* public timelines I have added. 

It would sure be great if they could apply there too. Again these are timelines (local or trending) from *other* instances that I browse in Ice Cubes. 

Thank you very much

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Unfortunately, this won't be possible. Filters are server side, only for your logged instance. Local timeline connect to a remote server to do so, so it can't apply your filters.
