### ISSUE TITLE
Bug: typo in Dutch translation 

### ISSUE THREAD

**Issue by EmilJacobs** [Dimillian/IceCubesApp#225]
The home page is translated to “beging” while it should be “begin” or perhaps “start” or maybe even “thuis”.

**Comment by EvilOne** [comment]
@EmilJacobs I don't speak Dutch. But I set the language of another app to Dutch, and they have **Startpagina** would this work?

**Comment by EmilJacobs** [comment]
Yes, that would work, if it is not too long?

**Comment by EvilOne** [comment]
@EmilJacobs does this work for you?
<img height="50%" src="https://user-images.githubusercontent.com/169561/213918364-b9316407-b7b3-4dd1-a951-a3bf6f0d451b.png">

**Comment by EmilJacobs** [comment]
I think so, yes 🙂

**Comment by EvilOne** [comment]
Thanks, I have updated things, and it will be released in a future version.

**Comment by icod** [comment]
@Dimillian, this issue may be closed. "beging" has been changed to "startpagina" and is now simply "start".
