### ISSUE TITLE
Feature request: compact/consolidated view in notifications 

### ISSUE THREAD

**Issue by Bexxia** [Dimillian/IceCubesApp#231]
In testing out a few Mastodon apps, I particularly love the way one presents notifications into groups - it makes it much quicker to see what kind of actions have been taken and looks aesthetically very pleasing. Tapping a group then expands the detail. I was wondering if there could be an option for something similar?

I’ve attached a screenshot for reference. 

![IMG_3020](https://user-images.githubusercontent.com/123167801/213870905-bd13a67c-a9c0-4831-a0de-16a2ec0aa8ad.png)

**Comment by Dimillian** [comment]
I wonder how accurate it is? My accounts can get more than 500 notifications per hour, for doing something like that, and accurate, it mean I would have to fetch hundreds of pages of notifications to get it working. 

In theory I would looooove to do it, in practice it'll probably be not accurate :/

**Comment by Bexxia** [comment]
> I wonder how accurate it is? My accounts can get more than 500 notifications per hour, for doing something like that, and accurate, it mean I would have to fetch hundreds of pages of notifications to get it working.
> 
> In theory I would looooove to do it, in practice it'll probably be not accurate :/

Ah, I’ve no idea about the technical limitations, just thought it looked good and it works well with my (small) account. Would be great if you could implement something similar, but appreciate your concerns on how accurate it would actually be.

**Comment by antijingoist** [comment]
For many things it gives you the number in the json, which is how I did it on mine.

ie: for Favourites, you can check the notification.type (Favourite), then grab notification.status.favourites_count, presenting favourites_count - 1. Then check the notification.status.id, and any more favourite notifications for that status id you ignore. 


I'm glad Mona is doing it. I thought I was going to be the only one. :D

**Comment by ruhrscholz** [comment]
To add one more data point, the Wooly App seems to do the same: https://mastodon.social/@charliemchapman/109757465278236970

**Comment by antijingoist** [comment]
As long as we are adding datapoints: 

Tusker also does grouping (in a different implementation tho): 

https://social.shadowfacts.net/objects/4828f1d0-5d41-432b-b6a9-7b84a1032d0e

**Comment by jdanthinne** [comment]
Here's a working prototype with consolidated notification (only working for favorited or boosted posts for now), but it only groups notification from the loaded page(s). Would it be a first nice step?

![Simulator Screen Shot - iPhone 14 Pro - 2023-01-27 at 09 53 05](https://user-images.githubusercontent.com/485107/215046267-6c542523-a9f9-4179-b3a6-cca5bd515218.png)

**Comment by antijingoist** [comment]
That's how i did it at first. It's a great first step. :)
(I'm not sure the idea of grouping works very well outside of boosts and favourites. I'm only grouping on boosts and favourites :D)
Since notifications includes total reblogs, favourites and replies on each notification, I also include that and just ignore all additional favs or reblogs for that post.
I don't have profile pics yet.  :D

**Comment by ruhrscholz** [comment]
That looks gorgeous! As @antijingoist already mentioned, you wouldn’t necessarily search mutuale pages for notifications that can be grouped, in my opinion it would be more than enough to group consecutive favorites/boosts, should be easier to implement too

**Comment by jdanthinne** [comment]
Currently I'm not at all searching multiple pages. At first I was grouping everything, all loaded pages together, but I changed that to only group per page. It seems to work fine.

**Comment by Dimillian** [comment]
This is amazing! But I think yes to be a bit better, you can load at least a few pages, for my account for example, it'll not be nearly accurate enough wit this one page. But wow! Feel greats to see it in the app!

**Comment by Dimillian** [comment]
Yes, maybe juste consecutive is enough, and much simpler, and then you don't need to fetch as much pages.
