### ISSUE TITLE
Search input not captured properly with Bluetooth keyboard

### ISSUE THREAD

**Issue by j2xl** [Dimillian/IceCubesApp#243]
Running iOS 16.2 with an external Bluetooth keyboard, go to the Explore :mag: tab. Tap the search box. Type `icecubes` using an external keyboard.

Intermittently, the cursor moves one character to the left, so `icecubse` or `Icuesbce` appears as input.

**Comment by Dimillian** [comment]
Fixed in 1.0.5 :)
