### ISSUE TITLE
Feature request: Support landscape orientation for viewing media

### ISSUE THREAD

**Issue by ryankoski** [Dimillian/IceCubesApp#245]
Please consider supporting landscape orientation on iPhone when viewing media. It seems the current implementation forces the entire app to always use portrait orientation.

**Comment by blueturtleai** [comment]
Would be really great, if this could be added in one of the next releases 🙏🏻.

**Comment by blackketter** [comment]
For video and images, even when view a web page in-app.  A little frustrating using the in-app browser when viewing links to YouTube, for example.

**Comment by Dimillian** [comment]
Will be fixed in the next version, the whole app will works in landscape on iOS!
