### ISSUE TITLE
Bug: After Boosting a post, the Bookmark option has become 'Unbookmark' blocking attmept to bookmark it

### ISSUE THREAD

**Issue by IanPatterson99** [Dimillian/IceCubesApp#246]
I use bookmarks quite a bit for posts I want to come back to , either to quote or read properly when ive time. there seems to be a bug linking the menu options for boomakr/unbookmark to boosting.
So I can bookmark / unbookmark fine if I've not alfready boosted the post. But if I've done that, the Bookmark menu option has become Unboomark - even tho it was never bookmarked, and so blocks the proper action. 
Attached is a snippet showing the area of the '...' menu concerned 
Thanks
![Screenshot 2023-01-21 at 20 56 23](https://user-images.githubusercontent.com/71190930/213886901-a0d9ab9c-513b-4a75-b60e-c941d2a0bdea.png)

**Comment by Dimillian** [comment]
Fixed in 1.0.5
