### ISSUE TITLE
Bug: Messages don’t work

### ISSUE THREAD

**Issue by pimoore** [Dimillian/IceCubesApp#250]
Clicking on messages (DMs) in the bottom bar brings up an error (retry doesn’t work).

![91F3EA8B-92FD-4FCC-8C93-94D0C615AD77](https://user-images.githubusercontent.com/5413470/213893957-a92232e9-0fe9-4f0c-9f1c-216e8d21af4b.jpeg)

**Comment by Dimillian** [comment]
Probably fix by 1.0.5, could you try?

**Comment by pimoore** [comment]
Unfortunately no, latest version still has the bug.
