### ISSUE TITLE
Bug: Laggy animation under profile view

### ISSUE THREAD

**Issue by Jerry23011** [Dimillian/IceCubesApp#255]
Under profile view, the refresh rate doesn't seem to be as high as the 120Hz or 60Hz displays could provide.
<img width="627" alt="截屏2023-01-22 12 32 59" src="https://user-images.githubusercontent.com/89069957/213900868-bfc7dad5-7162-4bc1-8bc9-cba43a02da01.png">

**Comment by Dimillian** [comment]
I've definitely noticed that too and I need to find out why.

**Comment by Jerry23011** [comment]
Thanks
