### ISSUE TITLE
Add translate option in the status context menu

### ISSUE THREAD

**Issue by Dimillian** [Dimillian/IceCubesApp#258]

**Comment by LorenAmelang** [comment]
Should this be in 1.3.7? I see it in the ... menu when the Translate option appears in the post itself, but not when it doesn't! 

At least in my timelines, I'd say maybe 10% of the posts with these Translate options are actually in a different language from mine. But way over half of the posts with a foreign language are _not_ recognized as such! Obviously posters don't understand the meaning of specifying the language they post in, not that of their home country...  

Could you please just make this Translate menu option appear for all posts? Or does it depend on the post origin instance settings? 

I have an option in my Share Sheet to translate with Mate, but somehow when used from IceCubes it can't recognize languages and produces gibberish even if I manually select them. Any idea why?
