### ISSUE TITLE
Dark theme background colors are flipped

### ISSUE THREAD

**Issue by firatciftci** [Dimillian/IceCubesApp#26]
When Nemesis Light Mode is selected, the background color of posts and pressable menu items in the settings screen are rendered `#ffffff`, with their surroundings rendered off-white. This is expected behavior. However, in Nemesis Dark Mode, the primary and secondary background colors don't follow expected behavior for Apple's theming guidelines. Specifically, the pressable menu items in the settings page should be `#1c1c1e`, and the color of the background view should be `#000000`, with the color of posts matching the background view's color this time around.

A good example for how this should look is the Settings app:
Settings (Light)            |  Settings (Dark)
:-------------------------:|:-------------------------:
![IMG_1558](https://user-images.githubusercontent.com/2052855/210435388-e827797d-1da0-43be-a809-c4109c2fdcc7.PNG)  |  ![IMG_1559](https://user-images.githubusercontent.com/2052855/210435396-b6613eb1-2ae6-4460-ac88-687dad192b8b.PNG)

Compare this with Ice Cubes's theming method:
Ice Cubes (Light)            |  Ice Cubes (Dark)
:-------------------------:|:-------------------------:
![IMG_1570](https://user-images.githubusercontent.com/2052855/210435889-a0900a79-95a9-4cd6-9d2b-a9561946358c.PNG)  |  ![IMG_1571](https://user-images.githubusercontent.com/2052855/210435891-afc4d2c1-1611-4bf8-ba3c-1b68b8e4f0fb.PNG)

Continuing on this, I would also love to see a "default iOS look" theme; given that the app is written using SwiftUI and greatly matches Apple's own design aesthetic, I think following [Apple's Foundations colors](https://developer.apple.com/design/human-interface-guidelines/foundations/color/) would make a lot of sense. I assume this could easily be added as two new theme options. More specifically, for the light theme, background color is `#ffffff`, secondary background color is `f2f2f7`, links are `#007aff`, and for the dark theme, background color is `#000000`, secondary background color is `#1c1c1e`, and links are `#0A84ff`. That said, it might be cool to see two dark modes, one regular and another AMOLED, as well.

**Comment by firatciftci** [comment]
Here is how the app looks with the proposed "default iOS look" themes:

Light Mode (Regular) |  Dark Mode (Regular) |  Dark Mode (AMOLED)
:-------------------------:|:-------------------------:|:-------------------------:
![IMG_1573](https://user-images.githubusercontent.com/2052855/210438313-fceeaa24-fc57-4315-8c68-bb46a62d21ee.PNG) | ![IMG_1580](https://user-images.githubusercontent.com/2052855/210438343-066bdf21-b4f7-4034-9282-fb84fcea3031.PNG) | ![IMG_1578](https://user-images.githubusercontent.com/2052855/210438330-a685cc7f-0223-4e3c-b9e8-f4dc57d927a4.PNG)

And the settings page (of course, as noted in the original post above, dark mode colors need to be flipped):
Light Mode (Regular) |  Dark Mode (Regular) |  Dark Mode (AMOLED)
:-------------------------:|:-------------------------:|:-------------------------:
![IMG_1572](https://user-images.githubusercontent.com/2052855/210438774-15a6544c-99c6-4b11-94ca-4e4a36fdba10.PNG) | ![IMG_1579](https://user-images.githubusercontent.com/2052855/210438798-4bf8be29-6952-4ffe-86e6-032c39e4f49b.PNG) | ![IMG_1576](https://user-images.githubusercontent.com/2052855/210438827-c80b6c2e-241c-4258-bfff-71f3aa192740.PNG)

For the regular dark mode, I am using `#1c1c1a` for the background color and `#2c2c2e` for the secondary background color.

**Comment by firatciftci** [comment]
Also, while creating this issue, I have stumbled upon another bug: while a light theme (i.e. a theme with dark text) is selected, if you change the background color to a dark one, the text stays dark, rendering everything unreadable. To fix it, you have to first pick a dark theme (i.e. a theme with light text) and then modify the colors.

I had Nemesis Light Mode selected and changed the background colors, resulting in the following:
![IMG_1575](https://user-images.githubusercontent.com/2052855/210439257-0b6b6845-5ea6-428f-903d-a835562aad39.PNG)

**Comment by Dimillian** [comment]
Quickly: the flip is actually a conscious design decision. I was wondering if anyone would comment on it haha.
