### ISSUE TITLE
Bug: View user profile in browser doesn't work

### ISSUE THREAD

**Issue by MichaelBell** [Dimillian/IceCubesApp#263]
Thanks for adding the view profile in browser option on the menu so quickly!

Unfortunately, it is not working for me.  It reopens the existing profile page instead of opening the user's profile page from their own instance.  I guess the app is recognising the URL as a user profile and handling it somehow instead of passing it to the browser.

The behaviour is the same regardless of whether the browser in the settings is set to In-App or System.

(Tested in v1.0.5)

**Comment by Dimillian** [comment]
oops, just fixed it, will be in 1.0.7, thanks!
