### ISSUE TITLE
Crash with contrived Twitter links

### ISSUE THREAD

**Issue by delfuego** [Dimillian/IceCubesApp#267]
When clicking on the contrived Twitter account links many people use on Mastodon, Ice Cubes immediately crashes. See the link in this post:

https://front-end.social/@leaverou/109732860961504484

Currently running version 1.0.6 on iOS 16.2; I saw this crash in 1.0.5 as well.

**Comment by henrik** [comment]
Perhaps a dupe of #102?

**Comment by Dimillian** [comment]
Yes
