### ISSUE TITLE
Feature request: Make language dropdown searchable by English language name

### ISSUE THREAD

**Issue by henrik** [Dimillian/IceCubesApp#268]
The language picker when composing includes e.g. “svenska (Swedish)” but the filter box only prefix-matches “svenska”; not “Swedish”. This felt unintuitive to me.

**Comment by vollkorntomate** [comment]
As of version 1.1.2, this seems fixed.
I can search for a language either in the native name of the language (Svenska) or the name in my app language (in my case: "Schwedisch").

**Comment by henrik** [comment]
Confirmed! Thank you ❤️
