### ISSUE TITLE
Bug: Multiple notifications per event

### ISSUE THREAD

**Issue by bazbt3** [Dimillian/IceCubesApp#270]
I'm getting between 3 and 7 push notifications per event, for every event, each with an entry in my phone's and watch's notification stack.

I've not attempted to figure out which type of event produces each quantity, but (for example) when your Ice Cubes account posts I get 5 (I've alerts set up for every toot), and a reply just now made 7.

Ice Cubes 1.0.6 and before, iPhone XS, iOS 16.2. (Apple Watch SE, watchOS 9.2).

**Comment by Dimillian** [comment]
Try to turn off and on your notifications in the app, I don't know why it suddently started to do that :/

**Comment by bazbt3** [comment]
Thanks. I slid the switch in the app, however it *immediately* turns back on every time I try - and I still get multiple notifications.

I think this is the fix you mentioned last time this issue happened.

One thing I've not tried is turning them off and on again in system Settings. I'll let you know.

**Comment by Dimillian** [comment]
Basically it's a server and you have X subscription that you all need to close 🤡 at some point it'll stop turning on. I'll try to work around this....

**Comment by bazbt3** [comment]
Thanks. That sounds easy. ;)

**Comment by frostyw98** [comment]
It did this to me today, too. I had been getting double notifications on liked toots. I tried to turn it off in the app, and it flicked on automatically. I did it a second time inside IC, and it turned off and stayed off. I then turned it back on. Now to wait and see if I continue getting duplicate notifications.
(If it's relevant at all, I have this app both on an iPhone and an iPad.)

**Comment by johncarney** [comment]
I've been seeing this on my iPhone, but Not my iPad. I wonder if it's related to the dropped account/inappropriate add account issue I've reported previously (#187)?
![image](https://user-images.githubusercontent.com/322950/213944914-e35ff492-3704-4719-8056-5b6d69931f9b.jpeg)

**Comment by bazbt3** [comment]
@johncarney Just to let you know I've not experienced issue #187, in fact I've had the same account through multiple TestFlight releases. I really wish I could recall when it started, but it's not the first time @Dimillian has had to figure out how to fix this.

One thing I've not tried, signing out and back in again. Or uninstall-reinstall.

**Comment by bazbt3** [comment]
@Dimillian I'm now occasionally getting **9** notifications with 1.0.8.

Is it possible that for every update I install it requests the push notification server to generate a new ID that somehow remains linked to me?

A complete guess of course, but if I get 10 any time after 1.0.9 arrives in the App Store I'll be very [redacted] 🤡

**Comment by Dimillian** [comment]
This is crazy. I'm sorry lol. I plan to investigate that next. I hope to find a local solution but I do think it's still a server issues. The only thing I know is that turning them off and on again fix it. Even if you have to hit the off toggle.... 9 times 🤡

**Comment by EmilJacobs** [comment]
I was about to open this same bug, heh. Glad it’s already on your radar!

**Comment by bazbt3** [comment]
User [workaround\* mentioned in this post by @fryto@mastodon@mastodon.social](https://mastodon.social/@Fryto/109751720286725184):

> "I managed to fix it. I removed the apps completely from my #iPhone and deleted the backup from #iCloud after which I reinstalled #icecube and backed up to iCloud And now everything works nicely"

I didn't go that far, but can confirm that uninstalling and reinstalling Ice Cubes 1.0.11 immediately dropped notifications to 1 per event. Yesterday. For me. I hope. :)

(Repeatedly turning off push got me down to 3, which was better than 9).

\*I say 'workaround': it's good that it works and there are few settings to remember after signing back into an instance, but I hope you can use this to figure out a permanent fix for ex-TestFlight users. (I'm *assuming* the issue carried forward into the App Store release).

**Comment by bazbt3** [comment]
@Dimillian The 'magic button' in version 1.1 has fixed this bug for me, thankyou. Would you like *me* to close this issue or do you have a system? :)

For anyone who needs this:    
Tap the account selector (user avatar top left) Settings > Accounts > choose account > Push notifications > Duplicate notifications fixer > 🪄Fix it.

**Comment by Dimillian** [comment]
Nice that it's working I was not even sure. It confirms the server (Mastodon) side issue then. Let's keep it open, I plan to auto fix it at app launch next.

**Comment by tarasis** [comment]
Oh thank golly! It's been slowly driving me crazy. I was up to 4 notifications per update on my Mac.

Just updated to 1.1 and applied the Magic Fix now to wait and see.

**Comment by tarasis** [comment]
Just noticed that while there was one notification on the Mac. In the app, there was marked 2 even though the list only showed one new notification.

**Comment by Dimillian** [comment]
This is fixed now.
