### ISSUE TITLE
Bug: additional local timeline broken on instances with v4.0.0rc4+glitch

### ISSUE THREAD

**Issue by willcohen** [Dimillian/IceCubesApp#273]
Example -- trying to add better.boston as a local timeline fails with "An error occurred while loading posts, please try again."

**Comment by EvilOne** [comment]
Other apps that I have that support this feature appear to be having issues with this instance. The apps get this response when trying to see the public timelines.
<img width="1113" alt="CleanShot 2023-01-22 at 09 52 55@2x" src="https://user-images.githubusercontent.com/169561/213925371-456c9acc-7b5b-49d9-86c0-3d077e33485b.png">

**Comment by patrickhoefler** [comment]
It looks like [better.boston](https://better.boston/) has disabled the public timeline, https://better.boston/public/local doesn't work either.

However, it works on other glitch instances, e.g. https://infosec.exchange/public/local

Here's the relevant [Mastodon commit](https://github.com/mastodon/mastodon/commit/225edac118634b146c1bbf45f199d8a1257bcf56).

**Comment by Dimillian** [comment]
Yep. I'll add better messaging, but the local timeline need to be public.

**Comment by willcohen** [comment]
Noted. Sorry for the confusion!
