### ISSUE TITLE
Bug: custom theme colors are reset after leaving the app

### ISSUE THREAD

**Issue by bwbuhse** [Dimillian/IceCubesApp#277]
I updated to v1.0.6 this morning and now any time I leave the app, my custom theming is reset. For example, I set my theme to Ice Cube Neon - Dark, change the tint color to blue, then go to my phone’s Home Screen. Next time I open Ice Cubes, the theme is reset to the default Ice Cube Neon - Dark.

**Comment by Dimillian** [comment]
It's not clear, but you have to disable follow system scheme for custom colors to be saved.

**Comment by Dimillian** [comment]
Will make it more obvious / automatic

**Comment by bwbuhse** [comment]
Gotcha, thanks! Will do On Jan 22, 2023, at 11:55, Thomas Ricouard ***@***.***> wrote:﻿
It's not clear, but you have to disable follow system scheme for custom colors to be saved.

**Comment by Bexxia** [comment]
@Dimillian will you be changing this so we can have custom accent colours when matching system light/dark?

**Comment by LauraLangdon** [comment]
> @Dimillian will you be changing this so we can have custom accent colours when matching system light/dark?

+1!
