### ISSUE TITLE
Bug: Timeline scrolling animation still not as smooth as it could be on iPad / macOS

### ISSUE THREAD

**Issue by TorsteinVin** [Dimillian/IceCubesApp#282]
When comparing scrolling performance in Ice Cubes to the official Mastodon app, Ice Cubes produces an occasional stutter in the scrolling animation on the "Home" timeline, while Mastodon is smoother and has fewer of the stutters, albeit some (It's not perfect either).

I know the app is in its early stages, and I don't want to nitpick, but I thought it'd be helpful to provide this feedback. Please see videos below for demonstration (it's subtle, but noticable when using the app in hand)

VIDEOS demonstrating the issue:
**Ice Cubes app**
https://www.youtube.com/watch?v=ILmqjVAPKso

**Mastodon app**
https://www.youtube.com/watch?v=5nAgdBiufNM

**Comment by jonikorpi** [comment]
As an additional data point: on my 12.9” iPad Pro (3rd gen) the stuttering is about 10x worse than in the video above, and happens in all timeline views.

**Comment by Dimillian** [comment]
Totally an issue with images on iPad and macOS, will look into it.
