### ISSUE TITLE
Feature request: Custom themes per account

### ISSUE THREAD

**Issue by jeffsikes** [Dimillian/IceCubesApp#285]
- [x] Search that this request don't already exist before creating it.

Something when you stop hammering out 5 updates a day and have some time on your hands.

It would be nice to apply a different theme per account.

Toot! has this option, although the UI there is much different - a background color is applied to the entire UI based on your current account.

There might be other ways to make this more apparent in the UI rather than theming.

**What is the purpose?** 
If you have multiple accounts it's just one more way to help you recognize at a glance which one you're logged into. Here's an example: Billy has a company / app that he promotes under @TheBestApp@BestApp.social and then a personal account at @billy@thegoat.com.  It's important for him to know which account he's posting from so he doesn't accidentally post his goat content on his company app.  This provides another layer of safeguarding as he can immediately identify the theme rather than looking for a profile icon.

And I just proved this would be helpful by accidentally posting this from my organizational GitHub account.  Wow.

**Comment by DirtyPeanut** [comment]
+1 to this request. A visual way to distinct which account is shown in addition to the small avatar would be much welcomed.

**Comment by RockyC36** [comment]
Plus 1 to this request. I have multiple accounts and I can’t tell them apart.

**Comment by Dimillian** [comment]
No planned.
