### ISSUE TITLE
Bug: No version information in app

### ISSUE THREAD

**Issue by ridmaur** [Dimillian/IceCubesApp#293]
Not a big one but could not find an about box, or something along the lines, displaying current version of the app.

**Comment by ScottChampagne** [comment]
If your app is updated, it shows on the settings screen.  ![image](https://user-images.githubusercontent.com/13421207/213941205-24bc7f6c-03c2-41ba-a95c-fd829a8367db.jpeg)

**Comment by ridmaur** [comment]
Yes, was on older version where it did not show. Will close issue.
