### ISSUE TITLE
Feature request: support timeline streaming

### ISSUE THREAD

**Issue by mattlqx** [Dimillian/IceCubesApp#294]
The Mastodon web app will stream new items via WebSocket as they come in if you are at the top of a feed. I'd like this for Ice Cubes instead of having to pull to refresh to get any updates. This is primarily useful when you have the app up on an iPad or Mac than an iPhone, but I'd very much like to use Ice Cubes instead of having a Mastodon web browser tab open all the time.

**Comment by Dimillian** [comment]
#91 It's planned as this feature. So closing this one. Thanks!
