### ISSUE TITLE
2nd Account signin gets error for Mastodon.social

### ISSUE THREAD

**Issue by davidakoontz** [Dimillian/IceCubesApp#299]
After multiple attempts to configure Mastondon.social account. Getting error. 

{"error":"invalid_client","error_description":"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."}

**Comment by davidakoontz** [comment]
![1D3B54E4-9653-4207-A6A6-53D05A9772D9](https://user-images.githubusercontent.com/3614419/213950263-bf0dcac4-aec6-49fb-878f-65f016851ad9.jpeg)
Did upload image work?

**Comment by Dimillian** [comment]
Closing as it's a server side issue, nothing much I can do about it :/

**Comment by davidakoontz** [comment]
Really nothing you could do?How about helping the person having the problem use your app!What should I do?David Koontz     Email: ***@***.***     (360) 259-8380     http://about.me/davidakoontzOn Jan 22, 2023, at 9:28 PM, Thomas Ricouard ***@***.***> wrote:﻿
Closing as it's a server side issue, nothing much I can do about it :/
