### ISSUE TITLE
Feature request: Remove Chat-GPT

### ISSUE THREAD

**Issue by jnozzi** [Dimillian/IceCubesApp#300]
Pleas remove support for ChatGPT. We don’t need to make it easy to add bot-like noise to Mastodon. 

At the very least, remove the “Emphasize” action as it allows you to enter a raw prompt as your toot and generate anything, unfettered. 

It’s irresponsible as a social media client feature.

**Comment by jnozzi** [comment]
Adding: I realize ChatGPT output can be pasted from anywhere, but a well behaved social media client shouldn’t be making it that easy for no reason to post bot noise.

**Comment by Dimillian** [comment]
🙄 It's not even ChatGPT, it's just some well targeted API Call to OpenAI API. I'll remove it if I feel like it. Thanks but no.

**Comment by Lundeful** [comment]
I feel like @Dimillian can use some logs and analytics to determine if/when the AI prompt is a problem based on how many use it/if some users are abusing it. Those that want to create bots will usually have system that scale better than using an in-app button like this. Even if they don't, and they script a usage of this feature in app, he will know pretty quickly if someone is abusing it.

Also his OpenAI bill would skyrocket, lol.

**Comment by Dimillian** [comment]
If I put metrics in this app track users in the app, I'll have this kind of shitstorm X 1000 lol. 
Anyway yes, the goal is not allow people to spam Mastodon with GPT generated text, it's there to help you correct your writing and yes the emphasise option is just a fun twist.

**Comment by Lundeful** [comment]
Yeah it would have to be anonymous and you'd only know that X amount of users is abusing it, not which users. Which also could be a shitstorm as you say. And again I'm guessing the billing for the AI would be the most scary part of it if that was allowed to happen at scale.

I think the feature is fun. I tried to generate some stuff but it does feel a bit weird to not use one's own words in public like that. Even though my own words are clearly less 'eloquent'.

I support you in not removing it!

**Comment by jnozzi** [comment]
It’s a disappointing response but it’s your show.

**Comment by bunnyhero** [comment]
> 🙄 It's not even ChatGPT, it's just some well targeted API Call to OpenAI API. I'll remove it if I feel like it. Thanks but no.

It's not ChatGPT yet you call it ChatGPT in the App Store description. Perhaps that should be updated, if nothing else.

Also, the privacy policy doesn't mention anything about connections to OpenAI.

**Comment by jaredcwhite** [comment]
I consider OpenAI a blight on the technology sector. Their ethics are woefully lacking and their products fundamentally at odds with the rights of online creators. Sorry to say this but I'm deleting Ice Cubes off my computer. Really disappointed to see this play out in this manner.
