### ISSUE TITLE
Feature request: stay in place after loading new posts

### ISSUE THREAD

**Issue by kilojarek** [Dimillian/IceCubesApp#306]
Hi,

when I come back to my timeline and click the "New posts" button, it takes me to the top of the feed. I would *much* prefer that after I click the "New posts" button, the feed would get loaded "ahead" of me but my position didn't change. I would like to stay in the same position in the timeline so that I could then scroll up to view the newly loaded posts in the chronological order. Hopefully it's not a big change to implement :-) Tweetbot used to do it so that I could load 50 newer posts at a time, each time rolled out ahead of me with a tap.

Unrelated comment: attaching other local timelines is a brilliant idea (is there some technical reason for why they couldn't be integrated with my local timeline?). Thanks for the good work!

**Comment by patrickhoefler** [comment]
Is this feature request different from #208?

**Comment by Dimillian** [comment]
Nop duplicate. We'll get there eventually.
