### ISSUE TITLE
Feature request: Keyboard Shortcuts for iPadOS

### ISSUE THREAD

**Issue by Jerry23011** [Dimillian/IceCubesApp#307]
I think it would be nice to support keyboard shortcuts for iPad users who have keyboards attached. For example, switching between navigations with ⌘1 / ⌘2, etc.
The feature that the system offers since iPadOS 15 can also be implemented - holding ⌘ to show all shortcuts.

**Comment by nmelehan** [comment]
➕ ➕ to this idea! I’d like to see up/down arrow keys scroll the timeline up and down. And maybe some way to navigate into a toot from the timeline with the keyboard (and back out to the timeline)

**Comment by digitalqualms** [comment]
Also, for macOS.
And, spacebar/shift+spacebar scrolling down and up. Arrow keys and j/k to move between posts

**Comment by Jerry23011** [comment]
Closing this since keyboard shortcuts are already featured on iPadOS

Longpress ⌘ in IceCubes to find them :)
<img width="1112" alt="image" src="https://github.com/Dimillian/IceCubesApp/assets/89069957/4d27b3f4-6dfb-44f9-9a73-76c4c4838d8a">
