### ISSUE TITLE
Links to posts on other mastodon instances should render in app, not browser

### ISSUE THREAD

**Issue by Mongey** [Dimillian/IceCubesApp#31]
When someone is doing a quote-toot, icecubes should open the link in-app.... like a normal post, rather than kicking you out to the browser.

post: https://mastodon.social/@siracusa/109628152513601215

example

<video src="https://user-images.githubusercontent.com/625787/210603568-b6859cfa-4bc9-49b9-8bc6-30061314f121.MP4" />

**Comment by Dimillian** [comment]
It is the case, do you have the example of a flow where it open in the browser? If I go to this status in app, and the click the link, it open in app.

**Comment by Mongey** [comment]
Apologies, I messed up the markdown for the screen recording, updated original opst

**Comment by Dimillian** [comment]
Is your user signed in on mastodon.social or another instance?

**Comment by Mongey** [comment]
I'm signed into another instance (@mongeyc@mastodon.ie 👋 )

**Comment by Dimillian** [comment]
Right, so if it can't resolve a local URL then it can't open it in the app. If those instances are federated it should works tho. Will take a closer look later.

**Comment by Dimillian** [comment]
Solved by @divadretlaw on #44
