### ISSUE TITLE
Feature request: Display Name options

### ISSUE THREAD

**Issue by lswee** [Dimillian/IceCubesApp#313]
In many old Twitter apps there was an option for how to display names.

Ivory has maintained this practice with 3 options:
Full Name (IceCubesApp)
Username (@icecubesapp@mastodon.cloud)
Both (IceCubesApp | @icecubesapp@mastodon.cloud)

This makes the timeline look a lot cleaner:
![7ea00d0809f13a6a](https://user-images.githubusercontent.com/40042240/214128498-06a71238-5b4a-4ee2-bee8-51051dfc0209.jpeg)
![a42cb31795ccce6d](https://user-images.githubusercontent.com/40042240/214128521-907b56c8-483f-4aa4-b660-d9adf7a5048b.jpeg)
![image](https://user-images.githubusercontent.com/40042240/214128443-0d025721-2f46-453b-835f-cb4ee483f61b.png)

**Comment by Dimillian** [comment]
Done

**Comment by lswee** [comment]
Woohoo! Many thanks.
