### ISSUE TITLE
Feature request: Haptics on Buttons

### ISSUE THREAD

**Issue by lswee** [Dimillian/IceCubesApp#315]
In Ivory, there are vibrations whenever a button is pressed, such as the ones in the tab bar, the new toot and search buttons, and when switching toggles in settings.

For whatever reason, it makes the buttons feel more physical and in my eyes, the app more premium. Like after turning on Haptics for the iOS keyboard, the device feels somewhat dead without it.

There is a vibration upon swipe-to-refresh in Ice Cubes, but the one in Ivory is stronger and nicer.

**Comment by Dimillian** [comment]
But we are not a premium app here, are we? Yes we are! I'll add that!

**Comment by lswee** [comment]
Thanks for doing this so quickly.

Are you given any options? Both Ivory's and Mammoth's haptics are a lot stronger.
