### ISSUE TITLE
Feature request: Follow requests

### ISSUE THREAD

**Issue by jdanthinne** [Dimillian/IceCubesApp#321]
I'd be happy to implement a follow requests screen (to approve or deny requests), but wondering where it could added…

**Comment by Dimillian** [comment]
I think the best place would be in your profile, followers screen? We could show a badge on it if there is requests? How do you they come? They can all just show up in notifications screen.

**Comment by Dimillian** [comment]
![image](https://user-images.githubusercontent.com/535509/214147989-c5e98cd8-67bb-4b8e-9985-f83a2d88796b.png)

**Comment by Dimillian** [comment]
It suppose to work already but not Suède we have an UI

**Comment by jdanthinne** [comment]
Suede?

**Comment by jdanthinne** [comment]
Here's what I've done. Seems ok for you?

https://user-images.githubusercontent.com/485107/214539134-fcd4c489-72c9-480d-8178-c34dddd29d6b.mov

**Comment by jdanthinne** [comment]
And of course, those buttons are also in the notifications.

![Simulator Screen Shot - iPhone 14 Pro - 2023-01-25 at 11 49 42](https://user-images.githubusercontent.com/485107/214544483-118d318f-6a02-4d1c-ac52-1e942950c003.png)
