### ISSUE TITLE
Feature request: Remove “ago” and use single letters for minutes, hours, days, etc. in Timelines

### ISSUE THREAD

**Issue by lswee** [Dimillian/IceCubesApp#325]
“2 hr ago” takes up more space than “2h”

“2 days ago” takes up a lot more space than “2d”

Does “ago” need to be reiterated for each post in a historical timeline?

**Comment by kalkwarf** [comment]
I would argue that without "ago," the time units don't have any context. Is space that much of a premium?

**Comment by lswee** [comment]
I’d say yes, but I do have a mini. I think unnecessary repetition in any interface adds clutter.

I’ve just had a look at the other similar apps I have installed and they happen to have “2h”:
Tweetbot/Ivory
Twitteriffic
Damus (Nostr)

Signal has “4m”

I don’t have Facebook, but on the AppStore I can see 8h in the screenshots. Same for the official Twitter app “1h”.

I imagine there’ll be examples where this isn’t the case, but one number, one letter seems to be fairly standard.

**Comment by Dimillian** [comment]
It's true that the bird app also do that. Will see

**Comment by Quarle** [comment]
The username line often breaks onto two lines (as in the attached image), so any space saved to prevent this would help to improve visual consistency in the app. (I wonder whether it would be better to put the time/date where the three dots context menu button is---the context menu can be accessed by a long press, so the button arguably isn't necessary in any event.)

![IMG_0696](https://user-images.githubusercontent.com/62277661/214498187-f9d28026-4668-4a02-a6d2-0df7b61047cc.jpg)

**Comment by lswee** [comment]
Good idea @Quarle

**Comment by tobiastom** [comment]
I also would like an option to hide the username completely. For me personally all this way more information I would want to see inside a timeline entry.
