### ISSUE TITLE
Bug: Ability to set unreadable tint colour (color)

### ISSUE THREAD

**Issue by lswee** [Dimillian/IceCubesApp#333]
Not sure if this is more a feature than a bug, and I’m sure you know this is possible, but it really doesn’t feel right that you can do this:
![52D81F88-849E-4826-B623-06F0FB1BEDF9](https://user-images.githubusercontent.com/40042240/214192541-d623002e-8efa-43ff-b4d6-84f83898033b.png)
![49439D71-B802-49B6-83AF-87B7B3F9FC1B](https://user-images.githubusercontent.com/40042240/214192623-54316aa4-1b7a-4c82-9492-ad759831d71b.png)

**Comment by Dimillian** [comment]
I mean, unless I restrict it to specific colors, I don't see what I could do.
