### ISSUE TITLE
Bug: Tapping outside of selector should close selector

### ISSUE THREAD

**Issue by lswee** [Dimillian/IceCubesApp#334]
In Timeline:
Tap Home (or arrow)
Tap somewhere other than one of the selections
Whatever you tapped will work like normal (open picture, go to Toot details), but tapping outside _should_ simply close/cancel the selection menu.

Same issue in the Notifications tab.

Also, would be nicer to have a larger tap target for invoking the drop-down menus in the first place as it’s sometimes hard to invoke.

**Comment by lswee** [comment]
Actually, same thing for three-dot menus.

**Comment by Dimillian** [comment]
I know, but we'll need a fix from Apple for SwiftUI for that :/
