### ISSUE TITLE
Bug: Linking to a URL with /tags/ in it behaves oddly

### ISSUE THREAD

**Issue by simonw** [Dimillian/IceCubesApp#339]
In this post here https://fedi.simonwillison.net/@simon/109742540974997768

I link to this page: https://simonwillison.net/tags/kellanelliottmccrea/

But clicking on that link in Ice Cubes doesn't take me to the page - instead it opens an in-app tag interface with no content.

https://user-images.githubusercontent.com/9599/214219807-6a69f7d3-4403-4a53-9059-8ae291d6f8a6.MOV

**Comment by simonw** [comment]
I think this code may be the cause of the bug:

https://github.com/Dimillian/IceCubesApp/blob/5b78e4657990316f6e127cf179f2d0786282e401/Packages/Env/Sources/Env/Router.swift#L64-L70

**Comment by Dimillian** [comment]
Just merged a fix for that at this right moment haha

**Comment by Dimillian** [comment]
https://github.com/Dimillian/IceCubesApp/commit/d0854d01075f15693e1d205b87871f076c25b8ef

**Comment by simonw** [comment]
Wow, quickest fix ever! Thank you.

**Comment by xurble** [comment]
I actually don't think my fix will fix this case.  As noted in the PR, this URL exactly matches the mastodon tags url structure, so even the new tighter test will hit this one.  It really needs to match on domain vs the users Instance domain as well.
