### ISSUE TITLE
Discussion: Floating Button for new Post

### ISSUE THREAD

**Issue by torre76** [Dimillian/IceCubesApp#357]
Hi @Dimillian,

just a though I had. 

I noticed that a lot of clients for Mastodon and event the Twitter official one have the "New Post Button" as a floating button on the lower right corner of the app.

Although it is against Apple guideline (the correct position is the one Ice Cubes has), I find this position very natural because I tap this button with the right thumb almost instantly.

So I was wondering what do you think about these choice...

**Comment by Dimillian** [comment]
Nah. We're staying on very basics component here. And Ivory is already doing it.

**Comment by torre76** [comment]
Ok!

**Comment by tomassliz** [comment]
@Dimillian I would love to have this floating button in the app as well. It's very useful in my experience. Plus it can be drawable to any corner of the timeline. It can be optional as well, but that's probably overkill.

I would love to implement it myself, but it looks like you have a very strong opinion against it, so I don't want to start useless work. For me, it doesn't matter that Ivory has it. There are so many apps which have it.

I think more people like me and @torre76 will appreciate the floating button. Buttons in the right upper corner are so hard to reach for me.
