### ISSUE TITLE
Bug: missing linefeeds in inbox

### ISSUE THREAD

**Issue by m4h4** [Dimillian/IceCubesApp#360]
In the inbox linefeeds that are in the original post are missing in the overview. ![image](https://user-images.githubusercontent.com/34862998/214429763-95e058e1-dd73-44ba-95f0-a04bb416cd66.png) should more look like this: ![image](https://user-images.githubusercontent.com/34862998/214429952-b74f9835-e67d-4f09-a946-542da24cc33c.jpeg)

**Comment by Dimillian** [comment]
You mean the formatting?

**Comment by m4h4** [comment]
Yes, I mean the formatting. The linefeeds do not appear in the preview, but they are essential. The preview can be shortened, but shouldn't leave out the linefeeds, because that makes it difficult to read.

**Comment by Dimillian** [comment]
Alright, I'll make the preview better there :)

**Comment by Dimillian** [comment]
This has been fixed in the latest version :)
