### ISSUE TITLE
Bug: iOS : Timeline refreshes and loses place 

### ISSUE THREAD

**Issue by raiderjr** [Dimillian/IceCubesApp#364]
First:  Thank you for the app. It's really great!

I read through existing issues, and didn't see this - so I am not sure if this is a bug or by design.  If its a dupe, sorry I missed the other...

On my iPhone, while reading the timeline - periodically the timeline updates or refreshes, and at that time it jumps up towards the top to the new items.  

This loses the place that I was reading.

On smaller or slower instances, its not a huge problem - but on a busier or more popular server it means I am constantly losing my place in the timeline and never really get to read all the posts.  Especially the Federated timelines which have way more stuff.

This may be by design, and if so I would suggest switching this to an enhancement request to provide an option to turn it off (the auto scrolling back to the top part - as the background refresh is fine, its the jumping around that is disruptive).

**Comment by Dimillian** [comment]
Duplicates but will get solved eventually.
