### ISSUE TITLE
Bug: scrolling the timeline is a bit laggish (slow)

### ISSUE THREAD

**Issue by andreagrandi** [Dimillian/IceCubesApp#368]
Hi, as you can see from the video I'm attaching, scrolling the timeline on my iPhone (it's an XR) is a bit laggish (slow). It also happens on my iPad Air (which should have a faster CPU).

I was wondering if it's just my own device being slow or if it's a known issue and you are planning to optimise it for the future.

Thank you so much 🙌

https://user-images.githubusercontent.com/636391/214501547-8871a485-aefa-48bb-95e3-1c72e6cce2e6.MP4

**Comment by Dimillian** [comment]
Will take another look at that, it's definitely not supposed to!

**Comment by hnk** [comment]
I seem to have the same issue, iPhone 12 mini running on iOS 16.3

I believe that this was introduced on my device with the last few updates? I have only been using the app for a few days but yesterday it felt noticeably more sluggish.

**Comment by vordenken** [comment]
I have the same problem but on an iPhone 13 Pro running iOS 16.2.
Does this app make use of the high refresh rate of the 13pro/14pro displays? On mine it definitely doesn't look like it.

If you need any additional information or help, let me know :) Awesome app already, keep it up!

**Comment by Jerry23011** [comment]
When I disconnect from the internet and scroll without any contents loading up, it feels smooth.
However, as soon as those posts or notifications show up, the animation starts to feel laggy.
Also, "Explore" and "Settings" view don't seem to have the issue after the contents are fully loaded on the iPad version.

Hopefully this helps, I feel the issue is the one last imperfection of Ice Cubes 💪🏻

**Comment by raduc** [comment]
I save the same issue on an iPhone 12 Pro Max running iOS 16.3. Hopefully the scrolling can be fixed.

**Comment by Dimillian** [comment]
I've made a few fixes that could help for the next release, let's keep track of it.

**Comment by pimoore** [comment]
Still seeing janky scrolling on 13 Pro, version 1.2 of the app.

**Comment by xurble** [comment]
Did this get improved again in 1.2.2?

Seems flawless now on my 13 Pro.

**Comment by pimoore** [comment]
Unfortunately I’m still seeing it on the same device. Not as bad as it was initially, but still perceptible.

**Comment by Jerry23011** [comment]
Still a bit laggy on iPad, especially under Profile view.

**Comment by Dimillian** [comment]
I have a few more things coming to make it even smoother.

**Comment by Jerry23011** [comment]
1.3 basically fixes this issue for me, but the Profile view still seems to be laggy as I mentioned in #255.

**Comment by raduc** [comment]
> 1.3 basically fixes this issue for me, but the Profile view still seems to be laggy as I mentioned in #255.

I can confirm the same. The home timeline scrolls smoothly now, also the scroll position indicator is not jumpy any more. The profile view is still a bit laggy for me as well.

**Comment by raduc** [comment]
One more thing I noticed recently is that the haptic feedback seems to create some lag in scrolling. Whenever the haptic feedback happens during scrolling to new posts, scrolling stutters a bit.

**Comment by raduc** [comment]
I don't know if it is a regression but it seems the home timeline in 1.5.0 stutters more than on the previous version.

**Comment by pimoore** [comment]
> I don't know if it is a regression but it seems the home timeline in 1.5.0 stutters more than on the previous version.

Seeing the same myself unfortunately, iPhone 13 Pro.

**Comment by Dimillian** [comment]
No waaaaaaaayyyyy

**Comment by pimoore** [comment]
I should point out the last few releases have had laggy timeline scrolling, some more prominent than others.

**Comment by kaiserkiwi** [comment]
Any progress here? Even on my iPhone 15 Pro the timeline lags pretty hard. I don't see this in any other app.

**Comment by justkutti** [comment]
Same here on my iPhone 14 Pro Max. The Timeline lags if you scroll.

**Comment by RayJW** [comment]
I think the recent updates definitely made it much better, but it still happens a little to me, to the point where scrolling for a long time almost makes me feel dizzy in a way. I think that's because it's so consistently when scrolling to a new post, so it's like in games where you have good FPS, but bad frame timing makes the stutters feel way worse than just constantly bad FPS. On the iPhone 13 Pro Max with iOS 17.2.1 by the way.

**Comment by jamwil** [comment]
It might be a bit of a placebo effect but changing the Status Media display to compact seems to have reduced the stuttering a little. Still noticeable, though. iPhone 14 Pro.
