### ISSUE TITLE
Feature request: tap top again to revert scroll to top

### ISSUE THREAD

**Issue by minrk** [Dimillian/IceCubesApp#374]
Timeline view has standard support for tapping the top (status bar?) to scroll to the top. Great! It's really nice when timeline apps (e.g. mastodon's own iOS app, Ivory, etc.) also support tapping the same spot again to scroll _back_ to where it was before that, giving an easy 'undo' for an accidental scroll-to-top.

**Comment by Dimillian** [comment]
Will get fixed eventually as spart of timeline position management, closing it right now because it's a duplicates.
