### ISSUE TITLE
Bug: Links from mastodon.macstories.net not recognized as posts

### ISSUE THREAD

**Issue by patrickhoefler** [Dimillian/IceCubesApp#375]
Links from https://mastodon.macstories.net/ are not recognized as Mastodon posts — no idea why though 🤷🏼‍♂️

## Example

https://mastodon.macstories.net/@macstories/109739929186959908

<img src="https://user-images.githubusercontent.com/547220/214547864-95295584-af5b-4c05-b4a1-04cbaf270ddf.PNG" width="300">

**Comment by Dimillian** [comment]
I wonder if they are federated. It's probably just a redirect. Will look but most probably nothing I can do.
