### ISSUE TITLE
Feature request: Opt-out of third-party AI service integrations

### ISSUE THREAD

**Issue by ezracelli** [Dimillian/IceCubesApp#388]
Similar request to #300 

Loving the Ice Cubes experience so far &mdash; responsive and beautiful!

As far as I can tell, third-party AI service integrations are implemented in at least two places: the little typewriter icon at the top of the "compose" screen, and automatic translations. I understand these functionalities may be a plus for some users, but I personally don't want to accidentally send any data to OpenAI, DeepL, or any other third-party service.

In my personal opinion, these integrations should be opt-in rather than opt-out. I think a sensible middle ground would be to provide an opt-out in the app's settings, or at least clearly indicate "This action will send data to ___, a third-party service." before the data is sent.

Thank you!

**Comment by Dimillian** [comment]
No data is sent. Just the text and only the text. In both DeepL and OpenAI, which is service I'm paying for. You can disable OpenAI in the settings, DeepL you simply can NOT click the button. Thanks. I have a privacy policy and it's valid.

**Comment by ezracelli** [comment]
Hi! Understood that only the text is sent — this is what I meant by “data”.

Apologies for not realizing there was already a setting for OpenAI! I was on app version 1.0.8. After upgrading to 1.0.11 I see the “Enable 🤖 helper” setting, which I’m assuming is what you’re referring to — perfect!! (With that said, without this discussion I don’t think I would have connected the dots that this setting disables the OpenAI integration but doesn’t affect the DeepL one. Maybe it would be good to add some “fine print”-type label there.)

As for DeepL — am I correct in assuming the “translation” functionality is the only place the DeepL API is called? If not, where else is it called? Maybe a better question is: **If there’s no way to completely opt-out of third-party AI services, can you provide a comprehensive list of all places in the app where third-party AI services might be in use?**

And regarding the statement about the privacy policy (which, referring to [POLICY.MD](https://github.com/Dimillian/IceCubesApp/blob/0f412ab309b56b7b177a00b85c44cbd8b8ddc551/PRIVACY.MD), doesn’t mention this topic): this wasn’t a legal concern but more of a philosophical one. I just don’t want anything to do with OpenAI and the like.

**Comment by Dimillian** [comment]
Then yes :) Nothing is sent ever to those services unless you tap those buttons. And BTW there is also a setting to hide the translate button.

I think is that I'll do is state that in the policy, make it clearer.
