### ISSUE TITLE
Bug: No vibrations in silent mode for notifications 

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#390]
When I receive notifications and silent mode is enabled (via the switch at the side), there are no vibrations. When I use the standard app, there are vibrations.

Not sure, if icecubes or the standard app works like intended 😀.

**Comment by blueturtleai** [comment]
No it just vibrated. Is it possible, that it only works, if the app is not in foreground?

**Comment by blueturtleai** [comment]
Now I’m sure, that it works like I wrote above: if the app is in foreground, it doesn’t vibrate. If in background, it does.

**Comment by Dimillian** [comment]
This is how iOS works, closing this one.
