### ISSUE TITLE
Bug: All Tip Buttons Animate

### ISSUE THREAD

**Issue by pohl** [Dimillian/IceCubesApp#392]
When a user selects a particular tip amount to make an in-app purchase, a throbber/spinner appears in all 4 tip amount buttons, rather than just the one that the user selected.

I imagine that only the specific one that was activated should animate. (The other 3 should probably become temporarily disabled until the transaction has been completed or cancelled.)

<img width="572" alt="Screenshot 2023-01-25 at 4 07 05 PM" src="https://user-images.githubusercontent.com/74958/214702453-4efef155-d91b-4bc2-a5dd-39181a3b7cfe.png">

**Comment by Dimillian** [comment]
Intended.
