### ISSUE TITLE
Bug: Un-gender the German translation

### ISSUE THREAD

**Issue by dertuxmalwieder** [Dimillian/IceCubesApp#398]
Not quite a bug, but room for discussion, I guess:

The German language does not have a "gender-neutral" word for "users", we usually use generic masculine nouns ("users" = "Nutzer", which is homonymic with "male users"). In recent years, a few attempts have been made to establish a neutral form, e.g. "Nutzer*innen" or "Nutzer_innen" or "Nutzer:innen", which adds the female ending "-innen".

Now the problem is that these disturb screen readers - using these forms would sound *weird*, to say the least, for severely visually impaired people. When doing https://github.com/Dimillian/IceCubesApp/pull/397, I saw that @vollkorntomate used one of the several "neutral" forms.

Personally, I would prefer to have "Nutzer:innen" corrected to "Nutzer", but I don't want to start an *edit war* on that. Just a suggestion ... :-)

**Comment by vollkorntomate** [comment]
As far as I know is VoiceOver perfectly capable of reading gender-neutral words like this. iOS even uses the same style with the colon (`:`), e.g. in the system settings.

But anyway, I don't have a strong opinion in either direction.

**Comment by jue89** [comment]
iOS VoiceOver pronounces the so called Glottisschlag, which is introduce by the ':', perfectly fine. From the POV, there's nothing to be fixed.

I'd recommend to keep it like it is - it explicitly includes non-maskulin people, whereas the "Generisches Maskulinum" does this only implicitly.

It may feels cumbersome to some people, as it arose during the recent years and may feel unfamiliar, but I'd say it's worth it. Language is always evolving. And if it includes people actively, it's a good development. Language is a tool and not art, that must be preserved.

**Comment by sothawo** [comment]
> we usually use generic masculine nouns

that's exactly what is the whole point of the gender discussion. Assuming that the masculine form is enough for all. There are many people who don't feel themselves addressed by this. So I would stick with the gendered variant.

**Comment by dertuxmalwieder** [comment]
Is anyone here who would *not* feel addressed?

**Comment by sothawo** [comment]
The question is not about people _here_. Developers are - alas - mostly male. It's about the users of the app. But I'll not discuss this further, sad it still comes up in 2023.

**Comment by dertuxmalwieder** [comment]
You claim that "there are many people who don't feel themselves addressed by this“, and I wonder how many of those use Ice Cubes. I mean, they'd probably show up here, right?

Suggestion: Let’s ask the affected users, not discuss this among us.

**Comment by jue89** [comment]
I would say the possibility that someone who's affected might use IceCube (I'm sure there are!) is reason enough to keep it in. Nobody's excluded by gender-neutral language - no harm is made.

**Comment by vollkorntomate** [comment]
Perhaps (in order to make everyone happy) we could add a setting if the user interface use gender-neutral language (default: yes). That way, users that are negatively impacted by some of the forms (or just don't like it) can turn it off.

Obviously, this would require some changes to the localization structure (I don't know if it's even possible), but would also benefit other languages that potentially have similar issues.

Either way, I think the current solution is perfectly fine, since VoiceOver supports it and it fits into the style of iOS.

**Comment by dertuxmalwieder** [comment]
The easiest way would be a setting to “just cut :innen from all strings”?

**Comment by jue89** [comment]
Or just use the English localization ... you can set the preferred language in the system settings.

A setting specific for just one language isn't justified IMHO.

**Comment by dertuxmalwieder** [comment]
Only one language behaves strangely though.

**Comment by umrath** [comment]
This is not a big, not even a request but someone not able to cope with a changing society that does not circle around males by default.

It is sad that we even have this discussion. But it would be crazy to assume that only progressive people are using Ice Cubes.

Please close this bug. There is nothing that needs fixing.

**Comment by dertuxmalwieder** [comment]
There is no reason to attack other participants as "not progressive" @umrath. Please respect the netiquette.

**Comment by umrath** [comment]
Why do you conclude/think that this was an attack?
It is merely a pretty solid statement without any judgement. At least I fail to see one.

**Comment by dertuxmalwieder** [comment]
You are implying that those who discuss the topic are "not progressive" and are "someone not able to cope with a changing society that does not circle around males by default". Please do not do that. Discussing people is not quite an inclusive, welcoming thing to do.

**Comment by jue89** [comment]
Any gender-neutral German language has been removed from Ice Cubes by now ...

* #489 changed all human-related words to alternatives that don't imply any gender (*users* turned into *profiles*) except for "Teilnehmenden" which is a little *hack* to create gender-neutral words without any unfamiliar sounding *:innen* postfix
* #597 changes those little *hacks* into the masculine nouns.

Basically, this discussion has been completely ignored and those PRs have been labeled as "updates".

I'm super sorry for @Dimillian that his awesome project has become a victim of this hidden edit wars that has been labeled as *translation help*.

And I'm also super sorry for all humans that don't feel included anymore by the German localization of Ice Cubes.

**Comment by dertuxmalwieder** [comment]
> And I'm also super sorry for all humans that don't feel included anymore by the German localization of Ice Cubes.

Still waiting for one. Please contact me.

I did not remove any :innen with a malevolent intent though. But yes, good catch.
