### ISSUE TITLE
Feature request: Medium size option under "Status media style"

### ISSUE THREAD

**Issue by Quarle** [Dimillian/IceCubesApp#399]
When using the "large" option for the "status media style" setting, images that are vertically long (such as phone screenshots) take up a lot of vertical space in the feed. A "medium" option that sets a max-height in addition to the max-width, scaling the image down to fit within the max-height bounds (and making it narrower than the max-width) or else cropping it to fit would be a nice option for those users who want media to appear larger than under the "compact" mode and smaller than under the "large" mode.

**Comment by vdbm** [comment]
The compact version crops the images. I would propose smaller versions of the full image.

**Comment by alexelgt** [comment]
I was going to request the exact same thing about adding a max-height. It’s gotten worse with version 1.5.6

**Comment by Dean151** [comment]
Implemented with 45765072257a0ba65e265de4316ffed9a9feb325

**Comment by Dimillian** [comment]
@alexelgt when you say it gotten worse. You mean on iPad & macOS?

**Comment by alexelgt** [comment]
> @alexelgt when you say it gotten worse. You mean on iPad & macOS?

I mean iPad. Compare one message between Ice Cubes, Ivory and the official app.

Ivory uses a max-height for images although is a little small in my opinion.

![2496B302-7CF8-434C-97C0-8AC6CAB72A04](https://user-images.githubusercontent.com/24291435/220723174-aade065c-4fe6-4f62-9d94-ebbcc62f70da.png)
![5B1EE010-2984-4D59-9D83-802B3F7FFAE5](https://user-images.githubusercontent.com/24291435/220723188-00a8f2fd-e7de-4775-a012-aa87f09a4ca3.png)
![9F7B532E-6CDF-45B4-841E-217EFA8AACB9](https://user-images.githubusercontent.com/24291435/220723192-a26025c4-a0d7-4ed1-94ee-0e41aec27698.png)

**Comment by Dean151** [comment]
@Dimillian @Quarle I think this issue should be closed now :)
