### ISSUE TITLE
After signing in, timeline page doesn't load

### ISSUE THREAD

**Issue by alombi** [Dimillian/IceCubesApp#4]
At first the Timeline worked, but after adding an account, the page is blank with the error: `the data couldn't be read because it's missing`. If refreshed, it says `canceled`.

**Comment by alombi** [comment]
Seems to be fixed in build 710!

**Comment by Dimillian** [comment]
I think it's random, most probably the server was under heavy load and sent back a 500. I'll do better error management so we'll see the true error.
