### ISSUE TITLE
Allow in-app browser to use reader mode by default.

### ISSUE THREAD

**Issue by ddimick** [Dimillian/IceCubesApp#400]
Would be a nice usability perk for those that prefer it.

**Comment by Dimillian** [comment]
#269 duplicate

**Comment by ddimick** [comment]
I'm not sure this is a dupe. I can see that there is an in-app browser available, and that I can click a URL that opens in it, and then I can click Aa and then Reader Mode, but I have to do that process every time I click a link.

The feature I'd like to see is Reader Mode is automatically enabled without me having to do all that for each link I click. If it's on 1.1.1 and I'm just missing it somewhere in the settings, I apologize.
