### ISSUE TITLE
Feature request: Load new posts without moving timeline to top

### ISSUE THREAD

**Issue by danielcarranza** [Dimillian/IceCubesApp#410]
Hi!, great work on the app and thanks for all the effort you're putting on it. 💪

I love opening the app in the exact same spot I left it last time, to continue reading. I'm one of those people who enjoy reading the whole timeline. I really appreciate the "load previous post" button for that, but it becomes cumbersome with a lot of unread posts.

If possible, a setting for the "load new posts" button where it doesn't move the timeline to the top, would be great for people who like to read the full timeline in a continuos manner.

**Comment by Dimillian** [comment]
Duplicate. In time it'll come.

**Comment by danielcarranza** [comment]
Sorry, I swear I really looked before posting 😅
