### ISSUE TITLE
Bug: The back arrow from a Trending Post or Suggested User goes to the Explore page

### ISSUE THREAD

**Issue by paspro** [Dimillian/IceCubesApp#414]
Suppose that you click on the Explore button, then go to the Trending Posts and click on "See more". As you browse the list of posts you click on one of these posts. If you then click on the arrow on the top of the page in order to return back to the list of Trending Posts, you return back to the Explore page and not the list of Trending Posts. 

The problem is that if you want to continue viewing the Trending Posts you have to start from the beginning until you find again the post you clicked to continue. 

The same happens when on the Explore page you select the Suggested Users "See more" option and then you click on a particular user. The return arrow brings you back to the Explore page and not the list of Suggested Users.

**Comment by Dimillian** [comment]
Will be fixed in 1.6.1
