### ISSUE TITLE
Bug: Scrolling toward top in Home timeline locks up for random seconds, maybe once in ~70 posts

### ISSUE THREAD

**Issue by LorenAmelang** [Dimillian/IceCubesApp#428]
Have used IceCubes on my iPhone SE2020 with iOS 16.2 for several updates now, and I keep seeing this. I know there is a lot of chatter about scrolling being laggy or sluggish or whatever, but I haven't seen any report quite like my issue. 

I read from old to new posts, so I've manually scrolled through everything new, back to my last timeline point. (Hope that save position issue gets worked out!) So I'm dragging posts down the screen, and occasionally there is a millisecond stutter or a jump of a few lines, probably what others see, no big deal. And then I hit a brick wall! Movement stops, at some random point in some random post. If I pull down, there is a momentary overlay of text lines on adjacent lines, and then a single image scrolls back upward exactly one line spacing. If I keep dragging, the single screen image chatters down one line space and immediately back up to the brick wall point. 

If I drag upward, I can go smoothly back in time as far as I want, but if I drag back down the brick wall remains. For some random time, even up to a minute or more. And then suddenly it is gone and I can keep reading. 

I have one possibly wild theory...  I'm at the far end of four 5GHz radio hops across maybe 25 miles. I average 15 mS latency to San Francisco fiber, but the possibility of dropped packets and retransmissions is unavoidable. If an update request disappeared into the ether, could the app scrolling lockup waiting for a retry and reply? Problem with that theory is it never (yet) happens while I'm flipping the screen upward and watching the rainbows slide across all the not yet loaded images. (How to find your past position...) 

But I do think it is checking for updates as I scroll toward newer posts...

**Comment by LorenAmelang** [comment]
Since I had my screen record button handy, there was no brick wall today. But I caught this, which looks like the first stage of the brick wall - the momentary overlay of text lines on adjacent lines. I tap the "Academic Sexism" CW line, it pushes space down for the content, and then the existing post text is overlaid on itself. But the user icon stays solid...  

https://user-images.githubusercontent.com/1297090/215202889-59dd56e0-a0e4-41f0-9920-6aa8427cc415.mp4

**Comment by LorenAmelang** [comment]
Finally caught a brick wall! Not the initial overlay of text part, but the long term chatter against the hard boundary. Stuck for over two minutes, but it all looked like this: 

https://user-images.githubusercontent.com/1297090/215289537-f8b536a7-b03b-4eb6-a048-0f3e47c1c2e5.mp4

Note there is no "n new posts" icon over the brick wall...  I'm sure it had been there for many minutes before the brick wall event. 

Here's the later static view of that post:

![iPhone-2023 01 28-10 48 08 000 static view of brick wall post](https://user-images.githubusercontent.com/1297090/215290051-9cf4d490-49ab-4eee-90cd-12a4398b66bf.png)

Don't know if time or switching to Explore and back unlocked it, but here's how close it was to the top of my timeline:

https://user-images.githubusercontent.com/1297090/215289624-1e87c753-c272-4003-aab5-6da621354bc0.mp4

Note that the brick wall post jerks as I scroll past it.  I'd say the brick wall post stutters about half the times I scroll past it now. 

And that the top Snowden post first shows "1 new post", but nothing is loaded by the spinner pull. 

My current theory is that this has something to do with "new posts" waiting. The brick wall seems to happen around the point where I've read most of what was loaded on my first refresh, but not quite all of it. And there are always way more new posts waiting than the number shown...

**Comment by Dimillian** [comment]
Thanks for all the research on this. Unfortunately I'll all go to Apple because it seems to be backed in the SwiftUI combo of container views I'm using :/ I don't know yet how to fix it without redoing a big part of the app. 

But I hope I'll find!

**Comment by LorenAmelang** [comment]
That's my experience with Apple - _so_ close to great but you just have to put up with one or two ridiculous design flaws. 

Ice Cubes is so far ahead of everyone else in all other ways! Maybe the universe is just telling me I need to take a break from Fediscrolling occasionally...  

If I can help at all let me know, otherwise I think I'll just stop obsessing here. Hope some solution appears!
