### ISSUE TITLE
Bug: there are visible lines (empty rows) in thetime line

### ISSUE THREAD

**Issue by andreagrandi** [Dimillian/IceCubesApp#431]
Hi, I noticed that often in my timeline there are some visible lines, those that normally are being used to visually separate a toot from another.
 
There are even 3 or 4 of them close together, just like in this screenshot

![image](https://user-images.githubusercontent.com/636391/215034849-f32661bf-da26-4711-88bc-8c5d773079ab.jpeg)

I was wondering: could it be because in that position there is some content which I have filtered out by using Mastodon filters?

Thanks

**Comment by Dimillian** [comment]
It's definitely that, will be fixed soon.
