### ISSUE TITLE
Feature request: Position of the "create new toot" and "config" buttons

### ISSUE THREAD

**Issue by PauloCarrasco** [Dimillian/IceCubesApp#434]
Search that this request don't already exist before creating it.
I think it would really improve one hand usability if both icons changed positions (see attached image). The config button is not used so often and can bee at the top of the screen. The "Create new toot" would be more functional if positioned in the middle of the bottom menu bar.

![IMG_1181](https://user-images.githubusercontent.com/1708828/215054738-3c6516d4-913f-446b-b7fd-6e322d0ab361.jpg)

**Comment by Dimillian** [comment]
The app already changed since, but will think about some diff placement for the new post button.
