### ISSUE TITLE
Bug: Skip filtered posts when loading the next post in the timeline

### ISSUE THREAD

**Issue by sothawo** [Dimillian/IceCubesApp#458]
Let's assume in my timeline I have the display that there are 5 new posts and assume that the next 2 ones which I cannot yet see are filtered posts. I then have to tap the _next post_ 3 times to see the next relevant post, 2 times to load the filtered ones - which are not displayed after that nice fix in #431, the only hint I see is that the count of posts remaining is decreased - and the third tap to get the next unfiltered post.

Would it be possible in reaction to that button to load the next post that filtered posts are skipped?

**Comment by phpmacher** [comment]
@sothawo is this still happening on the newest version?

**Comment by Dimillian** [comment]
We should close this one. It's the timeline looping bug.
