### ISSUE TITLE
Bug: Push Notification don't work at all for me

### ISSUE THREAD

**Issue by andreagrandi** [Dimillian/IceCubesApp#460]
Hi, as you may remember I reported this bug a few times on Mastodon, but I would like to report it here so I can provide you more details and keep track of any possible change/improvement.

## Context

Some Mastodon user sends me a reply. I have notifications set like this:

![IMG_3B5375F847ED-1](https://user-images.githubusercontent.com/636391/215252096-103eea17-2f9c-484a-a67d-ab25269bc1f1.jpeg)

## Expected outcome

I open Ice Cubes client and I expect to see the bell icon with at least the number "1" on it, to indicate I have a new notification for a reply

## What happens instead

When I ope the client, I see that there are new posts, but I can't see any number on the bell icon:

![IMG_8992](https://user-images.githubusercontent.com/636391/215252280-aa4c7e15-a165-4741-8992-8cd2a9c61534.PNG)

## Troubleshooting

I would like to understand if there is something wrong with either:

- my account
- my iOS system settings (note: I keep system notifications disabled for social clients, but this only prevents an app from opening a notification in my locked screen or in the notification area, it doesn't prevent apps from showing notifications in app. For example with Ivory I see all the expected notifications)
- my network: **do you use any particular server to subscribe to push notifications?** I use NextDNS and I want to check if any of the services you may use is being blocked by one of the lists.

I'm willing to make some tests as needed. I'm confident that if I'm the only one so far to have reported this issue, it may be related to a specific issue with one of the things above (or something similar which I may have forgot).

Thank you so much

**Comment by Dimillian** [comment]
If you have push notification turned off, you won't get any icons in the app. This is the way it works for now.

**Comment by Dimillian** [comment]
For now Ice Cubes rely on push notifications for managing unread badge. This is not planned to have another way of doing it at this point.

**Comment by andreagrandi** [comment]
> If you have push notification turned off, you won't get any icons in the app. This is the way it works for now.

they are off in the system settings but they are on inside the app. I just switched on in system settings too and see if they work this way, thanks!
