### ISSUE TITLE
Bug: changing app icon reverts to the default one

### ISSUE THREAD

**Issue by andreagrandi** [Dimillian/IceCubesApp#465]
Hi, in the latest (1.1.3) version of the app (I'm sure it was working before because I could change it without any issues) when I change the default icon to something else, after I go to the iOS home, the icon is reverted to the default one.

I'm attaching a video to show what happens:

https://user-images.githubusercontent.com/636391/215256261-0cda6ddf-2585-46e4-9922-9a09994840df.MP4

**Comment by Dimillian** [comment]
This is an old iOS bug :/ just reboot
