### ISSUE TITLE
Bug:Crash when default language is not English

### ISSUE THREAD

**Issue by fanyu** [Dimillian/IceCubesApp#466]
If default language is not English, app will crash when launch.

**Comment by Dimillian** [comment]
Are you sure? What language do you see the app doing that? I'll fix it ASAP

**Comment by Dimillian** [comment]
I've tried Chinese and the app is running.

**Comment by Dimillian** [comment]
CC @Jerry23011 @nixzhu does your app crash in the latest version when used in Chinese?

**Comment by nixzhu** [comment]
No crashes in the latest v1.1.3

**Comment by Jerry23011** [comment]
> CC @Jerry23011 @nixzhu does your app crash in the latest version when used in Chinese?

mine works fine.
iPadOS 16.3
Ice Cubes 1.1.3

**Comment by Dimillian** [comment]
Thanks, maybe it's an older version of a different configuration then.

**Comment by fanyu** [comment]
[crash.txt](https://github.com/Dimillian/IceCubesApp/files/10526942/crash.txt)
