### ISSUE TITLE
Toolbar Buttons on Account Details View not always readable

### ISSUE THREAD

**Issue by divadretlaw** [Dimillian/IceCubesApp#47]
Currently the Back Button and the ellipsis/more/menu is not always readable, depending on the account header.

![Now](https://user-images.githubusercontent.com/6899256/211212140-91a8dfaf-6a60-4fd2-b762-4fc3aaef23f3.png)

One way of dealing with that would be copying what Twitter does

![Twitter](https://user-images.githubusercontent.com/6899256/211212194-8292cdf0-c302-47b7-a8ef-b4be84f0d88b.png)

```swift
Image(systemName: "ellipsis")
  .imageScale(.small)
  .foregroundColor(.white)
  .font(.body.weight(.semibold))
  .frame(width: 30, height: 30)
  .background(Color.black.opacity(0.5))
  .clipShape(Circle())
```

or similar but better integrated into the theme of the app.

Overriding the system back button with `.navigationBarBackButtonHidden(true)` disables the swipe-back gesture, but that can be re-enabled via UIKit, like this

```swift
extension UINavigationController: UIGestureRecognizerDelegate {
    override open func viewDidLoad() {
        super.viewDidLoad()
        interactivePopGestureRecognizer?.delegate = self
    }

    public func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
        return viewControllers.count > 1
    }
}
```

but maybe there are better/different solutions to this issue

**Comment by Dimillian** [comment]
I would love to avoid having a custom back button. But yes I found the same issue as you, hard to read depending on the background. It is mitigated because the bar show up as soon as you scroll. Don't have clear solution yet, that is not overly complicated.

**Comment by Dimillian** [comment]
FYI I'll add a black mask to the image
