### ISSUE TITLE
Bug: Notification grouping doesn’t work as expected 

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#477]
A post was starred two times within 2 minutes. As expected, both notifications were grouped together. The same post was starred about 30 minutes later but the notification wasn’t grouped with the other two notifications. I expected, that it would be added to the existing group.

Does it work like designed or is it a bug?

**Comment by Dimillian** [comment]
It's work as designed, it's group only subsequent notifications for now.
