### ISSUE TITLE
Bug: Ability to change icon missing on the Mac

### ISSUE THREAD

**Issue by lolbat** [Dimillian/IceCubesApp#484]
Ice Cubes on the Mac has been missing the ability to change the app icon for the last few versions. 

Or the setting was moved and I am not smart enough to see it :-)

**Comment by Dimillian** [comment]
It's not possible on macOS unfortunately, it's an iOS API

**Comment by vordenken** [comment]
Oh noooo... 
I am so used to my changed icon on iOS that I keep looking for icecubes on Mac till I see that it has a different icon...
Is there no way to change them without the api?

**Comment by vdbm** [comment]
For now you can do it manually: open Finder, and click Cmd-I on the app name, then drag the new icon onto the very top of the window that popped up (see screenshot with changed icon)
![Screenshot 2023-02-11 at 15 58 51](https://user-images.githubusercontent.com/39005353/218265530-4c1f5e39-1804-4637-8d2e-42195e783214.jpg)

**Comment by jamrolu** [comment]
Ivory allows this - it's a bit of a hack, as it only takes effect when the app is running - and it reverts back to the default when the app is closed.
![CleanShot 2023-10-31 at 14 17 21@2x](https://github.com/Dimillian/IceCubesApp/assets/32819428/d0ce2448-5abd-4ba4-ae9f-3996ef2db6c0)
