### ISSUE TITLE
Bug: Moving Cursor in Compose View by Holding Space Causes Cursor Flickering

### ISSUE THREAD

**Issue by swotam** [Dimillian/IceCubesApp#487]
When composing a new post and holding Space in order to freely move the cursor to edit text, the cursor starts flickering and often appears as a duplicate. This makes moving the cursor using this method more difficult and is visually annoying.

To duplicate: compose a new post and then long press / hold on Space to enable the ability to freely move the cursor. The cursor will begin to flicker as you move it around, and a duplicate copy of the cursor will often appear at the position it was at prior to holding Space.

Issue has been present in all released versions of the app to date.

**Comment by Dimillian** [comment]
Duplicate, but will get fixed!
