### ISSUE TITLE
Scrolling past (muted) video stops system audio

### ISSUE THREAD

**Issue by m4p** [Dimillian/IceCubesApp#49]
If you e.g. listen to Music or a Podcast and scroll past a video in your timeline audio stops. Ice Cubes should probably use AVAudioSession.mixWithOthers while autoplaying a muted video.

**Comment by m4p** [comment]
Iirc you should be able to do the setup once on AVAudioSession.sharedInstance.

**Comment by Dimillian** [comment]
Should be fixed in next upcoming TestFlight, let me know (re open) if not.

**Comment by m4p** [comment]
Can confirm this is fixed. Thanks!
