### ISSUE TITLE
Bug: scrollbar position indicator jumps around

### ISSUE THREAD

**Issue by edrozenberg** [Dimillian/IceCubesApp#491]
When scrolling the timeline, the current position indicator (inside scrollbar on right side), jumps around randomly, up and down - currently this indicator is distracting as it keeps jumping around, and does not indicate anything useful.

**Comment by Dimillian** [comment]
Will not be fixed until Apple do something in SwiftUI.

**Comment by edrozenberg** [comment]
Understand thanks, don't know enough about SwiftUI compared to I guess UIKit which other apps (Ivory etc) might be using to get good results with this.
