### ISSUE TITLE
Feature request: Open Mastodon links directly in the app

### ISSUE THREAD

**Issue by Havhingstor** [Dimillian/IceCubesApp#497]
If a toot links to another toot and I click on the link, that other toot isn't opened in IceCubes, but in the integrated browser.
I suggest that mastodon links are automatically detected and opened in the app. Alternatively, it may be an option to allow the user to copy just the link, so that the toot can be searched for.

**Comment by Dimillian** [comment]
I'll close this one because it's already the case unless the Toot can't be found locally. Which can happen with the current state of the API unfortunately
