### ISSUE TITLE
Feature request: British English

### ISSUE THREAD

**Issue by arheh** [Dimillian/IceCubesApp#498]
It would be great to have British English added to localisation. If I knew how to do it I would.

**Comment by Dimillian** [comment]
I do think maintaining 3 English versions for a side project is a bit too much for myself. If anyone is up to do it feel free.

**Comment by Jerry23011** [comment]
> It would be great to have British English added to localisation. If I knew how to do it I would.

I think this [Documentation](https://developer.apple.com/documentation/xcode/adding-support-for-languages-and-regions) from Apple will help you, but feel free to ask me for help setting up the files if you don't know how.

**Comment by jpanther** [comment]
I tried with #297 but it was closed without merging. I personally find it really jarring seeing American spelling all over the place, especially in an app like this where "favorite" pops up frequently.

**Comment by Bexxia** [comment]
I too would be very grateful for British spellings. Favorite is particularly annoying - wouldn't be so bad if it was perhaps changed to Starred, like elsewhere in the app?

If I can do anything to contribute spellings, please ask and I'll be happy to help. I just have no clue about writing code, sorry.

**Comment by Jerry23011** [comment]
I started a new PR to add British, if anyone would like to take a look and review that would be great.

**Comment by EvilOne** [comment]
@Dimillian Should be able to close PR merged.
