### ISSUE TITLE
Bug: Pasted text has white highlight in dark mode

### ISSUE THREAD

**Issue by merelister** [Dimillian/IceCubesApp#500]
Pasted text has a white highlight that makes the text unreadable when using a dark mode theme. After pasting text, anything you type afterwards will also have the white highlight. 

![B3EEE7B6-FC65-4F68-B184-F0C70F348DD8](https://user-images.githubusercontent.com/24901233/215290544-8309f543-3adc-4931-81b3-81ef31ebac2b.jpeg)

**Comment by Dimillian** [comment]
It's a duplicate and will get fixed
