### ISSUE TITLE
Bug: Crash when tap on post's reply

### ISSUE THREAD

**Issue by splaGit** [Dimillian/IceCubesApp#505]
ice Cubes version 1.2 on iOS 16.3

When I tap on a post with replies then tap on one of the replies, the app crashes when I get back to the main thread.
![5AF02E3A-9B6C-4020-AFDA-AB6452C4EA68](https://user-images.githubusercontent.com/115372672/215311221-c37eb210-f7e5-46f9-95f3-369beffe90f6.jpeg)

**Comment by splaGit** [comment]
See this [video](https://videos.mastodont.cat/w/pqrwRfHuYWceyXsmvuFNbJ)

**Comment by praveenchandran1** [comment]
This issue is more frequent than I experienced before. Same issue with the iPad version as well.
