### ISSUE TITLE
Bug: sharing UI is truncated on iPad

### ISSUE THREAD

**Issue by Stooovie** [Dimillian/IceCubesApp#507]
When sharing to Ice Cubes from the Action menu, the UI is truncated so the Post button isn't in view. 

![767D5F6B-05DE-4C79-9C63-05E1B6DB24C7](https://user-images.githubusercontent.com/10572373/215320248-9a6f4ffb-ea8d-4ba3-96e5-9f5e88e5245f.png)

IC 1.2.0 ipados 16.2

**Comment by Jerry23011** [comment]
I can reproduce, both in landscape and portrait view.

iPadOS 16.3
Ice Cubes 1.2.0
