### ISSUE TITLE
Multiple Account Management - Add discerning labels/avatars to selection list dropdown

### ISSUE THREAD

**Issue by jeffsikes** [Dimillian/IceCubesApp#51]
When you have multiple accounts with the same name there is no way to discern which account is which.

Considering adding one or more of the following to assist in the selection process:

* The acct name (box464@mastodon.social, box464@moth.social, bot464@botsinspace) in a smaller font below the display_name
* The related account's avatar image beside the display_name

![IMG_0912](https://user-images.githubusercontent.com/6627582/211396632-31aba4d8-a735-4411-aade-adac185b61b8.jpeg)

Good luck with the rollout!  This definitely isn't a show stopper, just had a minute and thought I'd submit it.

**Comment by Dimillian** [comment]
I actually will do a custom popover I think, like Ivory, with custom row showing the avatar etc...

**Comment by Dimillian** [comment]
<img width="250" alt="image" src="https://user-images.githubusercontent.com/535509/211471543-1203d56f-1ecb-4277-9feb-7c38e05293be.png">

**Comment by jeffsikes** [comment]
I would expect to see the smaller account name under the full name, like below, but having it there in any form solves the issue. Thanks for the quick response!

---------------------------------
**IceCubesApp**
_@icecubesapp@mastodon.cloud_
---------------------------------
**Thomas Ricouard**
_@dimillian@mastodon.social_
----------------------------------

**Comment by Dimillian** [comment]
Ah yes, would be even better, will change it soon.
