### ISSUE TITLE
Bug: Keyboard Shortcut description for composing new posts missing on catalyst app(macOS)

### ISSUE THREAD

**Issue by enviousjag** [Dimillian/IceCubesApp#512]
**Bug**: 
The keyboard shortcut "cmd + n" is not displayed in the menu of the macOS catalyst app. 
While the shortcut cmd +n works, the hint isn't displayed I can still create new posts via this shortcut. 

**Expected behaviour**
Show the shortcut to create a new post greyed out like the other shortcuts. 

<img width="254" alt="image" src="https://user-images.githubusercontent.com/117439432/215326828-3722cd9a-b3ab-4230-b7e7-5eb4bde37730.png">

**Comment by Dimillian** [comment]
I'm closing for now, nothing I can do, shortcut is there, but if I add it in the menu, the app will crash.
