### ISSUE TITLE
Bug: Cannot delete account after moving it to another instance.

### ISSUE THREAD

**Issue by jyrgi66** [Dimillian/IceCubesApp#517]
**Precondition:** Logged in with two accounts on different Mastodon instances.
**Action:** Move one of the accounts via the standard account move procedure to another instance.
**Issue:** The account that has been moved leaves an empty account entry in the IceCubes app. This empty entry cannot be deleted within the app.

**Comment by Dimillian** [comment]
You can swipe to delete :)

**Comment by jyrgi66** [comment]
Yes, swipe helps 👍 thanks for the prompt reply.
