### ISSUE TITLE
Feature request: Swipe actions?

### ISSUE THREAD

**Issue by palaniraja** [Dimillian/IceCubesApp#52]
Swipe action on post for quicker way to Bookmark / Favorite?

**Comment by Dimillian** [comment]
This is not Ivory here :)

**Comment by palaniraja** [comment]
Respect your decision, but swipe to fav is not tweetbot/ivory or twitter client only feature

e.g Apollo for Reddit or any todo apps offer a swipe to quickly perform a frequently used action. Hence my request 


And also for a moment i thought i reported ivory bug here 😂 since like everyone else i also beta test and report like half a dozen mastodon apps
