### ISSUE TITLE
Feature request: Follow account from Profile view

### ISSUE THREAD

**Issue by darrinsmart** [Dimillian/IceCubesApp#520]
(I'm really excited about this app now that I can use it with by GoToSocial instance)

One minor issue I've noticed: When I see a interesting post, I'll often want to follow that account. My intuition is to click through to their profile page and be able to follow from there.

But I can't see any follow option in Ice Cubes. Perhaps it could be added to the context menu on that view? Or maybe a standalone button in its own right (I guess this is what I was familiar with when using Metatext). I suppose it would be a multi purpose button, with "Unfollow" and "Cancel Follow Request" depending on the state of the follow request.

Related: In Metatext, I could long press the user's handle and copy it, which was really handy when I would find someone to follow in one account, copy the handle, and follow it from a different account. Something like that would be useful in this app, maybe with the copy+paste mechanism or even an explicit menu item ("Follow with...").

<img width="735" alt="Screenshot 2023-01-29 at 11 54 29 AM" src="https://user-images.githubusercontent.com/1310620/215352328-01f7a03a-c6b9-47b7-a9f3-2bfa09ee6422.png">

**Comment by EvilOne** [comment]
With the latest version of the app, you should be able to see a follow button when tapping into the details of a post. This is what I see:


https://user-images.githubusercontent.com/169561/215356357-77eb5445-0fdf-469b-9468-6a51949cb57c.mp4

**Comment by darrinsmart** [comment]
Thanks for adding that video @EvilOne. You're right - I see the button with my mas.to account, but it is missing when I use my GoToSocial account. Looks like another client/server compatibility issue. I'll have a look into this and report back.

**Comment by darrinsmart** [comment]
Following up: It turns out it was failing because `/api/v1/accounts/:id/featured_tags` is not yet implemented in GoToSocial. Ice Cubes was receiving a 404 response and failing to complete fetchAccountData().

I suppose one could argue for making the client more robust. But at the same time it will just work once the server implements the whole API. Personally I am happy for this to remain closed.

I've reported this and suggested an interim server-side workaround: https://github.com/superseriousbusiness/gotosocial/issues/1419
