### ISSUE TITLE
Feature request: Why is an M1 chip required?

### ISSUE THREAD

**Issue by AnID-Aux** [Dimillian/IceCubesApp#522]
I would like to run the app on my Mac. I am currently using MacOS 13.2
Unfortunately it can't install it because apparently an M1 chip is needed which I don't have. Is that a bug or is it supposed to be like that?

**Comment by EvilOne** [comment]
The app at this time isn't a native Mac app. Instead, it runs the iPad version of the app, which requires an Apple silicon chip (M1, M2). You can see more technical info about this in another issue, #320.

**Comment by Dimillian** [comment]
Maybe one day I'll do a native macOS app, but for now it's just the iOS app with some runtime tweaks.
