### ISSUE TITLE
Bug: account.followers is not translated to Catalan

### ISSUE THREAD

**Issue by splaGit** [Dimillian/IceCubesApp#525]
There a is mistake in https://github.com/Dimillian/IceCubesApp/blob/main/IceCubesApp/Resources/Localization/ca.lproj/Localizable.strings
Var says "compte.followers", must be "account.followers"
![012994D4-0E77-44A4-A954-5FA6B0B59247](https://user-images.githubusercontent.com/115372672/215359609-9a7a6671-0f6d-4f47-a638-6b3a25103a66.jpeg)

**Comment by EvilOne** [comment]
@Dimillian, this appears to be fixed. It should be safe to close.
