### ISSUE TITLE
Bug: Profiles that have a transparent .gif as their avatar do not render in Ice Cubes

### ISSUE THREAD

**Issue by 9p4** [Dimillian/IceCubesApp#527]
For example, the account https://mastodon.social/@dlx has a transparent square where the profile picture ought to be. I can confirm that the image does appear in the official app.

@robb (owner of the account)

**Comment by robb** [comment]
FWIW, I've seen it appear *sometimes* – if I had to guess, I would assume it's the fact that this is a non-looping gif? 🙃

**Comment by Dimillian** [comment]
I have fix but it's require @robb and friends to stop putting weird GIF as their Avatar. So I guess it's not gonna happen. 🙃

**Comment by robb** [comment]
I think I did try an animated png first but Mastodon wouldn't let me?

**Comment by Havhingstor** [comment]
> FWIW, I've seen it appear _sometimes_ – if I had to guess, I would assume it's the fact that this is a non-looping gif? 🙃

Static gifs should now work with the newest version of nuke (see #304, #759).
Your avatar still doesn't seem to work though, so i guess there's another cause.
