### ISSUE TITLE
BUG: iPad share sheet text goes off screen

### ISSUE THREAD

**Issue by bmbufalo** [Dimillian/IceCubesApp#528]
L
![DC8BE7F3-18D7-4E5B-B9C6-816F6BA4B6B4](https://user-images.githubusercontent.com/15007937/215384541-cb0920e6-adc3-4cae-8649-fc81d1cb0035.jpeg)

**Comment by Jerry23011** [comment]
Hi, this is the duplicate of #507, and it's fixed [dbb8bd2](https://github.com/Dimillian/IceCubesApp/commit/dbb8bd2a3d5186cc9c7228ecbd316f5c02ac3eae)

**Comment by Dimillian** [comment]
I'll close it as it's fixed in 1.2.
