### ISSUE TITLE
Bug: Button-bar is not shown when reading local timeline

### ISSUE THREAD

**Issue by Havhingstor** [Dimillian/IceCubesApp#533]
The favorite / boost / reply / save and share buttons are not shown in the local timeline of another server, I have to open the toot and its replies when I want to favorite or boost it.

**Timeline:**
![IMG_0013](https://user-images.githubusercontent.com/59767224/215458626-b39637fb-dd95-459c-a81d-6aef5152611e.PNG)

**Toot alone:**
![IMG_0014](https://user-images.githubusercontent.com/59767224/215458643-3810cafc-2d0a-4d44-a701-b9fa10e97e08.PNG)

**Comment by Dimillian** [comment]
Closing as it's the normal behaviour. Each Toot need to be imported and it only happen when you tap on them.
