### ISSUE TITLE
Bug: Image gallery in posts doesn't maintain ordering

### ISSUE THREAD

**Issue by martimlobao** [Dimillian/IceCubesApp#535]
When tapping on media with an image gallery, selecting a photo and swiping left or right shows images in an arbitrary order, which also changes each time you close the gallery and re-open it. 
https://user-images.githubusercontent.com/6430786/215510579-9009586b-0a15-475d-b118-e291bb88120e.MOV

**Comment by Dimillian** [comment]
If you're up to date it's supposed to be fixed. Can you confirm.

**Comment by martimlobao** [comment]
Looks like it's working as expected in the latest version. Thanks!
