### ISSUE TITLE
Feature request: Remember Timeline position

### ISSUE THREAD

**Issue by palaniraja** [Dimillian/IceCubesApp#54]
Remember timeline position so user can scroll to read newer posts

**Comment by bazbt3** [comment]
Seconded. Please forgive me if this comment fragments this a bit but I hope it's all related.

Recent updates have stopped scrolling to the latest post *every* time I open the app, but I'd prefer my timeline position is recalled even after iOS manages resource, and after force-closing and TestFlight updates.

I like the 'new posts' indicator and the button to step through newer posts one-by-one (as an aid to calmness) but for me it's not for substitute for simply scrolling after a period away.

Would it be possible to have the new posts & step-ahead button at the bottom of the screen - for easier reachability? I realise adding a top or bottom user option grows the menus but it's probably time, approaching the App Store release.
