### ISSUE TITLE
Feature request: Add option to adjust how new posts are loaded/displayed

### ISSUE THREAD

**Issue by umrath** [Dimillian/IceCubesApp#543]
When new posts are there, tapping the information loads those and jumps to the top of the timeline.

It would be great to have the ability to change the behavior to load the messages but not jump to the top but stay abtue current position in the timeline.

**Comment by kwlorenz** [comment]
That's a really missing feature...

**Comment by Dimillian** [comment]
It's being worked on + it's a duplicates :)

**Comment by umrath** [comment]
Oh, I'm sorry.
I searched but couldn't find it.
