### ISSUE TITLE
Bug: Unable to log out after transferring to another instance

### ISSUE THREAD

**Issue by BeauNouvelle** [Dimillian/IceCubesApp#548]
Currently Ice Cubes ends up failing to load when an account transfer has occurred. 
Upon opening the app, things will continue to load forever with no available mechanism for logging out.

Reinstalling the app does not resolve this issue.

Suggested solutions:
1. Close sessions when the app is re-installed and force login. Can be achieved with a User Default flag.
2. Make log out button accessible even when nothing is loading.

**Comment by Dimillian** [comment]
Swipe to delete the account. It'll make it better later;

**Comment by BeauNouvelle** [comment]
Profile page doesn't even load. Is there any way to detect if an account transfer has occurred? I wonder if it's possible to figure this out in the app, then just present the onboarding again.

I'm not even sure if building this myself, then attempting to wipe the keychain manually will fix it. Haven't worked with it enough to know if it's paired with a dev account.

I guess I can still build and run it until a fix comes out if thats the case.

**Comment by Dimillian** [comment]
It's touchy, I'm super careful with the keychain. But I think whipping the account on a 401 should be ok. But on big instances like Mastodon.social can return 401 sometimes when just signed in and it resolves by itself on the next few queries.

Detecting account transfer should be doable too, the account query should have some data in the JSON I hope.
