### ISSUE TITLE
Feature request: Differentiate direct messages more strongly in the Home feed

### ISSUE THREAD

**Issue by pwinn** [Dimillian/IceCubesApp#553]
You're already showing a different icon for direct messages, so you know they're direct messages while building that list. It's still deeply disconcerting to see them appear in the Home feed just like public messages, and have only that tiny icon to let me know I didn't accidentally post semi-private things publicly. (Yes, I know DMs aren't *truly* private, at least from instance owners.)

Could those posts have a colored background and be indented, like they are in the Direct Messages conversation view? At least *something* to make them stand out and be immediately obvious they're DMs. 

Thanks.

**Comment by theotherlinh** [comment]
Agreed. This should also be different from general mention highlights as well. Ideally just another optional color.
