### ISSUE TITLE
Bug: Timeline is initialised twice on startup

### ISSUE THREAD

**Issue by xurble** [Dimillian/IceCubesApp#555]
Once by the TimelineViewModel setting the timeline, which seems fine and then again by the TimelineView on the change of scenePhase to active.
 
I can't find a need for the scenephase one.  Taking it out and some superficial testing backgrounding and reactivating the app suggests it's not needed, but I don't know if there's a special  case you had in mind.

However it goes to the network twice, so getting rid of one of these would speed startup.

**Comment by Dimillian** [comment]
It've already optimised quite a big on this lately, will check why this still happen. 

The background phase is useful to refresh the timeline when you come back from background.

**Comment by xurble** [comment]
It used to do it 3 times before your big change to lists so it's already improved.
