### ISSUE TITLE
Bug: “You boosted” displaying when someone else with the same username on a different server boosts

### ISSUE THREAD

**Issue by simonmaddox** [Dimillian/IceCubesApp#558]
If you username is @firstname@example.social and you follow @firstname@example.org, Ice Cubes shows boosts from the other person as “You boosted”.

it contains the other person’s avatar, and tapping that label takes you to the other person’s profile.

Screenshot attached, showing my avatar and the person with the same name. I’ve also confirmed that they haven’t changed their name to “You” 🙂

Using app version 1.2.2

![C55FB9F7-006B-4D03-8CEF-959FC93FAA41](https://user-images.githubusercontent.com/34273/215706322-eb2a3f3f-f341-4a1b-9572-73d5ac52d48a.jpeg)

**Comment by Dimillian** [comment]
Crazy bug haha

**Comment by simonmaddox** [comment]
Wow, that was fast! Thank you 🙂
