### ISSUE TITLE
Feature request: Improve new post notification indicator view. 

### ISSUE THREAD

**Issue by PrajeetShrestha** [Dimillian/IceCubesApp#565]
In the timeline view whenever there is new posts, currently there is a new post indicator view which is just a plain text like: "14 new posts". I would also like to add small circular avatar of first few people who posted. 
I found the feature very useful in other apps. Please refer screenshot. 

![screen](https://user-images.githubusercontent.com/8730910/215804449-8f5ea422-db51-4121-a613-9c635ea71cf2.png)

I am planning to implement it. Let me know if it's a good idea. 
And also can you give me some pointers on where it is implemented in the codebase?
I see localized string resource for the message: **timeline-new-posts %lld**, but the string resource is used no where in the code except the localized files. 
I also can't see any view code which looks similar to highlighted view in current implementation (left of the screenshot).

**Comment by Dimillian** [comment]
It's actually completely reworked for 1.3.0 (current main) and will show only a count of unread of the right. So while I like the Twitter indicator it's probably will not happen at this point.

**Comment by PrajeetShrestha** [comment]
![IMG_8747](https://user-images.githubusercontent.com/8730910/215822981-b785649f-6d1f-4086-963b-b634febe21be.PNG)
I will think of more creative design if you agree LOL :D

**Comment by Dimillian** [comment]
Wow. I like it lol. Quite a bit. But, this need to be an option with a default off. "Social new posts indicator".

**Comment by PrajeetShrestha** [comment]
On it.
