### ISSUE TITLE
Bug: Handles wrapping to second, or third line

### ISSUE THREAD

**Issue by Fastidious** [Dimillian/IceCubesApp#567]
I have seeing handles wrapping to a second, and third line. I will look for the one wrapping longer and attach. See screenshot. 

![Handke wrapping](https://user-images.githubusercontent.com/8352292/215836989-982c392a-d4ad-448e-b29f-fd7f978c675b.jpeg)

**Comment by Fastidious** [comment]
That overflow to the second line happens more often than expected. Maybe doing elipses on handles?

**Comment by LorenAmelang** [comment]
I'm on the other side of this issue - I _really_ like seeing the full handle, even if it takes more lines on my tiny iPhone SE2020. Maybe an option to limit them or not? Worst case, limit them in the timeline but show the whole handle in detail views and replies? I've seen apps that limit them differently in each view, and make it impossible to find out the full handle and instance. Sometimes you need it!

**Comment by Fastidious** [comment]
@LorenAmelang I understand what you are saying. There are ways to shorten it, then make it visible on a different screen. Or perhaps prearranging things to make them fit better (for example, that little globe at the end, is it needed? The “3 days ago”, can’t it be “3d”?). The way it is right now it isn’t aesthetically pleasant.

**Comment by LorenAmelang** [comment]
Not to argue...  Just to present the issue more vividly...  I actually like seeing the full handle, even in my timeline. For people I know well their icon is enough, but for all the new boosts seeing their full name and full instance tells me important clues about them. And helps immensely in recognizing them if they appear again, or searching for them. Likewise the globe icon reveals it is a public post, not a private reply. 

I'd actually love to be able to see the actual date and time of the post - but that's probably even more space than “3 days ago”...  

Maybe we could have more options in the Settings panel: 

Limit post identifying data to one line - no/yes
(If limited)
    Show full name, truncate instance then date - radio button
    Show full date, truncate instance then name - radio button

Date format: 
    "n hours/days ago" - radio button
    "yymmdd:hhmm" - radio button
    "month day year, hours:minutes" - radio button

(Yes, I'm a data nerd...)

**Comment by henrik** [comment]
I’ve been thinking about what feels more polished in Ivory - this is one thing. They have the globe on the details view but not the list view.

That seems reasonable to me - “DMs” already get special treatment and the rest seems like a fairly obscure detail that is OK to put behind a second tap (into the details view)?

They also show a more compact relative time: “5d” instead of “5 days ago”. I think that is a good trade-off as well.

**Comment by Fastidious** [comment]
This was solved in 1.5.5, with the option to hide the server name from the username. If you enable that, bye bye overflows. Closing.
