### ISSUE TITLE
Bug: Home timeline is scrolled automatically 

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#570]
When I scrolled the home timeline to the top and a new post came in, the new post was added at top and the timeline was scrolled a bit to top. Imo this is pretty irritating and shouldn’t happen. The timeline should only be scrolled manually or automatically by tapping on the new post counter.

I’m using v1.3.

**Comment by Dimillian** [comment]
For now this is the behaviour, if you're pinned to the top, and using the app (the app is in foreground) the posts will be streamed in. Will probably add a setting later but not for now as I want to test it out more

**Comment by blueturtleai** [comment]
Okay. Tbh, I liked it more like it worked before: just indicate, that there are new posts and I can decide myself when I want to load them.
