### ISSUE TITLE
Bug: Need to be able to Like Direct Message

### ISSUE THREAD

**Issue by RobATX** [Dimillian/IceCubesApp#571]
There is only a reply icon/action available on DMs. Need a Like icon as well. Thanks.

**Comment by RobATX** [comment]
Don't see it. ![image](https://user-images.githubusercontent.com/31712535/215867461-0b006ac0-c86f-4338-8e23-dbeeddbdeffd.jpeg)

**Comment by Dimillian** [comment]
Ah you need to be inside the conversation.

**Comment by RobATX** [comment]
When I tap on the response, it takes me to another screen with the response. I have to them tap to view detail. Then I get the action options. That's a huge pain.

**Comment by RobATX** [comment]
Never mind. I see it. Tap and hold on bubble. 👍
