### ISSUE TITLE
Bug: Submitting a quote post still scrolls to top of timeline?

### ISSUE THREAD

**Issue by LorenAmelang** [Dimillian/IceCubesApp#575]
Love the timeline performance in today's new version! 

But...  I did a quote post of a reply to a post in my timeline, and after I sent it my timeline scrolled to the top to show it. Regular posts and all other actions preserved my reading location. 

I hope once the timeline position is saved and synched, the Home button can alternate between newest and last read...

**Comment by Dimillian** [comment]
1.3.1 should have fixed that. But yes, if you"re on the top, new posts get streamed in.
