### ISSUE TITLE
Bug: Incorrect rendering of post

### ISSUE THREAD

**Issue by pmonks** [Dimillian/IceCubesApp#576]
[This post](https://cinematheque.social/@12pt9/109786219724322016) is not being rendered correctly, as shown here:

![image](https://user-images.githubusercontent.com/54865/215903846-dd773481-e5b8-4df3-8c32-ab55e3bb2687.jpeg)

Note: other clients I checked render it correctly.

**Comment by Dimillian** [comment]
@xurble Do you have an idea? It's probably not your change but just the current lib failing at converting the HTML. I sax that from time to time.

**Comment by xurble** [comment]
Just looking at the post, the first thing that jumps out is that the html is malformed. It truncates in the middle of an open anchor tag. 

Could that be it?

**Comment by xurble** [comment]
Looking at the thread, there's mention of zero width joining characters. I'll try and take a look this evening. 

I'd actually like to take another crack at the markdown generation.

**Comment by EvilOne** [comment]
This has been happening before any of @xurble changes. Is there an issue rendering due to EmojiText?

**Comment by EvilOne** [comment]
Here is one that I bookmarked a long time ago that has an issue displaying -> https://newsie.social/@jeff/109716493698039652

It renders like this:

<img width="50%" src="https://user-images.githubusercontent.com/169561/216196327-9f1fc267-34d3-4562-86d6-0c3b6ff66ecf.png">

**Comment by xurble** [comment]
FWIW the zero width joiners were breaking HTML2Markdown

**Comment by EvilOne** [comment]
Nice find!

**Comment by sothawo** [comment]
Are there different kinds of zero width joiners? This screenshot show that my post  is rendered correctly, there is a zwsp between "#tag" and "s" 

![image](https://user-images.githubusercontent.com/8456476/216320499-bff9db0e-5140-4f40-b452-f237cdf49618.png)

**Comment by sothawo** [comment]
Addition: I enter it as a unicode character, not as an html entity

**Comment by xurble** [comment]
Can you post the url for the screenshotted post please?

**Comment by sothawo** [comment]
https://digitalcourage.social/@sothawo/109795642095913757 new one, the original was not (only visible for me)

**Comment by sothawo** [comment]
well, it didn't break the current version - and did not break previous ones, I use always use this when I have pluralized tags.

**Comment by xurble** [comment]
@sothawo 
Your working zero width is (hex) `80 8B`
The breaking one is `E2 80 8D`

I don't know why HTML2Markdown chokes on one but not the other.

**Comment by xurble** [comment]
This can be closed, it's fixed
