### ISSUE TITLE
Glitch with the Visibility button when the keyboard moves

### ISSUE THREAD

**Issue by scalbatty** [Dimillian/IceCubesApp#58]
The Visibility menu button is being vertically offset after the keyboard has moved at least once.

This is easily reproducible in simulator by toggling the hardware keyboard on and off (see attached video), but also happens on device after you leave the photo selector screen.

Looking at the code the culprit might be the fact that it isn't a regular SwiftUI button but a `Menu`, and something strange definitely happens within the convoluted view hierarchy SwiftUI creates for that.

https://user-images.githubusercontent.com/520924/211566059-d15332ae-5aa1-4522-aff2-60a8900556a5.mp4

**Comment by Dimillian** [comment]
Yup, I know about it and unfortunately, without removing the direct menu access (it could be a button with a contextMenu) I don't see how to fix it :(

**Comment by Dimillian** [comment]
But feel free to propose a solution, even if it change the current UX

**Comment by scalbatty** [comment]
Found a related SO question about this: https://stackoverflow.com/questions/73996685/swiftui-add-menu-in-safeareainset-cause-strange-layout-issue

**Comment by Dimillian** [comment]
Interesting, I'll try to play with the frame.
