### ISSUE TITLE
Feature request: Timeline: restore the selected timeline at the next startup

### ISSUE THREAD

**Issue by nekolaboratory** [Dimillian/IceCubesApp#581]
It feels a little inconvenient that the selection of tabs on the main timeline is initialized at startup.
I want to keep the selected kind of timeline.

**Comment by jsynowiec** [comment]
Perhaps related to #561?

**Comment by alper** [comment]
I don't see how this is done. The thing that's preventing me from using Icecubes as a daily driver is to have Home open on the same list that I left it if I start the app.

**Comment by alper** [comment]
Is there an open ticket tracking having a List as your starting timeline?

**Comment by nekolaboratory** [comment]
I have never seen it, I guess.
