### ISSUE TITLE
Feature request: Menu icons inconsistent on iPad

### ISSUE THREAD

**Issue by sknobcat** [Dimillian/IceCubesApp#588]
OK, this is pretty nitpicky and OCD, but practically no two icons have the same line weight. Other than making people like me uncomfortable, it makes the UI seem less polished than it could be… 
![DEA68AF9-98F4-4FF3-9902-48E07D0DB779](https://user-images.githubusercontent.com/122608094/216064306-7b62de78-d195-48cf-b787-d286615e6137.jpeg)

**Comment by Dimillian** [comment]
Duplicate, on it.
