### ISSUE TITLE
Bug: post on home timeline scrolled out of view

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#590]
While reading the post at the top of the home timeline a new post came in. The new post was added at top and the home time line scrolled to top so I couldn’t read the post I were reading anymore.

When adding new posts at top automatically this should happen non  intrusive. 

Why are new posts now added automatically and not like before only on demand?

**Comment by Dimillian** [comment]
This is a conscious decision for when the timeline is scrolled to the top. Definitely not a bug. The old behaviour was completely removed.
I'll keep this open to take feedbacks on this new behaviour.

**Comment by blueturtleai** [comment]
Hm. But you understand that it’s annoying when you just read something and this is suddenly scrolled out of view?

**Comment by Dimillian** [comment]
I do but the web works the same when scrolled to top. And I do like it. If I'm at the top if means I'm ok to read more posts. Will see later to adjust it.

**Comment by blueturtleai** [comment]
I'm okay to read more posts, but I’m not okay, that the post I currently read is scrolled out of view. I really like your app, but this is a bad user experience.

**Comment by blueturtleai** [comment]
As it seems to work as designed, I close this issue.
