### ISSUE TITLE
Bug: Updating not possible

### ISSUE THREAD

**Issue by mkonia** [Dimillian/IceCubesApp#593]
Since a few days the update in the App Store is no longer possible for me.  Deleting the app and then reinstalling it via the App Store is also not possible. My current version is 1.2 (1071). Version in the App Store: 1.3.2

Also irritating is that the App Store says that the app is not verified for macOS. Cf. screenshot:

<img width="540" alt="Ice Cube" src="https://user-images.githubusercontent.com/15304151/216149936-78ec4750-c797-4edf-b03e-4548138cbc53.png">

**Comment by Dimillian** [comment]
I would say reboot?

**Comment by mkonia** [comment]
Thanks for the hint. However, this did not solve the problem.
<img width="1155" alt="Ice Cubes" src="https://user-images.githubusercontent.com/15304151/216285836-363d230c-83c6-4192-acd4-b7694de20be0.png">

**Comment by mkonia** [comment]
Finally, I was able to solve the problem with the help of Tinker Tool System, namely with the function "App Store Update". The description of this function reads: 

> Resolve Issues with the App Store Update Feature
The App Store application often fails, suggesting updates which have already been performed. You can reset the list of pending updates for the current user or all user accounts, which will remove the incorrect update notifications.
