### ISSUE TITLE
Bug: Getting "An error occurred" when trying to view 'floss.social' as remote local timeline

### ISSUE THREAD

**Issue by akyrtzi** [Dimillian/IceCubesApp#598]
I added https://floss.social as remote local timeline but it shows me "An error occurred" when trying to view it.
Another instance that I added works fine, so it seems there's something specific to 'floss.social'.

App version is 1.3.2

**Comment by Dimillian** [comment]
The local timeline is probably behind a login, not public. I'll add better messaging.
