### ISSUE TITLE
Feature request: Add Open Dyslexic font

### ISSUE THREAD

**Issue by markrprior** [Dimillian/IceCubesApp#599]
It might be appreciated if you add the Open Dyslexic font to the fonts available, either by simply adding it to the list or by making it a specific option so that it is more obvious. Toot! for example has it as a specific option but noting its availability may be enough to improve accessibility. See [https://opendyslexic.org/](https://opendyslexic.org/)

**Comment by Fastidious** [comment]
Can’t it be installed by the user as a custom font?

**Comment by markrprior** [comment]
> Can’t it be installed by the user as a custom font?

I can't see a way of doing that in the iOS app. The custom "Timeline Font" option is a list of fonts to select from rather than a way to add one. In any case you want to make it easy for a non technical user to be able to use it rather than make them jump through hoops.
