### ISSUE TITLE
Bug: tap on new post counter doesn’t scroll timeline

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#603]
Tapping on the new post counter does no longer scroll to the first new post in the home timeline. 1.3.3.

**Comment by jsynowiec** [comment]
Perhaps a duplicate of #121?

**Comment by blueturtleai** [comment]
Could be. But for me it looks like it was introduced with 1.3.3 as I didn’t have the problem before. I leave the issue open for now.

**Comment by Dimillian** [comment]
For now the indicator tap does nothing it's excepted.

**Comment by blueturtleai** [comment]
Okay. Due to the constant changes, it’s pretty hard to tell what is intentionally and what not 😀.

**Comment by Dimillian** [comment]
Don't worry, it'll get ironed out. 1.4.0 is in the works and the idea is to have a final behaviour on the timeline position management and state restauration.
