### ISSUE TITLE
Feature request: customize haptics

### ISSUE THREAD

**Issue by rolandleth** [Dimillian/IceCubesApp#604]
Haptics was a great addition, but it would be nice to have a setting to turn them off, preferably individually for different features. For example, haptics on buttons or when loading the feed are really nice, but I find haptics when scrolling new posts to be _such_ a nuisance and I'd love to turn it off 🙁

**Comment by phpmacher** [comment]
yes, a configuration-option would be nice.

**Comment by kieranjarrett** [comment]
Agreed l to me the haptics feel unnessary (especially on scrolling through posts). Options to control where they occur would be fantastic.

**Comment by Dimillian** [comment]
This will come next week. It's next on my list

**Comment by Dimillian** [comment]
Will be in 1.4.0

**Comment by rolandleth** [comment]
Awesome, thank you! 🙌🏻
