### ISSUE TITLE
Feature request: different style menu icons

### ISSUE THREAD

**Issue by Ruchbah** [Dimillian/IceCubesApp#605]
On the iPhone, despite the size of the bottom menu bar being the same as other clients, the icons feel "heavier". Maybe no need to go super stylised as Ivory, but probably smaller, or removing the labels (Timeline, Notifications, etc.) might give a better "identity" to the app.

**Comment by nekolaboratory** [comment]
I've made a pull request(#669) for this feature request.

Please close this issue when it is merged and you are satisfied with the results :]

**Comment by henrik** [comment]
The option to hide labels has been released.
