### ISSUE TITLE
Bug: Profile view often stuck on placeholders

### ISSUE THREAD

**Issue by jsynowiec** [Dimillian/IceCubesApp#607]
Since one of the last updates, the profile screen now is often stuck on the placeholder, initial state, and it does not load. Switching tabs does not help. The only thing I found working for me is to force-kill the app and relaunch. This does not look like an instance issue because I can use it just fine with other web or mobile client apps.

Version 1.3.3

<img src="https://user-images.githubusercontent.com/1029142/216290222-b55b1f9e-4d21-4389-8993-032ff6bbb799.PNG" width="240" />

**Comment by phpmacher** [comment]
@jsynowiec Do you have the impression that happens particularly often with some instances?

Because I haven't had this problem yet.

Which iOS version do you use?

**Comment by Dimillian** [comment]
It's probably due to instance outage. I'll close this one.

**Comment by jsynowiec** [comment]
Like I mentioned in the first post, this does not look like an instance issue. I can interact with the instance just fine using other web or mobile client apps like Elk, Ivory, or the default Mastodon web client. Moreover, this happens randomly with two instances I use, so this looks too much of a coincidence. However, I had this only a few times, so it might be hard to identify the exact conditions.

I'm using iOS 16.3
