### ISSUE TITLE
Bug: After waking up from energy saving, the timeline is reset 

### ISSUE THREAD

**Issue by dertuxmalwieder** [Dimillian/IceCubesApp#609]
So this just happened: I put my iPhone aside, had a good night of sleep, I took my iPhone, it still had 100% battery and Ice Cubes had forgot its timeline position.

**Comment by Dimillian** [comment]
If the app is killed it'll not restore position for now.

**Comment by dertuxmalwieder** [comment]
It is not really *killed* - it is hibernated in the background from what I understand.

**Comment by ixs** [comment]
Observing this as well. Force killing the app but also switching back to the backgrounded app after a while means the app starts at the last recent pay on the timeline, forgetting the previous position of last read toot.

**Comment by Dimillian** [comment]
For now the app is not supposed to restore position if it was killed in the background or manually. But I'll come eventually.

**Comment by dertuxmalwieder** [comment]
This seems to be fixed ... faster than I thought!

**Comment by chlndh** [comment]
With the latest version in the App Store it is still not working. Before closing it would be good if the link to the fix is added here.
