### ISSUE TITLE
Bug: Custom emojis not shown

### ISSUE THREAD

**Issue by EmilJacobs** [Dimillian/IceCubesApp#611]
My instance has a few custom emojis, but when clicking the custom emojis button in a new post, I get no emojis at all, let alone my custom emojis.

Bonus (really an enhancement request I think?): that button should really show all regular emojis as well.

**Comment by pjolt** [comment]
Tried the new post emoji button on fosstodon.org, mastodon.social, social.vivaldi.net and they all work and seem to also display each instances custom emojis as expected.  

Also tried moth.social (instance of Mammoth app) and i don´t get the (new post) emoji button with IceCubes. 
Official Mastodon app (1.4.10 build 252) shows the emoji button but is stuck on loading circle and never displays emojis. And checking Mammoth app, it has option for custom emoji but currently there is no emojis there at all just a blank screen. And finally checking the instance emojis through website shows all default emojis available and usable. 

All instances running 4.0.2. Honestly no idea if this helps narrow anything down but thought i´d mention my experience regardless.

**Comment by te6-in** [comment]
What people in my timeline discovered is that emojis including underscore(_) don't show properly.

**Comment by Dimillian** [comment]
That definitely narrow it down to our own code doing some bad parsing for recognising custom emojis :) CC @divadretlaw on this.

**Comment by te6-in** [comment]
@Dimillian I tried changing the regex from [this line](https://github.com/Dimillian/IceCubesApp/blob/71063c69dfd282a74cf49cec4fe77f5c9e48966e/Packages/Models/Sources/Models/Alias/HTMLString.swift#L41) to exclude the underscore and confirmed that emojis including _ shows properly.
But I'm not pretty sure what this change will bring across the app since I'm not fully understanding the codes 🥲

**Comment by Dimillian** [comment]
CC @xurble didn't realised it was there and not in our EmojiTextView library

**Comment by divadretlaw** [comment]
Yeah I guess because of this Regex the resulting emoji code results in `:some\_emoji:` instead of `:some_emoji:` but then `EmojiText` tries to find `some\_emoji` in the list of available emojis but obviously cannot find it then.

**Comment by Dimillian** [comment]
✅  LGTM
