### ISSUE TITLE
Bug: inconsistent icon weight in toolbar (Mac)

### ISSUE THREAD

**Issue by rsebbe** [Dimillian/IceCubesApp#614]
Icon weight (stroke width) across different icons is inconsistent when app is run on a Mac. Some are very thin, others much stronger. See attached screenshot. Version 1.0 (872).

<img width="64" alt="Screenshot 2023-02-02 at 15 56 45" src="https://user-images.githubusercontent.com/369828/216359469-cac01a45-8821-416e-b5ce-955c20d1d704.png">

**Comment by Dimillian** [comment]
It's been reported previously, will look at it :)

**Comment by rsebbe** [comment]
didn't see it, sorry about that. Thank you so much!

**Comment by Dimillian** [comment]
<img width="90" alt="image" src="https://user-images.githubusercontent.com/535509/218085843-42ce5695-18a4-4518-9b82-8c18be842336.png">
What do you think?

**Comment by rsebbe** [comment]
yes, it's much better. Thank you for fixing it.
