### ISSUE TITLE
Bug: Swipe Action bug

### ISSUE THREAD

**Issue by PrajeetShrestha** [Dimillian/IceCubesApp#615]
- Duplicate swipe actions are created.
- Swipe action button image not showing up

Issue demonstrated in attached screenshot. 
![ISSUE](https://user-images.githubusercontent.com/8730910/216379272-5a8fb5bd-8bb9-455b-9bf1-b6a612aee099.png)

**Comment by Dimillian** [comment]
How is this even possible lol

**Comment by phpmacher** [comment]
@PrajeetShrestha can you provide the iOS version and the version of your icecubesapp?

I think, giving the versions could always help on bugs.
