### ISSUE TITLE
Feature request: customizable text colours, and themes

### ISSUE THREAD

**Issue by pimoore** [Dimillian/IceCubesApp#62]
This is a really great app already, congratulations! I’d love to see the ability to customize the default text, and with that being able to save, and import/export themes. I’ve already added some Nord colours to mine, so it would be great to bring more of the swatches in, as well as share them back out with the community.

**Comment by Dimillian** [comment]
Ouuuuuwwwwaaaa I love the idea. I think I could even make it works with iCloud so anyone could share and votes for theme in the app!

**Comment by pimoore** [comment]
> Ouuuuuwwwwaaaa I love the idea. I think I could even make it works with iCloud so anyone could share and votes for theme in the app!

That would be fantastic! Not sure if it’s possible, but along with the default tweet text it would be useful to change the secondary text colours like those highlighted here:

![BB3A5153-9554-42F6-9D3D-F90367F743C4](https://user-images.githubusercontent.com/5413470/211897443-d3943a4c-8d51-4de5-808f-c6089f87d66b.jpeg)

Depending on the background colours it’s proving hard to read.

**Comment by Dimillian** [comment]
Yes, I'll look to make primary and secondary text customizable. For now it's default SwiftUI colors with all theme. So it'll quite a bit of a rework to be sure it's applied everywhere.

**Comment by pimoore** [comment]
Thanks, Thomas! 👍🏻

**Comment by Dimillian** [comment]
Closing this as I want to discuss everything about theme improvements here: https://github.com/Dimillian/IceCubesApp/discussions/67
