### ISSUE TITLE
Bug: crash after long idle

### ISSUE THREAD

**Issue by pimoore** [Dimillian/IceCubesApp#623]
I’ve had several instances of the app crashing after opening it from a long idle. The timeline never updates, and after a few seconds of being frozen the whole app crashes. Upon reloading it loses my previous timeline position and loads at the top.

edit: background refresh is disabled for Ice  Cubes

**Comment by mavsill** [comment]
I've got the same problem when I switched to the other instance. Then the app crashes every time when I try to open it again and can never have a chance to switch back to the main instance I use. No matter how many times I've reinstalled the app or restart the phone...😭

**Comment by Dimillian** [comment]
This is what I'm trying to fix in the 1.3.X hotfix basically... this one is just crazy.

**Comment by Dimillian** [comment]
Fixed in 1.3.7
