### ISSUE TITLE
Feature request: automatic theme switching

### ISSUE THREAD

**Issue by jdanthinne** [Dimillian/IceCubesApp#63]
Currently, you can choose from a list of themes globally.
It would be nice to pick a theme for light mode, a theme for dark mode, and a setting to choose between always light, always dark or automatic theme switching (following the system behavior).

**Comment by Dimillian** [comment]
Hello, I'm closing this as I've moved all the thing related to theming improvements here: https://github.com/Dimillian/IceCubesApp/discussions/67
