### ISSUE TITLE
Bug: erratic cursor behaviour in compose screen

### ISSUE THREAD

**Issue by loskristianos** [Dimillian/IceCubesApp#630]
When composing a toot, dragging the cursor around (using long-press on space bar and moving) results in a lot of flickering and jumping around. Similar behaviour when selecting text and moving the end points of the selection. Video attached.
iPhone 13 Pro, iOS 16.3RC

(similar behaviour on an iPad 10th Generation on iPadOS 16.3RC, although it doesn’t seem as bad on there - flickers a little but then settles down).

Edit: can’t attach video so here’s a link to it 
https://imgur.com/a/VQ0fQDH

**Comment by Dimillian** [comment]
Duplicate but will get fixed.
