### ISSUE TITLE
Feature request: remove the three dots button for more actions

### ISSUE THREAD

**Issue by tobiastom** [Dimillian/IceCubesApp#634]
As there are now swipe actions 🎉, and a long press gesture on the status, the three dotted button next to the author might not be necessary anymore.

<img width="353" alt="Bildschirm­foto 2023-02-03 um 14 30 34" src="https://user-images.githubusercontent.com/49210/216629241-1b5850c4-70dd-41ea-9b89-253e03d17af1.png">

I could offer a pull request, if that's what what it takes. 😜

This also seem to be mentioned here before: https://github.com/Dimillian/IceCubesApp/issues/325#issuecomment-1403169362

**Comment by Dimillian** [comment]
I'll actually swap the ... by a thread button if the post is part of it.

**Comment by tobiastom** [comment]
Awesome. Thank you.
