### ISSUE TITLE
Bug: older posts not loaded in home timeline 

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#641]
When I scroll to the bottom of the home timeline, no older posts are loaded. The oldest displayed post is 2 hours old. I checked it in the web frontend where older posts were displayed.

I reported now several bugs in the home timeline, which make your app currently unusable for me. As the home timeline is the core of your app, it’s imo crucial, that these will be fixed very soon.

iOS 16.2, icecubes 1.3.7

**Comment by RockyC36** [comment]
Exists for me as well on iPadOS 16.3, IceCubes 1.4.3. I have to quit the app and launch it again to get everything to load.

**Comment by blueturtleai** [comment]
As it didn’t occur again since 3 weeks, I close the issue.
