### ISSUE TITLE
Bug: Going back from expanded pages in "Explore" takes you back to the first page.

### ISSUE THREAD

**Issue by WaterSword** [Dimillian/IceCubesApp#650]
In the "explore" tab, whenever you expand a section like "trending" and then in the expanded section open a post, when you swipe to go back it takes you all the way back to the first screen of the explore tab instead of the previous section (the expanded trending page)

See video below for an example.

https://user-images.githubusercontent.com/116206844/216791633-cbff9a6d-314c-4242-a8e6-49531497b10f.MOV

**Comment by Dimillian** [comment]
Know issue, will get fixed soon.
