### ISSUE TITLE
Bug: Cannot login on any instance

### ISSUE THREAD

**Issue by Thomas-Philippot** [Dimillian/IceCubesApp#657]
When typing an instance name on the "add account" page, the login button does nothing

The instance details are displayed but nothing else happens

**Comment by bkircher** [comment]
Same here (with this instance: https://mastodon.social)

**Comment by Dimillian** [comment]
Remove the https prefix. Will fix that soon.

**Comment by bkircher** [comment]
FWIW, had to remove the URL scheme completely from that input field, e.g., neither https://mastodon.social/ nor http://mastodon.social/work but mastodon.social does.

**Comment by Dimillian** [comment]
<img width="363" alt="image" src="https://user-images.githubusercontent.com/535509/216839351-3d849c0f-448b-448f-aaf8-29ea6768482c.png">
I think you're on a very old (1.0) version, this been fixed a long time ago actually. Can you download it from the App store instead of TestFlight?
