### ISSUE TITLE
Moved instance, cannot logout

### ISSUE THREAD

**Issue by vowe** [Dimillian/IceCubesApp#660]
I moved from home.social to social.heise.de. Ice Cubes still tries connect to the disabled account on home.social and cannot load content. I cannot remove old account and add new account. When I remove Ice Cubes, reboot, and reinstall, then I am stuck at the same point.

How can I get rid of the old settings for Ice Cubes?

**Comment by pjolt** [comment]
When you open Ice Cubes and go into settings and swipe left on your old account and select delete. Does this make any difference? 

This issue seems the same as #548

**Comment by vowe** [comment]
I was unable to find Settings until I tried tapping on the rotating spinner in the left upper corner. Initially I was looking for it in the Profile tab, but everything was blank.

Now I found settings, was able to delete the old account and register for a new one. Yes, it seems to be the same as #548.

**Comment by pjolt** [comment]
Ah yes, i should have clarified where the settings option can be found. My apologies!   Good that you got it working now!

**Comment by Dimillian** [comment]
Made it better in 1.4.0 :)
