### ISSUE TITLE
Bug: Swipe actions in posts with quotes cause multiple handlers

### ISSUE THREAD

**Issue by Jerry23011** [Dimillian/IceCubesApp#663]
This is first discussed in #615, but the fix did not work since I’m on the latest version v1.3.7
![IMG_4324](https://user-images.githubusercontent.com/89069957/216830313-9e671c65-27b6-4072-918d-69277926ddb4.jpeg)
![IMG_4325](https://user-images.githubusercontent.com/89069957/216830333-dfc25352-fee8-4670-82e7-b342a382e4d5.jpeg)
From my observation, this issue can be reproduced by using the swipe actions on the post that quotes another mastodon post.

**Comment by Dimillian** [comment]
Already fixed for next version.
