### ISSUE TITLE
Feature request: Native Style for Notifications

### ISSUE THREAD

**Issue by trbutler** [Dimillian/IceCubesApp#667]
When Ice Cubes produces a notification, it features a large Ice Cubes icon on the left side of the notification and a smaller picture of the poster. On the other hand, native MacOS/iOS notifications like Messages display the poster on the left side with a small overlaid icon of the notifying app. This makes it easier to see the information that is actually relevant with as little screen space used as possible. Mammoth, another new Mastodon client, follows that format that Apple uses. Comparison below of Messages (top), Mammoth and Ice Cubes (bottom).

![Screenshot 2023-02-05 at 11 29 53 AM](https://user-images.githubusercontent.com/4777803/216845464-b90b301b-50aa-44a3-9d8d-631922b0e0c9.jpg)

**Comment by nekolaboratory** [comment]
As far as I read the code, it seems to be implemented as expected.
If you have only one account for notifications, your avatar will be highlighted as you said,
For notifications from multiple accounts, the app icon is highlighted.

Similar to the attached screenshot, iOS stacks multiple notifications from one app.
In this case, only one user avatar out of multiple user avatars is highlighted, so it doesn't make much sense, and I think this implementation is suitable.

However, I agree with you that I would rather have a larger amount of textual information than show two avatar images.

**Comment by Dimillian** [comment]
I would love to do it but this is very challenging due to the current push notifications API.

**Comment by trbutler** [comment]
@nekolaboratory The notification always seem to appear with the Ice Cubes icon on the left side and the person in reference on the right (unlike Mammoth). So far, I haven't seen any Ice Cubes notifications appearing in the other style. Are you saying that's because I have Ice Cubes logged into several accounts?

**Comment by Dimillian** [comment]
Done in 1.5.0
