### ISSUE TITLE
Feature request: Browsing posts that are getting traction on other instances 

### ISSUE THREAD

**Issue by wnagrodzki** [Dimillian/IceCubesApp#673]
I find it very useful to browse posts that are getting traction on other mastodon instances. Despite my account resides on local community server I am still interested in what mastodon.art community perceives as important.

IceCubesApp's Local Timelines stream all the posts in chronological order only.
[Toot!](https://apps.apple.com/us/app/toot/id1229021451) supports this feature already.
![IMG_1F8FC334FA26-1](https://user-images.githubusercontent.com/278594/216927101-4c7047fb-cc25-48dc-942f-bda4660be623.jpeg)

I am really curious what you think.

**Comment by Dimillian** [comment]
I think that would be awesome. Let me think about some UI.

**Comment by Dimillian** [comment]
Done for 1.4.1!

**Comment by Dimillian** [comment]
https://github.com/Dimillian/IceCubesApp/commit/5f76a8057c2c19dfa05e032f780d7659a0737624

**Comment by wnagrodzki** [comment]
Wow, that was fast. Tipping already paid off. Thank you 😊

**Comment by Dimillian** [comment]
This make so much sense and was incredibly stupid to do as the codebase made it readily available :D 
Just never thought about it.

**Comment by tobiastom** [comment]
@Dimillian Wouldn't it make sense to also use this filter UI for the home timeline to make it more consistent?
