### ISSUE TITLE
Feature request: Group custom emojis in the picker when composing 

### ISSUE THREAD

**Issue by olivvybee** [Dimillian/IceCubesApp#674]
The custom emoji picker on the web interface groups the emojis into sections determined by the instance admins.

When choosing a custom emoji in Ice Cubes, it’s hard to find the one I’m looking for because all the emojis are presented in a single list. 

I would like to see them grouped in the same way as the web, so I can quickly select one by going to its category.

**Comment by bitfl0wer** [comment]
I'd like to say that I'd see this as a welcome change, since I was just about to create an issue with the same feature request. :)
