### ISSUE TITLE
Bug: Is the Open Dyslexic font actually available?

### ISSUE THREAD

**Issue by markrprior** [Dimillian/IceCubesApp#677]
I expected to find it in the custom fonts list but I don't see it. Am I looking in the wrong place? I'm running 1.3.8.

**Comment by Dimillian** [comment]
It should be but it's not, it's def a bug. I've poked around @xurble, and basically without installing the font system wide from the app (so we need to code an action that do that, and have the proper entitlements (but last time I've tried it crashed on device)) I don't know how to do it yet. 

I don't know what it show in the simulator, but not on device, this is so weird.

**Comment by Dimillian** [comment]
What you can do is install it manually from the FontCase app: https://apps.apple.com/fr/app/fontcase-manage-your-type/id1205074470 and then it'll be available in the app. We'll try to fix it so the app make it available in the picker.

**Comment by xurble** [comment]
I've reached out to the person that made OpenDyslexic since it turns out they follow me on Mastodon. 

They make an app specifically to install the font so might have some insight.

**Comment by Dimillian** [comment]
If we can show it in the font picker, maybe we can just have it in the toggle menu directly and apply it like any iOS custom font. Without installing it.

**Comment by antijingoist** [comment]
Ohhh, fonts in iOS is a giant pain. I think the process you need to do is have it as an option separate from the system fonts.  Perhaps if you include it in the menu and list system fonts after it, or include it in a separate list, like "system", "opendyslexic", "other bundled fonts", "Custom" -> opens menu? 

If you wanted to have it installable, last I checked the documentation, it was sparse, but the idea was
* Fonts listed in "Fonts provided by application" in plist
* try installing it and check for errors :-/ You can't check if the font is installed with ctfontmanager for some reason.  
* To install, I looped through an array of the font names: 
`           CTFontManagerRegisterFontURLs([Bundle.main.url(forResource: fontFile, withExtension: "otf")] as CFArray, .persistent, true) { (errors, done) -> Bool in
                    if(done) {
                        print("Some days I don't have any idea of what I am doing and CTFontManagerRegisterFontURLs has definitely rubbed that in.")
                        success += 1
                    }
                    print(errors as Array)
                    return true
                }
            }`
* iOS shows a permissions dialog only for the first font install attempt in the loop.

The printf comment is still true.
Not exactly an answer you were looking for, but it's everything I have. :-|

**Comment by Dimillian** [comment]
I've tried that yesterday and it was very crashy. If nobody try tonight I'll try the first option, just list them under the first menu so it'll be system, those two fonts and then the font picker.

**Comment by markrprior** [comment]
Toot! have it as a separate menu item so maybe they found that to be the path of least pain.

**Comment by antijingoist** [comment]
AFAIK, thats what almost all apps that use the installed fonts do. Even Word has a split menu.

**Comment by antijingoist** [comment]
@Dimillian @markrprior 
I just tried the most recent commit on main and (https://github.com/Dimillian/IceCubesApp/commit/f1fd18a04f0d64d83ef10e4272f8ca960cfbc454) on a new iOS simulator and it's working with both hyperlegible and opendyslexic?

**Comment by Dimillian** [comment]
It's only listed in the simulator not on device.
