### ISSUE TITLE
Bug: When replying to content that has a care warning, the care warning is not carried over to the reply

### ISSUE THREAD

**Issue by antijingoist** [Dimillian/IceCubesApp#684]
✅ Search that this bugs don't already exist before creating it.

Unless explicitly including Spoiler Text in a reply to a post already containing Spoiler Text, the reply is sent without Spoiler Text. This causes issues in threads where people accidentally forget to explicitly include it. 

Expectation: When replying to a post with Spoiler Text, the reply should pre-fill with the spoiler text from that post.

**Comment by Dimillian** [comment]
Does the web works like that? If yes, will make it so in the app.

**Comment by antijingoist** [comment]
web works that way
