### ISSUE TITLE
Bug: can't open app when account has been moved

### ISSUE THREAD

**Issue by HappyFishkeeper** [Dimillian/IceCubesApp#688]
can't open app when account has been moved.  I just moved from one instance to another.  Then tried to open IceCubes and the app won't let me access my profile to add the new account.  When I go to Profile, nothing shows up.  I was thinking I would just add the login info.

**Comment by Dimillian** [comment]
You can tap in setting (any other tab than profile), tap the spinning wheel, then settings then swipe on the old account to delete it.

**Comment by HappyFishkeeper** [comment]
Thank you! I did not realize I could tap the spinning wheel.

 

I'm all set now. Thanks for the very quick response. Great app.
