### ISSUE TITLE
Feature request: add Basque

### ISSUE THREAD

**Issue by xabirequejo** [Dimillian/IceCubesApp#691]
No idea how to create a pull request and not enough data for tutorials, but I translated the strings to Basque and I have attached [the file](https://github.com/Dimillian/IceCubesApp/files/10670714/eu.lproj.txt) to this issue so that Ice Cubes speaks another language.

Weblate would make it a lot easier for us noobs and hopefully variables could be reordered, or else some of the strings won't make much sense in some languages (I'm thinking line 392, for example) — they don't sound natural and there's only so much we can do.

Thanks.

**Comment by dertuxmalwieder** [comment]
> Weblate would make it a lot easier for us noobs

It should not be mandatory though. The less user data I'll need to leave on other sites, the better. Your translation only needs to be added [to the project file](https://github.com/Dimillian/IceCubesApp/commit/be802980c58c8b2f34e1b67fd8c1ced715643773) as far as I can see.

**Comment by EvilOne** [comment]
@xabirequejo, I added your language additions to #728.  Could you please look it over?

**Comment by xabirequejo** [comment]
Thanks, @EvilOne, it's a good start. I hope I can get my broadband back soon and give it the finishing touches myself.

@dertuxmalwieder I'm not against learning new skills and I understand that GitHub is the right tool for developers, but I also believe that platforms such as Weblate, Transifex and Crowdin make it a lot easier to localise software. Besides, you could log in with your GitHub account or even self-host the platform to minimise data footprint? Or maybe I'm terribly wrong.

Again, thank you.

**Comment by EvilOne** [comment]
@xabirequejo, great! Since you looked it over, I am sure that @Dimillian will merge this sometime tomorrow. 

Thanks for taking the time and translating things!
