### ISSUE TITLE
Option to hide full handles

### ISSUE THREAD

**Issue by AndrewHaglund** [Dimillian/IceCubesApp#692]
add an option to hide handle for a cleaner look

![C5C9051D-A107-4D45-AB89-888A40658073](https://user-images.githubusercontent.com/5075921/217132866-529c2adf-acec-4992-a8c8-89f4d4b392cc.jpeg)

**Comment by danieldickison** [comment]
I think this one is a dupe or variant of #313.

**Comment by Dimillian** [comment]
All good and done.
