### ISSUE TITLE
Bug: swipe icons off-screen for lengthy posts (see video).

### ISSUE THREAD

**Issue by ddimick** [Dimillian/IceCubesApp#693]
https://user-images.githubusercontent.com/46494221/217169783-9509de99-fea9-47a6-8a37-cf24a7d59fc2.MOV

**Comment by Dimillian** [comment]
Ivory have the same problem and I actually have no idea on how to fix it. This is a native iOS API, I can't move the icon at all. So it's either that or removing this feature.
