### ISSUE TITLE
Bug: selecting hyperlegible in the font selector selects System

### ISSUE THREAD

**Issue by antijingoist** [Dimillian/IceCubesApp#703]
Selecting hyperlegible as the font option resets to System as a choice. 

https://user-images.githubusercontent.com/663100/217233830-e00cc74e-7ed8-49f0-8bb8-45802796b939.MOV

Search that this bugs don't already exist before creating it. ✅

**Comment by Dimillian** [comment]
Fixed in 1.4.2 that out just now :)

**Comment by antijingoist** [comment]
Faster than Barry Allen can run! 😁
