### ISSUE TITLE
Bug: Cursor positioning when writing text constantly jumps to the end

### ISSUE THREAD

**Issue by phpmacher** [Dimillian/IceCubesApp#705]
When writing text and positioning the cursor somewhere in the already written text and wanting to correct something, the cursor jumps to the end of the complete text at each character.

This behavior appeared with version >1.4.0

Version 1.4.2 under iOS16.3

**Comment by Dimillian** [comment]
This is weird you're reporting that because 1.4.1 actually fixed that.

**Comment by phpmacher** [comment]
It's slightly different now:

'til 1.4.0 the cursor seemed to be like a shadow and it was sometimes not easy to position it, cause it jumps around on the positioning.

Now it is positioned e.g. at the beginning of a word and if i tap on a character, the cursor jumps at the end of the whole text.
There is no shadow-cursor or more than one cursor.

It simply jumps at the end after writing the typed character at the position it was before.

**Comment by Dimillian** [comment]
Found the issue, will be fixed in next version, and text input will be even smoother!

**Comment by RockyC36** [comment]
This issue is REMARKABLY frustrating. I’m on 1.4.3 on iPadOS 16.3 and it happens constantly. The cursor will ignore wherever I’ve placed it and will instead move to the end of the text.

**Comment by phpmacher** [comment]
@RockyC36 Sometimes it seems to help to place the cursor and then wait 4-5s. Then it can happen that you can write at this point.

**Comment by RockyC36** [comment]
I’ll give that a try, thanks.

--
