### ISSUE TITLE
Bug: I get cached messages from trending in the home timeline

### ISSUE THREAD

**Issue by alexelgt** [Dimillian/IceCubesApp#710]
I’m on version 1.4.2.

Steps to reproduce the bug:

1) Open the app
2) From the dropdown menu switch to trending
3) Go to your Home Screen (exit the app without closing it)
4) Go back to the app and from the dropdown menu switch back to the home timeline

The faster I do step 4, the easier is to reproduce the bug.

If the bug appears, you can scroll up and get messages that should not be in the home timeline.

This is related with cached messages from trending because if I clear the cache and restart the app (or go to, for example, local timeline and back to home timeline) everything is back to normal.

**Comment by Dimillian** [comment]
Actually super nice. You found the repro step of a bug I could not nail down!
