### ISSUE TITLE
Bug: Hyper Legible font not accessible

### ISSUE THREAD

**Issue by markrprior** [Dimillian/IceCubesApp#711]
Open Dyslexic does work through the new Timeline Font menu but Hyper Legible does not. If I try to select it then the app selects System instead. For example, if I select either a custom font or Open Dyslexic and Display Settings is indicating I have that selected and then try to Hyper Legible the system will indicate that System is selected.
Note I have Open Dyslexic installed via Fontcase (as a workaround to the previous Open Dyslexic case) so maybe that is masking the problem for Open Dyslexic too. 
This is for 1.4.1 of the app.

**Comment by EvilOne** [comment]
There is a 1.4.3 available to download and this should fix your issues.

**Comment by markrprior** [comment]
> There is a 1.4.3 available to download and this should fix your issues.

Apple are slow at pushing it out to all stores. Once it drops I'll have a look, thanks.

**Comment by Dimillian** [comment]
All good!
