### ISSUE TITLE
Feature request: add new line when sharing

### ISSUE THREAD

**Issue by stoinov** [Dimillian/IceCubesApp#742]
When sharing, the entry cursor is placed at the end of the text.
Would it be possible to mimic the Ivory experience where a new line is added either before or after the link so one can start typing right away?

**Comment by Dimillian** [comment]
It's already adding a space at the end of the link. On Ivory I don't even see a space when sharing a link. Are you sure it's not already there?

**Comment by stoinov** [comment]
I did some testing and I see what you mean. The space added is when you share _to_ IceCubes.
What I meant tho, is when I'm sharing _from_ the app.

Can you check and confirm if that's indeed the case and fix it?
