### ISSUE TITLE
Bug: Translation use the DNS domain of the poster, not the language of the toot...

### ISSUE THREAD

**Issue by jaco60** [Dimillian/IceCubesApp#747]
## Environment:

 - OS: 
IOS 16.3
 - IceCubesApp version: 
 IceCubeApp v1.4.4

## Description

If a german (.de) poster toots in english, Icecube writes (in french) : "Traduire de allemand"

## Related Issues

Very bad french localisation : "traduire de allemand" is not french (as most of french localisation strings of the App...). "Traduire" would be enough

**Comment by Dimillian** [comment]
Oué mais le français c'est compliqué roh

**Comment by jaco60** [comment]
Raison de plus pour ne pas faire de grandes phrases :)

**Comment by sothawo** [comment]
The question is: did the german user that posted in english had the language of the post set to english as well? Because the selected language for posting is sent along with the post data, so if this is set to german (which might be set as default for that user) then you'll see that behaviour

**Comment by Havhingstor** [comment]
I think the language was probably wrongly set. I've seen examples where different posts from one user (https://mstdn.social/@stux) show the ability to translate from dutch or english, depending on the language of the post, suggesting that it only regards the language the user said the post is written.

**Comment by jaco60** [comment]
I suppose it didn't... I've seen the same problem with a finnish user who admit to forget to switch to english before posting... But that's rather cumbersome to switch before a post, isn't it? Why not stay with a "one size fits all" message, as "Translate" ?

**Comment by sothawo** [comment]
agreed for that link. 

But - and that has nothing to do with this issue - I find it important to always set the language for a post, because you can set in the settings on the server the languages you are interested in. For me I have set that to english, german and french. But I see posts from people in russian, where these are offered to be translated from english because the poster did not set the language accordingly.

**Comment by jaco60** [comment]
Agree too... It is important to indicate the language of the post. But, if this is not done, no need to deceive the reader even more :)

**Comment by Dimillian** [comment]
Everyone is bugging me about this, I don't know what to do. At this point I'm considering not using the post lang but running on device ML thing to detect the lang and use that as the true post language.

**Comment by sothawo** [comment]
Having something to detect the language might probably be the best solution. 

The API definition btw does not require language when posting a status; I just tested the server's behaviour. I sent in a status without a language and got back "de" (default setting for my profile). Quite interesting that the mastodon server in this case returns the default language although I did not set any and the field in the returned status is nullable as well.

So if you got something in mind to detect the language on the device, I wouldn't change the current behaviour now.

**Comment by Havhingstor** [comment]
DeepL already has some kind of language detection. However it seems that you can't really access it via the API without letting it just translate the whole text. If you let it translate the text without specifying the source-language, it seems to return both the translation as well as the detected source language. It would probably be possible to send every single post to DeepL to translate and only show when the detected source language is different from the device language. However, that probably needs some time, so the button wouldn't pop up instantly after loading the post. Additionally, i don't know if there would be any problem with the API-key if so many requests are coming in.

**Comment by sothawo** [comment]
not only the API usage, but that would mean a lot of traffic from the users device to deepL when the result probably is not used in the most cases.

**Comment by LorenAmelang** [comment]
> Everyone is bugging me about this, I don't know what to do. At this point I'm considering not using the post lang but running on device ML thing to detect the lang and use that as the true post language.

Obviously most posters are ignorant of the language setting. How about eliminating the "Translate" option visible in the post, and having it always available in the Share Sheet, like my "Translate with Mate" option? Can you add items to the Share Sheet? Or add a Translate icon to the Detail view of a post? 

I more often need translate when the language setting matches mine, but some of the actual text doesn't. If you do ML, I hope it can appear for bits of quoted text, not just the majority language of the post.

**Comment by sothawo** [comment]
I'm personally against moving the translation button out of the post; having it only in the popup menu would require an extra long tap and a selection from the menu whereas currently it's just a tap in the post. I would really miss this.

**Comment by phpmacher** [comment]
@Dimillian My suggestion is:

Leave the current solution in. This is ideal if everyone follows the rules of the game, that you have to provide a post with the language in which it is written.

But add to the menu an item to translate, so that you can also translate posts where the creators have not set the correct language.

Everyone can live with that.
