### ISSUE TITLE
Feature request:re-add burger menu on posts

### ISSUE THREAD

**Issue by sothawo** [Dimillian/IceCubesApp#757]
There was a burger menu (or whatever this the dots is named) on each post to pop up a menu with actions for a post. This was removed as they set the buttons below the post and the long press context menu. 
 
I think it would make sense to add the burger I again. The buttons at the bottom don’t include edit or quote, and the pop up odd not an intuitive option ( see https://nerdculture.de/@tita/109835707620138094) where this was asked

**Comment by Dimillian** [comment]
I would have to think of a new place to add it then, right now because of the thread icon it could make the view too busy.

**Comment by sothawo** [comment]
didn't notice the thread icon,I probably have too few of these. But I'll add edit to the possible swipe actions, then everybody can put it there if fast access is needed
