### ISSUE TITLE
[Feature request] Option to select post's language in the composer

### ISSUE THREAD

**Issue by jsynowiec** [Dimillian/IceCubesApp#76]
It is important for multi-language people to indicate the language of their post.

The `/api/v1/statuses` endpoint accepts a `language` parameter. Its value should be a ISO 639 language code that represents the language of a status update. On the official Mastodon UI, this can be selected using the language icon.

![IMG_0174](https://user-images.githubusercontent.com/1029142/212475094-f13cef53-29bc-4538-a63e-753a37fe3cf6.jpeg)

Ice Cubes could have a similar button in the New Post composer. It could be placed between the CW and Drafts buttons on the toolbar. The default language could be derived from the system language.

**Comment by Dimillian** [comment]
It's planned and will come :)
