### ISSUE TITLE
Bug: All of my logged in accounts disappeared from the iOS app

### ISSUE THREAD

**Issue by Someguy123** [Dimillian/IceCubesApp#765]
App Version: 1.4.4
iOS Version: 16.1.1
Model: iPhone 13 Pro Max

The other day I downloaded Ice Cubes to test it out, I setup 3 of my accounts (all on equestria.social), and was using them all just fine.

Today I clicked on an iOS notification which was a reply to a Toot I made, and it brought me to the default Mastodon timeline, with all my accounts seemingly gone...

This is a pretty bad bug, it's a pain to add multiple accounts (on all apps in general), it's not good for an app to just "lose" your account logins within a day.

**Comment by Someguy123** [comment]
Edit: After closing and re-opening the app - my accounts seem to have re-appeared

Still strange for accounts to seem to disappear after clicking a notification and should be investigated

**Comment by Dimillian** [comment]
Weird. Network error I guess.
