### ISSUE TITLE
[Feature Request] Localization

### ISSUE THREAD

**Issue by vollkorntomate** [Dimillian/IceCubesApp#77]
Set up a system for localizing the app for languages other than English.

This will probably require at least the following points:
- [ ] Convert all hard-coded English text in the views etc. to localization keys
- [ ] Add the Localizable.strings file for English
- [ ] Possibly set up an easy-to-use collaboration tool (such as Crowdin)
- [ ] Adapt UI for right-to-left languages (I assume most of it is handled automatically by SwiftUI)

I volunteer to help setting all of this up and providing translations for German. It is just a very big change in many files and some work beyond that, so I didn't want to just open a PR.

**Comment by Dimillian** [comment]
Hello, 

Thanks for the list, I'm not planning to start localisation at all at this point, most probably when I'll have all the feature in at a later stage I'll consider it. 
But feel free to setup the project for it, I can then continue to build on that when we have a proper localizable files etc... 

Thanks!
