### ISSUE TITLE
Bug: The play icon appear on videos in profiles view but not in timeline

### ISSUE THREAD

**Issue by MuDevV** [Dimillian/IceCubesApp#771]
## Environment:

 - OS: 
 macOS Ventura 13.2 (22D49)
 - IceCubesApp version: 
 Ice Cubes 1.4.5 (1310)

## Description

The preview of a video in the timeline no longer shows the play button, whereas this button is clearly visible when the same toot is displayed in the profile that tooted the video.
Not a big problem, but it's convenient anyway.

**Comment by Dean151** [comment]
@MuDevV Would this been solved with #939 ?
