### ISSUE TITLE
Bug: image pasting pastes url to cache, not image

### ISSUE THREAD

**Issue by jonathankoren** [Dimillian/IceCubesApp#780]
## Environment:

 - OS: iOS 16.2
 - IceCubesApp version:  1.4.4

## Description

Pasting an image should attach the image, not paste the URI of the local cache.

1. Use Safari to find an image on the web. Let’s say https://frinkiac.com/meme/S08E14/1031880.jpg?b64lines=IFRXTy0tIFdIRU5FVkVSIEVMT04gSVMgCiBOT1QgT04gVEhFIFRJTUVMSU5FLCBBTEwgVEhFCiBPVEhFUiBVU0VSUyBTSE9VTEQKIEJFIEFTS0lORywgIldIRVJFJ3MgRUxPTj8i 
3. Long press the image, and bring up the share dialog. Select “copy”
4. Go to IceCubes, compose a toot. Long press on the text box to bring up the paste option, and the tap it.
5. Observe you just pasted a string similar to  
`file:///var/mobile/Library/Caches/com.apple.Pasteboard/eb77e5f8f043896faf63b5041f0fbd121db984dd/33727f0b068265475b9f8b588c62cbc88e55700e`

**Comment by Dimillian** [comment]
Fixed for 1.4.7
