### ISSUE TITLE
Bug: Tab bar icons misaligned

### ISSUE THREAD

**Issue by Ruchbah** [Dimillian/IceCubesApp#783]
Now that’s possible (thanks!) to remove the strings from the tab bar, the icons just remain in their place rather than go a bit down to align themselves within the tab bar. ie there’s more empty space below them than above.

**Comment by Dimillian** [comment]
Unfortunately, not planned to change this unless I make a custom tabbar. So much much later down the line.

**Comment by Ruchbah** [comment]
Thanks the prompt reply!
