### ISSUE TITLE
Feature request: improvement of secondary account icon visualization (iPadOS/macOS)

### ISSUE THREAD

**Issue by vdbm** [Dimillian/IceCubesApp#791]
At the moment, after adding a secondary account:
- the secondary icon is added to the bottom of the left navigation bar when in the primary account
- the secondary icon is added right underneath the primary account icon when in the secondary account

Much better would be an approach like in Ivory: secondary account icon is hidden when in primary account, and only shows up when clicking on the primary account icon (the same action which also allows you to switch accounts)

**Comment by Dimillian** [comment]
This is how I've designed it for iPadOS / macOS and how I use it. Not planning to change it for now.
