### ISSUE TITLE
Ballistic Scrolling on macOS

### ISSUE THREAD

**Issue by pohl** [Dimillian/IceCubesApp#795]
On iOS and iPadOS, Ice Cubes has a nice, ballistic scroll. You can flick the feed with your finger, and the scroll continues for some time even after your finger no longer touches the screen.

On macOS, scrolling in Ice Cubes does not behave this way..  Other applications on the macOS do have this feature, though.  For example, load some tall web page in Safari, and feel the ballistic scrolling by flicking up or down on the track pad.

Ice Cubes feels a little out of place on macOS by not having this behavior. Implementing it would provide a nice level of polish to the app.

**Comment by Dimillian** [comment]
Because Ice Cubes is an iOS app running on macOS, there is nothing I can do about it for now. Maybe one day I'll do a proper macOS app.
