### ISSUE TITLE
Bug: Counts don't update when returning from a thread view

### ISSUE THREAD

**Issue by dougalcampbell** [Dimillian/IceCubesApp#804]
## Environment:

 - OS: iOS 16.3
 
 - IceCubesApp version: 1.4.5
 

## Description
If you click a post and go into the thread view, then Star or Reblog the post, the counts update and highlight to show that you've interacted with the post. 

When you click the "< Back" link to return to the previous view, the post still shows its original state. 

The post in the previous view should update to show the new interaction and count state. 

## Related Issues

I did not find any related issues, based on my search terms. 

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Duplicate of https://github.com/Dimillian/IceCubesApp/issues/889
