### ISSUE TITLE
Bug: string not using localisation

### ISSUE THREAD

**Issue by xabirequejo** [Dimillian/IceCubesApp#816]
## Environment:

 - OS: iOS v16.3
 - IceCubesApp version: v1.4.6
 - Language: Basque

## Description

String `account.detail.n-fields %lld` doesn't seem to use localisation on 1.4.6. It shows the string itself, not the text.
Same issue with `account.detail.featured-tags-n-posts`.
The app shows the right text when the language is changed to British English or Catalan.

## Related Issues

Very similar to #525: [account.followers is not translated to Catalan](https://github.com/Dimillian/IceCubesApp/issues/525)

## Illustration

![IMG_3073](https://user-images.githubusercontent.com/888924/218326588-60632c63-6b99-4e1f-bed9-b2bf0d423104.jpeg)

**Comment by te6-in** [comment]
I looked up the Localizable.strings file and it seems that the entire line is missing for both. Doesn't look like a typo issue for me.

**Comment by Dimillian** [comment]
<img width="316" alt="image" src="https://user-images.githubusercontent.com/535509/218383001-5b259295-adb2-49e4-9b93-b72c42d3fbbb.png">

You need to add it there.

**Comment by xabirequejo** [comment]
Hmmokay. I must've dropped them at some point; I'm sure they where showing the other day. I have added them back to where they were before, I believe.
I'm going to take a look at plurals.
Sorry and thanks.

**Comment by xabirequejo** [comment]
Hi again,

- I have updated the plurals file. Is it now safe to remove these strings from the generic / non-plurals document?
- I have changed the string order for "design.tag.n-posts-from-n-participants %lld %lld" to show participants before posts as it didn't make much sense in my mother tongue. I hope that's ok and doesn't break anything.
- Also, is there a way to change the order for the time? That app says: `X secs/mins/hours ago`. Is it possible to edit it somehow so that the word order is different depending on the number ("one" or "other")?
- Last and least, where does the "joined" date come from? [Date FNS](https://github.com/date-fns/date-fns) maybe?

**Comment by te6-in** [comment]
- Removing duplicate strings from the Localizable.strings (generic) that already exist in Localizable.stringsdict (plural) should be safe. If you want to make sure, you'll want to run the build and check the result out.
- I've just found out that you can specify the position of variables in the string by adding `n$` between the format specifier like `%1$lld`.
  - Usage: `%lld posts from %lld people` == `%1$lld posts from %2$lld people` == `%2$lld people wrote %1$lld posts`
  - `"design.tag.n-posts-from-n-participants %lld %lld" = "%2$lld명의 사용자가 %1$lld개 글 작성함";`
  - [reference](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Strings/Articles/formatSpecifiers.html)
- Actually, I couldn't 100% understand what date and time you're referring to, but if it's the created/edited time of the post, [`DateFormatter()` and `RelativeDateFormatter()`](https://github.com/Dimillian/IceCubesApp/blob/0526c1025f4e8ae13749493bc2b43b3073d31939/Packages/Models/Sources/Models/Alias/ServerDate.swift#L21) handle them. So I believe they are not part of string translations.

Hope this helps!

**Comment by xabirequejo** [comment]
Thank you, I'm not sure how to use it, though. Would this be ok if the goal was to change the order to `%2$lld people wrote %1$lld posts` (instead of `%lld posts from %lld people`?
```
<key>design.tag.n-posts-from-n-participants %1$lld %2$lld</key>
	<dict>
		<key>NSStringLocalizedFormatKey</key>
		<string>%#@tagParticipantsCount@ %#@tagPostsCount@</string>
		<key>tagParticipantsCount</key>
		<dict>
            	<key>NSStringFormatSpecTypeKey</key>
			<string>NSStringPluralRuleType</string>
			<key>NSStringFormatValueTypeKey</key>
			<string>lld</string>
			<key>one</key>
			<string>Partaide batek egindako</string>
			<key>other</key>
			<string>%2$lld partaidek egindako</string>
		</dict>
		<key>tagPostsCount</key>
		<dict>
			<key>NSStringFormatSpecTypeKey</key>
			<string>NSStringPluralRuleType</string>
			<key>NSStringFormatValueTypeKey</key>
			<string>lld</string>
			<key>one</key>
			<string>bidalketa %lld</string>
			<key>other</key>
			<string>%1$lld bidalketa</string>
		</dict>
	</dict>
```

Can I modify the main `<key>` or does that need to be as is?
—
And about the last two bullet points on the [previous post](https://github.com/Dimillian/IceCubesApp/issues/816#issuecomment-1430144757), I was wondering about the source of the time/date that is shown on posts as it's not correct in Basque. I thought that maybe I could have a look at it.
![IMG_3094](https://user-images.githubusercontent.com/888924/219823594-0f7d65ff-7ec6-4669-a983-7d8698cfae21.jpg)
![IMG_3093](https://user-images.githubusercontent.com/888924/219823620-220fcbc7-d9af-45dd-bd69-739be054c015.jpg)

**Comment by te6-in** [comment]
@xabirequejo

The main key should remain the same. If you want to change the order, you should modify the `NSStringLocalizedFormatKey` value.

```xml
<dict>
	<key>design.tag.n-posts-from-n-participants %lld %lld</key>
	<dict>
		<key>NSStringLocalizedFormatKey</key>
		<string>%#@tagPostsCount@ written by %#@tagParticipantsCount@</string>
		<key>tagPostsCount</key>
		<dict>
			<key>NSStringFormatSpecTypeKey</key>
			<string>NSStringPluralRuleType</string>
			<key>NSStringFormatValueTypeKey</key>
			<string>lld</string>
			<key>one</key>
			<string>%lld post</string>
			<key>other</key>
			<string>%lld posts</string>
		</dict>
		<key>tagParticipantsCount</key>
		<dict>
			<key>NSStringFormatSpecTypeKey</key>
			<string>NSStringPluralRuleType</string>
			<key>NSStringFormatValueTypeKey</key>
			<string>lld</string>
			<key>one</key>
			<string>%lld person</string>
			<key>other</key>
			<string>%lld people</string>
		</dict>
	</dict>
</dict>
</plist>
```
Take a look at [this line](https://github.com/Dimillian/IceCubesApp/blob/980b9a5dd6e4afd386fbaaf15ac16f5c889bcc49/Packages/DesignSystem/Sources/DesignSystem/Views/TagRowView.swift#L19) from the actual code and let's assume that `tag.totalUses` is 4 and `tag.totalAccounts` is 1.
The stringsdict above should say `4 posts written by 1 person`.

```xml
<dict>
	<key>design.tag.n-posts-from-n-participants %lld %lld</key>
	<dict>
		<key>NSStringLocalizedFormatKey</key>
		<string>%2$#@tagParticipantsCount@ wrote %1$#@tagPostsCount@</string>
		<key>tagPostsCount</key>
		<dict>
			<key>NSStringFormatSpecTypeKey</key>
			<string>NSStringPluralRuleType</string>
			<key>NSStringFormatValueTypeKey</key>
			<string>lld</string>
			<key>one</key>
			<string>%lld post</string>
			<key>other</key>
			<string>%lld posts</string>
		</dict>
		<key>tagParticipantsCount</key>
		<dict>
			<key>NSStringFormatSpecTypeKey</key>
			<string>NSStringPluralRuleType</string>
			<key>NSStringFormatValueTypeKey</key>
			<string>lld</string>
			<key>one</key>
			<string>%lld person</string>
			<key>other</key>
			<string>%lld people</string>
		</dict>
	</dict>
</dict>
</plist>
```
At the same situation, this stringsdict will say `1 person wrote 4 posts`.
The `n$`position specifier represents that it will grab the `n`th variable from the code.

In case of the date & time formatting, I believe there's nothing we can do about it only with string localizations for now.

**Comment by xabirequejo** [comment]
Hey, @te6-in:
Thank you very much for your help.
Now Basque localisation makes a lot more sense with the new order.
Thanks

**Comment by te6-in** [comment]
I'm glad it was helpful 😄
I learned a lot of new things too.
