### ISSUE TITLE
Bug: boost and favorite info not actual in detail view

### ISSUE THREAD

**Issue by sothawo** [Dimillian/IceCubesApp#818]
## Environment:

 - OS: 
iOS 16.3
 - IceCubesApp version: 
1.4.6

## Description

When I favorite or boost a post in my home timeline, the number of favs and boost for that post is increased. When I then tap on that post to get into the detail view, the numbers shown there don't reflect my action.

**Comment by Dimillian** [comment]
This is actually fixed in 1.4.7 in review at Apple (on on main :) )

**Comment by sothawo** [comment]
I promise that in the future I will always install the latest commit of the main branch and check before opening an issue 😄
