### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by maksim77** [Dimillian/IceCubesApp#826]
## Environment:

 - OS: 16.3
 - IceCubesApp version: 1.4.7

## Description

The translation button translates from English to... English.
I think it would be very useful to put the target language for translation in the settings.

**Comment by Dimillian** [comment]
Closing this as I already have the same issue somewhere but yes.. right now it use your server setting OR you current iOS locale and I plan to allow an option in the settings for the target language.
