### ISSUE TITLE
Feature request: Update action counts on status detail

### ISSUE THREAD

**Issue by jakewinter1** [Dimillian/IceCubesApp#827]
On smaller instances action counts can be significantly understated and meaningless from local (pretty much all zeroes), so it’s great to hide the counts with the “Status action buttons” setting. What would be even better is when opening status detail, allow the counts but fetch the accurate ones from remote local with all the replies, instead of continuing to display zeroes.
![AEBB3C9B-BE59-4D83-B3FE-74E2F9819488](https://user-images.githubusercontent.com/125241927/218387939-30f0c6ce-fe09-4417-84be-de0eaf06c8ac.jpeg)

**Comment by Dimillian** [comment]
This is done now
