### ISSUE TITLE
Bug: Duplicate notifications for polls ending

### ISSUE THREAD

**Issue by xurble** [Dimillian/IceCubesApp#849]
## Environment:

 - OS: 
 iOS & macOS
 - IceCubesApp version: 
 1.4.7 

## Description

I've started getting duplicate notifications.  But only for polls ending.  All others seem fine.

## Related Issues

 - [x] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
It's a backend issue :/

**Comment by xurble** [comment]
By backend you mean actual mastodon? Cause I just noticed they're duped in every client I try 😬

**Comment by Dimillian** [comment]
Yup.
