### ISSUE TITLE
Feature request: allow disabling alt text button

### ISSUE THREAD

**Issue by Cyberbeni** [Dimillian/IceCubesApp#850]
It often overlaps the text of meme images. Attched example.

![image](https://user-images.githubusercontent.com/8356175/218697684-5f404524-16ee-4e83-9593-f7f9a4ff4862.png)

**Comment by sothawo** [comment]
Valid point, as not everybody needs or reads alt-texts. Will have a look at that in my lunch break.

**Comment by sothawo** [comment]
lunch break finished.

**Comment by Dimillian** [comment]
🥪
