### ISSUE TITLE
Bug: sharing or pasting screenshot doesn’t work

### ISSUE THREAD

**Issue by echidistanti** [Dimillian/IceCubesApp#864]
## Environment:

 - OS: iOS 16.3.1
 
 - IceCubesApp version: 1.4.7
 

## Description

If I take a screenshot and try to share it (or copy it to the Clipboard and then paste it into the composer) nothing happens. If I copy an image from the film and paste it, it works regularly

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by sothawo** [comment]
Can you please edit the issue and add the information as to which OS you are using and which version of IceCubes?

**Comment by echidistanti** [comment]
Sorry I wrote that info in the comment 🤭
