### ISSUE TITLE
Bug: Editor lets you change visibility but it has no effect

### ISSUE THREAD

**Issue by henrik** [Dimillian/IceCubesApp#868]
iOS 1.4.8. 

If I edit a post with visibility “Everyone”, I can change that dropdown to “Unlisted”. 

But if I save, it still shows as “Everyone” on the post and if I edit it again, that’s also what the editor says.

Perhaps it can’t actually be changed after the fact and should not be enabled in the edit view?

**Comment by Dimillian** [comment]
I have to check it's not the first report. I guess if it doesn't change then maybe it can't be changed server side.
