### ISSUE TITLE
Bug: post message always have language detection

### ISSUE THREAD

**Issue by twoheartliu** [Dimillian/IceCubesApp#871]
## Environment:

 - iOS v16.2
 
 - IceCubesApp version: 
 
IceCubesApp v1.4.8
## Description

![image](https://user-images.githubusercontent.com/19301712/218918041-78029de9-2fb4-477e-848d-3aaf528db071.png)
It seems that language detection must be set up for every users, otherwise it will keep coming.
## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Will be solved in 1.6.0
