### ISSUE TITLE
Bug: wrong notification count after internet reconnect 

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#881]
## Environment:
iOS 16.2, icecubes 1.4.8

## Description
The app is running when I have an internet connection. For some time I have no internet connection. When I reconnect to the internet, I get a notification and „1“ is displayed as notification count. When I open the notification tab of the app, there are more than 1 new notifications.

**Comment by Dimillian** [comment]
will close this one for now. This is not something I can fix. Mastodon don't send the badge for unread notifications. This is just an +1 update mechanism. Not doable for now.
