### ISSUE TITLE
Feature request: Share post as image

### ISSUE THREAD

**Issue by alexsereno** [Dimillian/IceCubesApp#885]
Several good Twitter apps have the option to long press the share icon to share a post as an image, vs tap to share normally.

This feature is super useful since it's a lost faster than the screenshot tool and lets you watermark it with an ice cubes link etc. Extra reasoning: it's really hard for non mastodon people to see mastodon content. Quickly share as image vs screenshot lets me send something to a non-mastodon user in an engaging and simple way.

**Comment by echidistanti** [comment]
I would use to share toots to other social networks like instagram (memes etc.) would be dope

**Comment by ivey** [comment]
Thirding this, it's the one thing I miss from other clients. I use it to post dumb stuff to Tumblr.

**Comment by Dimillian** [comment]
I'm looking at doing this one soon. It'll probably be a custom action the standard share sheet.
