### ISSUE TITLE
Bug: favorite/boost count wrong in profile tab

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#888]
## Environment:
iOS 16.2, icecubes 1.5.0

## Description
If a post from me is favorited/boosted, i can’t see the correct favorite/boost count on my profile tab. Even reloading the tab by dragging down doesn’t help anymore. This worked before. The correct count now only is shown, if I switch to another account and switch back or restart the app.

**Comment by blueturtleai** [comment]
Pulling doesn’t help. Tbh, this is a strange way the app works 😀! I think everybody expects to see the correct favorite/boost count everywhere.

**Comment by Dimillian** [comment]
Of course, I'm not saying it's ideal I'm just saying that I did nothing for it to works properly ... yet :)
