### ISSUE TITLE
[Bug] Tapping a post shows the same post in a nested view more than once

### ISSUE THREAD

**Issue by jsynowiec** [Dimillian/IceCubesApp#89]
There should be only a single nested level when tapping a post. On the post details view, I shouldn't be able to tap it once more and push the same view onto stack.

https://user-images.githubusercontent.com/1029142/212967489-27049204-3123-4c38-bc76-74f0cfe53e4b.mov

**Comment by Dimillian** [comment]
Closed in latest beta
