### ISSUE TITLE
Feature request: San Francisco Rounded in the roster of custom fonts

### ISSUE THREAD

**Issue by echidistanti** [Dimillian/IceCubesApp#890]
I don't know if there is a technical reason, wouldn't it be possible to introduce San Francisco Pro Rounded among the custom fonts?

**Comment by kirocop** [comment]
Great idea

**Comment by Dimillian** [comment]
I'll tell you, I have no idea why it's not there.

**Comment by Dimillian** [comment]
![image](https://user-images.githubusercontent.com/535509/219126873-94bb131b-b907-4701-9a67-6ff4bb1215ae.png)
Done for next version!

**Comment by echidistanti** [comment]
wow i'm impressed about how fast your reply was 😯
