### ISSUE TITLE
Bug: with multiple accounts, in app notification badge counts unread notification for all the accounts

### ISSUE THREAD

**Issue by echidistanti** [Dimillian/IceCubesApp#894]
## Environment:

 - OS: iOS 16.3.1
 
 - IceCubesApp version: 1.5.0
 

## Description

When using more than one account the app should to keep track of notifications separately for each account. If you have new notifications on your personal Mastodon account, the notification badge (the little number that appears on the icon) should only show the count for that account, not for your work Mastodon account or any other accounts you might have added.

As it is by now the app is counting all the unread notifications across all your accounts and displaying that total count on the notification badge. So even if you only have new notifications on one account, the badge will show a higher number that includes all of the unread notifications from all your accounts.

I think this can be confusing and make it harder to keep track of which account has new notifications. For example, if the badge shows that you have 10 new notifications, but only 2 of those are for the account you're currently using, you might waste time checking the wrong account or miss important notifications.

![3e17e1d0b4c7d606](https://user-images.githubusercontent.com/5138294/219136233-682d85bb-8739-4378-9dad-b17f2f912115.jpg)

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by blueturtleai** [comment]
After implementation: will I still see, that there are notifications for other accounts than the currently active?
