### ISSUE TITLE
Bug: iOS Calendar Alarm notification hidden while in IceCubes?

### ISSUE THREAD

**Issue by LorenAmelang** [Dimillian/IceCubesApp#897]
## Environment:

 - OS: 16.3
 
 - IceCubesApp version: 1.5.0
 

## Description

This morning I has an iOS Calendar Alarm set with "at time of event" and "30 minutes before" chosen. The 30 minute before notification worked, while the iPhone was idle, and once I was ready for the event I began reading my timeline in IceCubes. The time of event notification was not shown or sounded! Once I noticed the time was well past, I checked the iPhone notification screen and it was shown there. 

Just tried this again, with a time ~10 minutes out and 5 minutes before that. The first one played the Alarm sound and dropped down over the top of my IceCubes timeline. The time of event notification did not show at all. And this time it did not show on the iPhone notification screen either. 

I have no clue if this might be an Apple thing or an IceCubes thing, not much experience with using apps during alarms. I know I get dropdown notifications over IceCubes for calls and texts...  There was also a wild screen jerk due to a CW post loading above my timeline position about the time this morning's alarm failed, but definitely no alarm sound. 

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Unfortunately I don't see how this could be related to Ice Cubes. Most probably it's actually an iOS 16 bug if you receive notifications at the same time?

**Comment by LorenAmelang** [comment]
Tried it today with 1.5.1 and both notifications dropped down and stayed until I closed them. Probably Apple randomness yesterday...
