### ISSUE TITLE
Noticeable lag when typing search term

### ISSUE THREAD

**Issue by jsynowiec** [Dimillian/IceCubesApp#90]
This is not a bug, but rather a UX improvement request. There is a noticeable delay when typing the search term and the caret is jumping behind the last character. I noticed this on the Mac app running on Apple Silicon.

https://user-images.githubusercontent.com/1029142/212968263-739039d0-e49e-44fe-b433-56f5a3bccdf8.mov

**Comment by scalbatty** [comment]
Also happens on iOS
