### ISSUE TITLE
Feature request: Actions Buttons foldable / drawer option

### ISSUE THREAD

**Issue by SvenCSchmidt** [Dimillian/IceCubesApp#901]
Would love to see an option to make the Action Buttons un-/foldable besides „buttons only“ and „no buttons“ like the „Drawer“ option in Ivory. Love to have as much space as possible for toots (text), but was never a fan of long-press-menus for things I want to do quickly like Fav or Boost.

**Comment by sothawo** [comment]
you can use swipe actions instead of the long press menu

**Comment by SvenCSchmidt** [comment]
Yes, I know, but this two action swipes are imho too wobbly to hit recurring safe. Swiped a ms too long and you activate the outside action instead of have the option to choose.
Just a short tap to expand the action buttons below the tapped toot is imho a really good idea of design and is very good to handle.

**Comment by Dimillian** [comment]
I'll close this one as "this is not Ivory". I was never fan of the drawer so not something I'll add anytime soon. They actually did add an option to not have a drawer before the initial release.
