### ISSUE TITLE
Bug: Infinite scroll (posts appear multiple times)

### ISSUE THREAD

**Issue by alakoring** [Dimillian/IceCubesApp#908]
## Environment:
 - OS: 
iPadOS 16.3.1

 - IceCubesApp version: 
 1.5.0

## Description

scrolling to show new items is looping — the same items appear again. 

See video

## Related Issues

 - [ x ] Search that this bugs don't already exist before creating it.

**Comment by alakoring** [comment]
I had to downsample the video to get it to load, but I think you can spot TETRIS appearing more than once as I scroll

https://user-images.githubusercontent.com/12171257/219438981-7a4d6044-85d9-4cfa-ad87-10a63148120c.mov

**Comment by alakoring** [comment]
Although it was repeatable, the issue seems to have resolved itself. Scrolling now stops at the top of the timeline. Not sure if I did anything different in the mean time.

**Comment by alakoring** [comment]
This happened again just now. I will update to 1.5.1.

**Comment by darrinsmart** [comment]
I've noticed this a few times too. Haven't been able to narrow it down to any particular action.

**Comment by alakoring** [comment]
I don’t have anything new to add but it’s still sometimes happening in 1.9.6.

**Comment by Dimillian** [comment]
Fixed on main update will be out soon
