### ISSUE TITLE
Bug: Scrolling on iPad is horribly stuttering / Timeline jumps while scrolling

### ISSUE THREAD

**Issue by jacotec** [Dimillian/IceCubesApp#911]
## Environment:

 - OS: 
 IPadOS 16.3.1
 - IceCubesApp version: 
1.5.1

## Description

On my iPad Pro 10.5 scrolling in the timeline feels horribly stuttering. Interesting fact: Even when scrolling slowly(!) upwards, the timeline feels like it jumps up and down. Probably related to loading pictures and URL previews.

Unfortunately this makes IceCubes unusable for me at the iPad. iPhone is OK.

No relation to content or my device itself as Ivory and Toot! are scrolling perfectly smooth on the same device.

Posted a video sample here: https://majak.de/@marco/109875960086015651

**Comment by Dimillian** [comment]
https://user-images.githubusercontent.com/535509/219567269-8c3b2530-02e8-480d-8c4b-ae7ad3398736.mov

Adding my own video on macOS this morning. It seems like it's backed into SwiftUI List tho and there is indeed a bug when scrolling up only on those devices....

**Comment by jacotec** [comment]
@Dimillian That looks pretty similar 😉

**Comment by Dimillian** [comment]
FYI I've filled a feedback and a DTS support ticket with Apple. At this point there is nothing I can do (or that I know I can do :/) This been the most annoying issue of the whole app.

**Comment by jacotec** [comment]
Ahm, but why do other apps work perfectly on my iPad if there is nothing you can do?

**Comment by Dimillian** [comment]
This app use SwiftUI and unfortunately it have a few shortcomings :/

**Comment by jacotec** [comment]
That's no good news 🥺
Does Apple need to fix it in IOS or XCode?

**Comment by xjliu-sequoia** [comment]
could you paste the feedback link？ @Dimillian

**Comment by Dimillian** [comment]
FB11994040

**Comment by Dimillian** [comment]
I got feedback that they're aware of it, but as of now there is no workarounds unless not using SwiftUI. Crossing finger it could be solved in iOS 16.4 but I have low hopes for this.

**Comment by xjliu-sequoia** [comment]
thanks a lot！

**Comment by jacotec** [comment]
Thank for your feedback @Dimillian !
It's a pity I can't use Icecubes on my iPad due to this. Hoping for a quick fix.

**Comment by jacotec** [comment]
@Dimillian Any update at which point Icecubes will work on an iPad?
