### ISSUE TITLE
Bug: Can't copy photo from library and paste into post

### ISSUE THREAD

**Issue by RobATX** [Dimillian/IceCubesApp#912]
## Environment:

 - OS: 16.3.1
 
 - IceCubesApp version: 
  Latest

## Description

Still can't paste a photo copied from my library into a post. 

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
for me it works using copy photo within the share sheet form the iOS photo library. Maybe you have another flow?

**Comment by RobATX** [comment]
Interesting. I have an iPhone 14 Pro Max. I did the same. Go to photos, use share sheet to copy, go to IceCubes compose, tap hold for Paste prompt, tap Paste. Nothing. I now just killed app and tried again and it WORKED. SIGH. 🤦‍♂️ Thanks for verifying. Sorry for the red herring.
