### ISSUE TITLE
Feature request: Collapse long post

### ISSUE THREAD

**Issue by Cyrivs89** [Dimillian/IceCubesApp#914]
I think a great feature, which I've seen in other apps like Ivory, Toot!, Trunks or Tusker, is the ability to collapse long posts, so that you have to press something like "Read More" to read the whole text.

**Comment by sothawo** [comment]
Would like to see that as well, I already had some first look at it but did not dig deeper yet.

**Comment by LorenAmelang** [comment]
Would also love this - my Neuromatch instance has a 10000 char post limit! But be sure it can be activated from both top and bottom of the post, for people who scroll either way. Even if the post is collapsed it may be more than a screenfull on a tiny phone.

**Comment by sothawo** [comment]
I do not think about actively collapsing by the user. Wouldn't it be better if long posts (_long_ to be defined) would be initially collapsed to their lets say first 100 words with a small button "read complete post"? When that button is tapped, the post would be expanded. Perhaps with the option to collapse again.

**Comment by LorenAmelang** [comment]
Mastodon web client 4.02 does that: 
![image](https://user-images.githubusercontent.com/1297090/219974706-5bb15acc-cf66-4871-9a51-e518063df78b.png)

"Read More" opens an expanded detail view. You can close it and go "Back" to the previous collapsed view. If the timeline is _always_ collapsed that works fine for me. 

But "100 words" is probably too sensitive. What I'd like would be defined in screen heights of the text section - if it fills more than one whole screen on the current device, collapse it. 

There's an "eye" icon on the Mastodon expanded post that says "Show less/more for all", but it doesn't change expand/collapse. Reddit thinks it is about CW visibility...

**Comment by sothawo** [comment]
The eye is for CW, mostly on a thread so that you don't have to expand every answer when your setting is to have CWs collapsed.

The 100 was just a number I put in. I am not sure if dynamically calculating the visible length of the text in relation to the screen is the best solution; people with large displays might like to see a collapsed post and 2 or three more.

**Comment by sothawo** [comment]
@Dimillian can you assign this to me please? I am already trying things out here.
