### ISSUE TITLE
Bug: Repeatable load glitches on specific posts, in timeline or detail - screen video

### ISSUE THREAD

**Issue by LorenAmelang** [Dimillian/IceCubesApp#916]
## Environment:

 - OS: iOS 16.3
 
 - IceCubesApp version: 1.5.1
 

## Description

The weird loading of some posts has gotten weirder in 1.5.1. I captured one repeatable one. 

https://user-images.githubusercontent.com/1297090/219561447-36db3681-323c-41bb-9bcb-428f1e98fc73.mp4

The "5 of 7" post pops up above its quoted image. Note the later posts of the thread are not directly above...  

https://user-images.githubusercontent.com/1297090/219561715-029142fb-ce3d-4253-a805-4e43c823e9e7.mp4

Later the "7 of 7" post sweeps in from both directions, every time it is scrolled past. 

https://user-images.githubusercontent.com/1297090/219562203-0a6e4664-6321-42c5-a33f-95b46e433198.mp4

In Detail view, the "7 of 7" post slides down toward its buttons, even scrolling the screen up. You can repeat it as many times as you like. 

In older versions, I only saw this kind of thing when I first scrolled to a new unseen post. Now these happen every time certain specific posts appear, scrolling either direction. 

Is that a clue? 

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by LorenAmelang** [comment]
Tried the iPad M1 12.9 last night - same thread did pretty much the same jumps. This morning I discovered I'd accidentally boosted the "7 of 7" post yesterday - essential tremor wrecks my finger control! The Detail view of the boosted thread also jumps all over, repeatably as many times as I scroll it:

https://user-images.githubusercontent.com/1297090/219789773-52e7c0dd-255f-4228-a3fa-e5048e7f26f1.mp4

**Comment by kean** [comment]
It looks better with the animation removed, but there are still some weird state transitions, especially if the embed fetch fails. Ideally, it would display an error if it fails to load without affecting the cell height.

Related: there is no memory cache for embedded statuses, and it might be a good area of improvement. It could also try to check if this embedded status is already present somewhere else in the timeline to avoid the network call entirely.

> It would've been nice to prefetch these embeds during the page load to eliminate the dynamic resize, but looks like it's not possible, especially given that some of them might be on a different instance. And even in the same instance, I can't find an API to fetch statuses by a list of IDs.

**Comment by kean** [comment]
I think adding embeds to `TimelinePrefetcher` should help. In most cases it'll finish offscreen, eliminating the dynamic resize.

**Comment by LorenAmelang** [comment]
@kean Way out of my knowledge here, but I'm not sure "offscreen" is a solution. I often see the post I'm reading pushed way down my screen by one above it that I haven't seen at all yet loading an embed or a CW. 

Maybe the question is what is "offscreen"? I notice the haptic pulse happens before I've drug down far enough for the full post header to be visible...  About the same point where the resize of the next post above it pushes down if it is going to. 

Also - I have CW hiding fully disabled. Maybe the app plans for it to be enabled and discovers my preference later? 

As for "different instance", I usually find that once the post has been fetched the weirdness doesn't re-appear. The screen caps here were very surprising, repeating even when already in my timeline, and in boosts of that post by other users.
