### ISSUE TITLE
Crash on clicking to private profile

### ISSUE THREAD

**Issue by alper** [Dimillian/IceCubesApp#918]
I just had a reliable crash browsing to a follower's private profile.

Latest iOS version of Icecubes.

**Comment by Dimillian** [comment]
Do you have a post with the link to the profile or anything similar?

**Comment by Dimillian** [comment]
Anyone can reproduce that? I've not been able to ever reproduce it.

**Comment by alper** [comment]
I had it happen with another profile but going back wouldn't reproduce it. 

Do you have crash reporting installed? That should surface it, if it's more than a fluke.

**Comment by Dimillian** [comment]
I do have it and for now I don't see anything related to profile. Or anything new by the way. This is weird as it's not the first report.

**Comment by alper** [comment]
This one does it for me now a couple of times in a row: https://mstdn.social/@marick/

**Comment by alper** [comment]
Now I have a video. First open no crash. Do some stuff click profile boom.

**Comment by alper** [comment]
Here's the video: 
https://user-images.githubusercontent.com/72429/219871052-b5b03402-54e7-4a6a-b825-164d6f670e7a.mov

**Comment by stodge** [comment]
I experience crashes 95% of the time when viewing the profile for @nakedcardboard@wargamers.social. It’s not a private profile but I thought I’d post I hear in case it helps identify a bug.

I’m on iOS 16.1.2.

**Comment by alper** [comment]
Maybe that's right then. I got stuck on that version because the iPhone was full. Upgraded now.

**Comment by Dimillian** [comment]
It's an iOS bug at this point. I've confirmed it. Related to iOS 16.1.X. Please update to 16.3 when you can. I'll soon close this one.

**Comment by stodge** [comment]
Ooops, good to know. I have a brand new phone and I thought it had already updated to the latest iOS.
