### ISSUE TITLE
Bug: Seems no way to delete Filters, sometimes can't even rename them? 

### ISSUE THREAD

**Issue by LorenAmelang** [Dimillian/IceCubesApp#923]
## Environment:

 - OS: iOS 16.3
 
 - IceCubesApp version: 1.5.2
 

## Description

I made a bunch of test Filters when I first learned of them. They are trash now, but I can't find any way to delete them. I can delete the filtered terms, so I guess they are harmless, but they clutter my screen and mind. 

I thought I'd rename them to "x, y, z, ..." to make their junk status obvious, but it took a random number of failed tries before the new name was saved. One wouldn't change until I retried the next day...  

Maybe I'm mossing something? 

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by sothawo** [comment]
Swipe to the left on the filter entry in the list?
![grafik](https://user-images.githubusercontent.com/8456476/219802467-9b534ed6-3a38-430b-b1dd-b49e818aa144.png)

**Comment by sothawo** [comment]
As for renaming: When editing the title, before tapping "Done" in the top right, make sure to have hit the "enter' key so that the input field loses the focus, otherwise your change is lost.

**Comment by LorenAmelang** [comment]
Thank You! Worked immediately. Even though I have all the timeline swipes disabled because my finger tremor too often jerks when I don't intend to.

**Comment by Dimillian** [comment]
I'll improve the UI to add clear delete button. Thanks for the report!

**Comment by sothawo** [comment]
timeline swipes are a different thing; this is swiping in standard lists
