### ISSUE TITLE
Feature request: better handling of notifications with several accounts 

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#928]
I have several accounts. When I see there are new notifications, I tap on the notifications tab. When the notification is not for the account, which is currently active, no new notification is shown in the tab. I have to switch then to the other accounts to find the account, for which the notification occurred.

Not sure, if/how this could be improved. But the current state is a bit annoying.

**Comment by pjolt** [comment]
This seems related to #894

**Comment by Dimillian** [comment]
Yup and it's planned for very soon :)
