### ISSUE TITLE
[Feature request] Prepend the language list with the frequently used ones or allow marking languages as preferred

### ISSUE THREAD

**Issue by jsynowiec** [Dimillian/IceCubesApp#93]
This is a follow-up request to #76. It would be nice to have the frequently used, or starred, languages at the top of the language list. I imagine that the majority of users will use two, maybe three languages interchangeably, so having to search for it requires repetitive, unnecessary actions.

**Comment by Dean151** [comment]
Last used languages are already live. Is this still to be left open?

**Comment by alper** [comment]
Here's proof that this is done.
![IMG_45B3F34540B5-1](https://user-images.githubusercontent.com/72429/220448443-c9587ee1-0dd6-4c3b-a620-66b082f70079.jpeg)
