### ISSUE TITLE
Image size in the timeline

### ISSUE THREAD

**Issue by kean** [Dimillian/IceCubesApp#931]
I noticed that the app uses `url` and not `previewUrl` for images in the timeline. Is there a good reason not to use the previews?

Let's take the following image from the timeline as an example:

- Original (1247x1663) https://files.mastodon.social/media_attachments/files/109/884/136/729/763/293/original/1ee92b4fcac2dabc.jpeg
- Preview (416x554) https://files.mastodon.social/media_attachments/files/109/884/136/729/763/293/small/1ee92b4fcac2dabc.jpeg

The original is too high resolution for the timeline. The main concern isn't necessary the image data size, but how much memory it takes to bitmap it: ~8 MB. This will lead to high memory usage.

The image previews displayed in a grid take only 172 pt width. 416px is plenty to display it with high quality and in comparison, it takes less than 1 MB to bitmap. If there is only one image, it'll might make sense to use the original, but scale it.

I suggest the following improvements:
- Use `previewUrl` (note: [prefetcher](https://github.com/Dimillian/IceCubesApp/pull/930) needs to use the same URLs)
- Use `ImageProcessors.resize` to resize the images in the background to exactly match the display size (challenge: computing this size ahead of time and communication it to the [prefetcher](https://github.com/Dimillian/IceCubesApp/pull/930) too)
- A further optimization is to crop the preview to reduce memory usage even further

**Comment by Dimillian** [comment]
This is great, added both (preview and resize processor) to your PR: https://github.com/Dimillian/IceCubesApp/pull/930

**Comment by Dimillian** [comment]
Will also prefetch image card
