### ISSUE TITLE
Bug: Fails to build when target is Mac v13.1

### ISSUE THREAD

**Issue by digitalnomd** [Dimillian/IceCubesApp#934]
## Environment:

 - OS: 
MacOS 13.1
 - IceCubesApp version: 
Commit ID: 7112e6515bc41844c569bac9611bdd1624cd1077 `main`

## Description

I'd like to build the client locally and followed the steps in the README but I am getting the following errors:

```
Failed to register bundle identifier. The app identifier "com.example.IceCubesApp.IceCubesNotifications" cannot be registered to your development team because it is not available. Change your bundle identifier to a unique string to try again.
...
No profiles for 'com.example.IceCubesApp.IceCubesNotifications' were found. Xcode couldn't find any iOS App Development provisioning profiles matching 'com.example.IceCubesApp.IceCubesNotifications'.
...
```

## Related Issues

 None found that are open.

**Comment by AlanQuatermain** [comment]
I expect you'll need to change the bundle ID to something else. Bundle IDs on the Apple Developer site are intended to be unique, and someone else has run using `com.example.IceCubesApp.*`, so Xcode registered that bundle ID and attached it to their developer account.

I'd suggest changing the bundle IDs to something like `com.digitalnomd.example.IceCubesApp.*` or suchlike when building for yourself. The ADC `SAMPLE_CODE_DISAMBIGUATOR` setting only goes so far, unfortunately.
