### ISSUE TITLE
Bug: Multiple choice polls show incorrect numbers 

### ISSUE THREAD

**Issue by atomicbird** [Dimillian/IceCubesApp#952]
## Environment:

 - OS: 
 
iPad OS 16.3.1
 - IceCubesApp version: 
 
1.5.2

## Description

If a poll allows multiple choice responses, Ice Cube displays the results incorrectly. Numbers are scaled so that results add up to 100%, which does not make sense for multiple choice polls. 

An example: https://androiddev.social/@cliffwade/109886759066153225

The Mastodon web interface displays results correctly. Percentages add up to more than 100% because people could choose multiple options. 

![162F0432-88B7-4C9D-A6AA-31FA410437B2](https://user-images.githubusercontent.com/15008/219966766-28569d4a-3c42-46db-ac60-f1d976c0d5a0.jpeg)

Ice Cubes shows incorrect numbers that add up to 100%.

![443054A3-A179-4BCE-A86C-FA659E206B6B](https://user-images.githubusercontent.com/15008/219966776-c8b474d0-d644-45b6-a113-e71af1a22cf0.jpeg)

**Comment by sothawo** [comment]
Will check this when back from work and at home.
