### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by xurble** [Dimillian/IceCubesApp#961]
## Environment:

 - OS: 
 macOS, iOS
 - IceCubesApp version: 
 main branch, not present in 1.5.2

## Description
- Live updating of the preview post in settings no longer works when you change font / font size.  
- Changing font / font size does not update on the timeline until it is refreshed

Happy to look at this if you like, but you might just know what to do, since it's probably a recent timeline scroll optimization.

## Related Issues

 - [X] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment]
Interesting, I think something got disconnected from Theme env, It'll take a look.
