### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by skin-soc** [Dimillian/IceCubesApp#962]
## Environment:

 - OS: 
iOS 16.3.1
 - IceCubesApp version: 
1.5.3

## Description

Under SETTINGS -> General -> Display Settings -> **Tint Colour**, when Match System is enabled, the Tint Colour does NOT reflect the `$classic-highlight-color` (variables.scss) of the instance, instead it reverts to a standard Mastodon brand purple, no matter what the highlight colour of the instance is.

**Comment by Dimillian** [comment]
I'm closing this as it's absolutely not supposed to honour instance colour at this moment. It's entirely up to the theme or the user own choice. Maybe one day tho.
