### ISSUE TITLE
Bug: “follows you” not visible in some cases

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#984]
## Environment:
iPhone SE 2020, iOS 16.2, icecubes 1.5.5

## Description
In some cases I don’t see the “follows you” although the account follows me. This happens in portrait, when I switch to landscape I can see it, but it is also cut a bit. Example: https://universeodon.com/@kat3638

**Comment by sothawo** [comment]
you might better provide screenshots

**Comment by blueturtleai** [comment]
There isn’t much to see, the text is just missing 😀

**Comment by Dimillian** [comment]
I've seen a few mentions on this. Will look into why.
