### ISSUE TITLE
Bug: Crash when navigating to profile page from timeline

### ISSUE THREAD

**Issue by paulhart** [Dimillian/IceCubesApp#994]
## Environment:

 - OS: 16.1.2
 - IceCubesApp version: 1.5.6

## Description

Application crashes when visiting a user profile. Screen updates to indicate it is preparing to render the profile, and then hard quits.

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by paulhart** [comment]
This appears to be okay when using the search, and navigating between profiles where the link is in the profile.

**Comment by Dimillian** [comment]
Can you please update to iOS 16.3? We made some fixes for 16.1 but if you say it crash ut means there is still some issues about it.

**Comment by Dimillian** [comment]
And it's a duplicate too!

**Comment by paulhart** [comment]
Resolved - sorry, I didn't check the closed issues for duplicates :(
