### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by sanguish** [Dimillian/IceCubesApp#997]
## Environment:

 - OS: iOS 16.4 1
 - IceCubesApp version: 1.5.6

## Description

The new movie badging need to scale better for the notifications tab

See https://iosdev.space/@sanguish/109906635957575119

![image](https://user-images.githubusercontent.com/6151362/220531940-194ddea9-28df-454c-99b3-fc747f4d5b44.jpeg)

**Comment by Dimillian** [comment]
Fixed in next version
